version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: subflix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: subflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - subflix-postgres-data:/var/lib/postgresql/data

volumes:
  subflix-postgres-data:
