const Map<String, String> kStringsZh = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': '搜索片名',
  'searchMovieOrSeriesTitle': '搜索电影或剧集',
  'searchMovieOrSeriesSubtitle': '找到片名、查看字幕来源，并通过几次点击启动翻译任务。',
  'searchHintText': '搜索 Dune、Breaking Bad、Severance...',
  'searchMockTitle': '在模拟目录中搜索任何内容',
  'searchMockMessage':
      '试试 Inception、Dune、Breaking Bad、Severance 或 The Last of Us，体验字幕来源流程。',
  'searchFailedTitle': '搜索失败',
  'noTitlesMatchedTitle': '没有匹配结果',
  'noTitlesMatchedMessage': '我们在模拟目录中找不到这个标题。请尝试更宽泛的搜索，或使用建议标题。',
  'searchTrendingTitle': '热门搜索',
  'searchLoadingLabel': '正在搜索...',
  'searchFoundResults': '找到 {count} 条与“{query}”相关的结果',
  'searchNoResultsFor': '没有找到“{query}”的结果',
  'searchTryDifferentKeywords': '试试其他关键词。',
  'retry': '重试',
  'retryTranslation': '重新翻译',
  'uploadSubtitleTitle': '上传字幕',
  'uploadIntroTitle': '使用你自己的字幕文件',
  'uploadIntroSubtitle': '导入英文 `.srt` 或 `.vtt` 文件，交给后端校验并解析，然后继续进入翻译设置。',
  'uploadChooseFile': '选择字幕文件',
  'uploadSupportedFormatsTitle': '支持的格式',
  'uploadSupportedFormatsSubtitle': '英文 `.srt` 和 `.vtt` 字幕文件',
  'uploadOpeningPicker': '正在打开选择器...',
  'uploadChooseFileShort': '选择文件',
  'uploadPickSubtitle': '选择字幕文件',
  'uploadPickedFile': '已选择字幕文件',
  'uploadUseDemoFile': '使用演示文件',
  'uploadFailedTitle': '文件导入失败',
  'uploadFailedMessage': '我们无法读取这个字幕文件。请尝试其他文件，或使用更小的导出文件。',
  'uploadFailedFallback': '请尝试其他字幕文件。',
  'tryAgain': '再试一次',
  'uploadMetadataTitle': '字幕详情',
  'uploadReadyTitle': '可以开始翻译',
  'uploadLineCount': '{lineCount} 行',
  'uploadEnglishSource': '英文来源',
  'uploadContinueSetup': '继续进行翻译设置',
  'translateSetupTitle': '翻译设置',
  'translateSetupSubtitle': '选择目标语言，查看字幕来源，然后启动后端翻译任务。',
  'translateSetupSourceTitle': '源字幕',
  'translateSetupLanguageTitle': '翻译为',
  'translateSetupOptionsTitle': '选项',
  'translateSetupSelectLanguage': '选择语言',
  'translateSetupReadyTitle': 'AI 翻译已就绪',
  'translateSetupReadyBody':
      '我们的翻译流程会将这份字幕转换为 {language}，同时保留时间轴并保持清晰的 cue 结构。',
  'translateSetupPreserveTiming': '保留时间轴',
  'translateSetupPreserveTimingBody': '让原始字幕时间与源文件保持一致。',
  'translateSetupAutoDetect': '自动识别格式',
  'translateSetupAutoDetectBody': '自动选择合适的字幕输出结构。',
  'subtitleSourceFormatLabel': '{format} 字幕来源',
  'targetLanguage': '目标语言',
  'startTranslation': '开始翻译',
  'translationProgressTitle': '翻译进度',
  'translationProgressHeadline': 'AI 字幕翻译进行中',
  'translationFailedTitle': '翻译未能完成',
  'translationFailedMessage': '出了点问题。',
  'translationStageQueued': '已加入翻译队列',
  'translationStageIdle': '等待翻译请求',
  'translationStagePreparing': '正在准备字幕包',
  'translationStageAligning': '正在对齐时间戳和场景上下文',
  'translationStageGenerating': '正在生成字幕翻译',
  'translationStageReadability': '正在进行可读性优化',
  'translationStageReady': '翻译已完成',
  'translationResultCompleteTitle': '翻译完成',
  'translationResultCompleteSubtitle': '你的字幕已经可以预览或下载。',
  'translationResultDetailsTitle': '翻译详情',
  'translationResultMediaLabel': '作品标题',
  'translationResultSourceLabel': '源语言',
  'translationResultTargetLabel': '目标语言',
  'translationResultMethodAi': 'AI 翻译',
  'translationResultMetricsTitle': '质量指标',
  'translationResultConfidenceLabel': '翻译可信度',
  'translationResultTimingLabel': '时间精度',
  'translationResultTimingPreserved': '时间已保留',
  'translationResultProcessedIn': '处理耗时 {duration}',
  'translationResultWarning': '某些专业术语仍可能需要人工快速复核，以确保语境准确。',
  'translationResultPreviewCta': '预览字幕',
  'translationResultDownloadCta': '下载字幕',
  'translationResultHomeCta': '返回首页',
  'translationPreviewTitle': '翻译预览',
  'translationPreviewHeader': '查看翻译后的字幕',
  'translationPreviewSubtitle': '在 cue 中搜索、切换预览模式，并在确认结果无误后导出。',
  'translationPreviewSearchHint': '搜索字幕行',
  'previewModeOriginal': '原文',
  'previewModeTranslated': '译文',
  'previewModeBilingual': '双语',
  'previewNotReadyTitle': '预览 cue 暂时不可用',
  'previewNotReadyMessage': '翻译已完成，但后端尚未返回预览 cue。请稍后重新加载此页面。',
  'previewNoMatchesTitle': '没有匹配的字幕行',
  'previewNoMatchesMessage': '请尝试其他搜索词，或清除筛选以查看完整翻译。',
  'previewFailedTitle': '预览加载失败',
  'exportingLabel': '正在导出...',
  'exportSubtitleLabel': '导出翻译后的字幕',
  'exportedSnack': '已将 {fileName} 导出到 {path}',
  'exportFailedSnack': '导出失败：{error}',
  'metadataFormat': '格式',
  'metadataLines': '行数',
  'metadataLanguages': '语言',
  'metadataEstimatedDuration': '预计时长',
  'subtitleSourcesTitle': '英文字幕来源',
  'subtitleSourcesSubtitle': '为 {title}{target} 选择一个字幕来源，然后在下一步选择目标语言。',
  'subtitleSourcesBannerTitle': '可使用 AI 翻译',
  'subtitleSourcesBannerMessage': '选择字幕来源后，即可进入针对字幕时间轴优化过的精致翻译设置。',
  'subtitleSourcesFailedTitle': '无法加载字幕来源',
  'seriesSeasonsTitle': '选择季',
  'seriesSeasonsSubtitle': '选择 {title} 的某一季以浏览可用剧集。',
  'seriesSeasonLabel': '第 {seasonNumber} 季',
  'seriesSeasonMeta': '{episodeCount} 集{year}',
  'seriesEpisodesTitle': '第 {seasonNumber} 季',
  'seriesEpisodesSubtitle': '{episodeCount} 集{year}',
  'seriesEpisodeLabel': '第 {episodeNumber} 集',
  'seriesEpisodeMeta': '约 {runtime} 分钟',
  'historyTitle': '翻译历史',
  'historySubtitle': '重新打开以前的字幕任务，再次查看预览，或稍后导出。',
  'historyEmptyTitle': '历史为空',
  'historyEmptyMessage': '完成搜索或上传流程后，已翻译的字幕任务会显示在这里。',
  'historyFailedTitle': '无法加载历史记录',
  'historyCountLabel': '{count} 条翻译',
  'historyFilterAll': '全部',
  'historyFilterMovies': '电影',
  'historyFilterSeries': '剧集',
  'historyFilterCompleted': '已完成',
  'historyFilterAiTranslated': 'AI 翻译',
  'historyFilterFailed': '失败',
  'historyFilterReused': '复用',
  'historyFailedItemMessage': '翻译失败。点击重新开始。',
  'homeRecentJobsTitle': '最近任务',
  'homeRecentJobsSubtitle': '无需从头开始，直接重新打开你最近的字幕会话。',
  'homeNoRecentTitle': '还没有最近任务',
  'homeNoRecentMessage': '先搜索电影或上传字幕文件，你最近的翻译会显示在这里。',
  'homeFailedRecentTitle': '无法加载最近任务',
  'homeWelcomeTitle': '欢迎回来',
  'homeWelcomeSubtitle': '查找并翻译字幕',
  'homeSearchPlaceholder': '搜索电影或剧集...',
  'homeQuickSearch': '搜索',
  'homeQuickHistory': '历史',
  'homeQuickUpload': '上传',
  'homeViewAll': '查看全部',
  'homeTrendingNow': '当前热门',
  'homeTrustTitle': '为什么团队会信任它',
  'homeTrustSubtitle': '今天仍是模拟版，但结构已经按真正可上线的产品来设计。',
  'homeFutureTitle': '面向未来的仓库设计',
  'homeFutureSubtitle': '可替换的 mock 仓库让 UI 代码不受后端变化影响。',
  'homePreviewTitle': '以预览为先的翻译流程',
  'homePreviewSubtitle': '可在导出前通过原文、译文或双语视图检查结果。',
  'homeStatesTitle': '完善的状态体验',
  'homeStatesSubtitle': '加载、空状态、重试、校验以及模拟离线场景，从第一天起就是 UX 的一部分。',
  'navHome': '首页',
  'navHistory': '历史',
  'navSettings': '设置',
  'heroTitle': '更快翻译字幕',
  'heroSubtitle': '搜索电影和剧集目录、选择来源，并在几分钟内导出打磨过的翻译结果。',
  'heroBadge': '高级字幕工作流',
  'heroHeadline': '用接近工作室级别的流程翻译电影和剧集字幕。',
  'heroBody': '你可以选择可搜索的片名目录，或直接上传文件，然后在几分钟内完成预览并导出打磨过的字幕。',
  'heroSearchCta': '搜索电影 / 剧集',
  'heroUploadCta': '上传字幕',
  'heroStatPathsTitle': '2 条路径',
  'heroStatPathsValue': '搜索或上传',
  'heroStatLanguagesTitle': '10 种语言',
  'heroStatLanguagesValue': '可直接预览',
  'heroStatMockTitle': 'Mock API',
  'heroStatMockValue': '已为后端接入做好准备',
  'settingsTitle': '设置',
  'settingsSubtitle': '管理你的偏好',
  'settingsProfileName': 'SubFlix 用户',
  'settingsProfileTier': '高级会员',
  'settingsLanguageLabel': '首选目标语言',
  'settingsThemeLabel': '外观',
  'themeSystem': '跟随系统',
  'themeDark': '深色',
  'themeLight': '浅色',
  'settingsPremiumTitle': '高级功能占位',
  'settingsPremiumSubtitle': '后续我们可以在这里接入订阅、计费和云项目同步。',
  'settingsNotificationsTitle': '通知',
  'settingsNotificationsSubtitle': '管理通知偏好',
  'settingsHelpCenterTitle': '帮助中心',
  'settingsContactTitle': '联系我们',
  'settingsSupportTitle': '支持占位',
  'settingsSupportSubtitle': '模拟帮助与联系页面',
  'settingsPrivacyTitle': '隐私政策',
  'settingsPrivacySubtitle': '模拟隐私内容',
  'settingsTermsTitle': '服务条款',
  'settingsTermsSubtitle': '模拟条款内容',
  'settingsMaintenanceTitle': '维护',
  'settingsMaintenanceSubtitle': '清除此设备上由后端管理的翻译任务，并从空历史状态重新开始。',
  'settingsHistoryClearedSnack': '已清除此设备的翻译历史',
  'settingsAboutTitle': '关于 SubFlix',
  'settingsVersion': '版本 {version}',
  'settingsClearCache': '清除缓存',
  'settingsCacheCleared': '缓存已清除',
  'settingsFailedTitle': '设置加载失败',
  'legalPlaceholderBody': '此页面在演示应用中只是占位内容。请替换为你正式环境中的法律文本。',
  'legalTitlePrivacy': '隐私政策',
  'legalTitleTerms': '服务条款',
  'legalTitleSupport': '支持',
  'legalTitleAbout': '关于 SubFlix',
  'legalBodyPrivacy':
      'SubFlix 当前仅通过本地持久化在设备上保存模拟偏好和翻译历史。未来接入后端后，可替换为带身份验证的存储、审计记录以及服务器管理的保留策略。',
  'legalBodyTerms':
      '这个模拟版本旨在验证产品流程、UI 状态和架构边界。等后续接入正式的 NestJS 与 Postgres 后端后，法律层面可以扩展为真实的服务条款与数据处理说明。',
  'legalBodySupport': '目前支持页只是占位内容。正式版本中，这一部分可以接入邮件、问题反馈以及高级账户支持，同时保持应用框架不变。',
  'legalBodyAbout':
      'SubFlix 是一款偏高级体验的 Flutter 客户端，专注于 AI 字幕翻译。此版本使用 mock 仓库、人工延迟和本地持久化，以便在接入真实后端前先完善 UI 与架构。',
  'routeMissingSubtitleSourcesTitle': '字幕来源',
  'routeMissingSubtitleSourcesMessage': '我们无法判断应为哪个标题加载字幕来源。请从搜索重新开始。',
  'routeMissingSeriesSeasonsTitle': '剧集季列表',
  'routeMissingSeriesSeasonsMessage': '我们无法判断应加载哪部剧集。请从搜索重新开始。',
  'routeMissingSeasonEpisodesTitle': '本季剧集',
  'routeMissingSeasonEpisodesMessage': '我们无法判断应加载哪一季。请从搜索重新开始。',
  'routeMissingTranslationSetupTitle': '翻译设置',
  'routeMissingTranslationSetupMessage': '打开翻译设置页面前，必须先有一个字幕来源。',
  'routeMissingTranslationProgressTitle': '翻译进度',
  'routeMissingTranslationProgressMessage': '没有提供翻译请求。请从搜索或上传开始新的翻译。',
  'searchResultPopularity': '热度 {score}',
  'subtitleSourceLines': '{lineCount} 行',
  'subtitleSourceDownloads': '{downloads} 次下载',
  'subtitleSourceRating': '评分 {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': '电影',
  'mediaTypeSeries': '剧集',
  'jobReuseTranslation': '复用翻译',
  'jobReuseSubtitle': '复用字幕',
  'jobConfidence': '可信度：{level}',
  'jobOpenPreview': '打开预览',
  'onboardingPage1Title': '找到电影或剧集，并拉取可直接翻译的字幕。',
  'onboardingPage1Eyebrow': '搜索并获取',
  'onboardingPage1Description': '搜索标题、查看可用的英文字幕来源，然后启动一个几乎即时的翻译流程。',
  'onboardingPage1Highlight1': '可预测的模拟目录，方便稳定开发',
  'onboardingPage1Highlight2': '字幕来源质量标签与格式标识',
  'onboardingPage1Highlight3': '后续可无缝切换到真实后端',
  'onboardingPage2Title': '如果你已经有脚本，可直接上传 `.srt` 或 `.vtt` 文件。',
  'onboardingPage2Eyebrow': '使用自己的文件',
  'onboardingPage2Description': '导入字幕文件、校验格式，并在不离开应用的情况下走完整套精致翻译流程。',
  'onboardingPage2Highlight1': '本地文件校验与优雅的重试状态',
  'onboardingPage2Highlight2': '上传与搜索保持一致的翻译设置',
  'onboardingPage2Highlight3': '导出前先预览，让结果更透明',
  'onboardingPage3Title': '选择目标语言、预览字幕，并立即导出。',
  'onboardingPage3Eyebrow': '翻译并导出',
  'onboardingPage3Description': '在原文、译文和双语视图之间切换，回看历史记录，并在结果满意后导出干净的字幕文件。',
  'onboardingPage3Highlight1': '带元数据与搜索的快速预览控制',
  'onboardingPage3Highlight2': '历史记录让旧任务始终只差一次点击',
  'onboardingPage3Highlight3': '设计得像高级媒体工具，而不是演示页',
  'onboardingStart': '开始翻译',
  'onboardingNext': '下一步',
  'onboardingSkip': '跳过',
  'onboardingContinue': '继续',
  'onboardingEnterApp': '进入 SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'AI 驱动的字幕翻译',
  'splashPreparing': '正在准备你的字幕工作室',
  'brandSubtitleCompact': '字幕智能',
  'brandSubtitleFull': 'AI 字幕翻译工作室',
  'comingSoonTitle': '即将推出',
  'comingSoonMessage': '这个页面还在准备中。',
};
