const Map<String, String> kStringsFr = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Rechercher des titres',
  'searchMovieOrSeriesTitle': 'Rechercher un film ou une s?rie',
  'searchMovieOrSeriesSubtitle': 'Trouvez un titre, consultez les sources et lancez la traduction.',
  'searchHintText': 'Rechercher Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Rechercher dans le catalogue d?mo',
  'searchMockMessage': 'Essayez Inception, Dune, Breaking Bad, Severance, The Last of Us.',
  'searchFailedTitle': '?chec de la recherche',
  'noTitlesMatchedTitle': 'Aucun titre trouv?',
  'noTitlesMatchedMessage': 'Titre introuvable dans le catalogue d?mo. Essayez plus large.',
  'retry': 'R?essayer',
  'retryTranslation': 'Relancer la traduction',
  'uploadSubtitleTitle': 'Importer des sous-titres',
  'uploadIntroTitle': 'Importez votre fichier',
  'uploadIntroSubtitle': 'Importez un fichier `.srt` ou `.vtt` en anglais puis continuez.',
  'uploadChooseFile': 'Choisir un fichier',
  'uploadSupportedFormatsTitle': 'Formats pris en charge',
  'uploadSupportedFormatsSubtitle': 'Fichiers `.srt` et `.vtt` anglais',
  'uploadOpeningPicker': 'Ouverture du s?lecteur...',
  'uploadChooseFileShort': 'Choisir',
  'uploadPickSubtitle': 'Choisir un fichier de sous-titres',
  'uploadPickedFile': 'Fichier s?lectionn?',
  'uploadUseDemoFile': 'Utiliser un fichier d?mo',
  'uploadFailedTitle': 'Import ?chou?',
  'uploadFailedMessage': 'Impossible de lire ce fichier. Essayez un autre fichier.',
  'uploadFailedFallback': 'Veuillez r?essayer avec un autre fichier.',
  'tryAgain': 'R?essayer',
  'uploadMetadataTitle': 'D?tails des sous-titres',
  'uploadReadyTitle': 'Pr?t ? traduire',
  'uploadLineCount': '{lineCount} lignes',
  'uploadEnglishSource': 'Source anglaise',
  'uploadContinueSetup': 'Continuer la configuration',
  'translateSetupTitle': 'Configuration de traduction',
  'translateSetupSubtitle': 'Choisissez la langue cible et lancez la traduction.',
  'subtitleSourceFormatLabel': 'Source {format}',
  'targetLanguage': 'Langue cible',
  'startTranslation': 'D?marrer la traduction',
  'translationProgressTitle': 'Progression',
  'translationProgressHeadline': 'Traduction IA en cours',
  'translationFailedTitle': 'Traduction ?chou?e',
  'translationFailedMessage': 'Une erreur est survenue.',
  'translationStageQueued': 'En file d?attente',
  'translationStageIdle': 'En attente d?une demande',
  'translationStagePreparing': 'Pr?paration du paquet',
  'translationStageAligning': 'Alignement du timing',
  'translationStageGenerating': 'G?n?ration de la traduction',
  'translationStageReadability': 'Am?lioration de la lisibilit?',
  'translationStageReady': 'Traduction pr?te',
  'translationPreviewTitle': 'Aper?u',
  'translationPreviewHeader': 'V?rifiez la traduction',
  'translationPreviewSubtitle': 'Recherchez, changez de mode et exportez.',
  'translationPreviewSearchHint': 'Rechercher dans les sous-titres',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Traduit',
  'previewModeBilingual': 'Bilingue',
  'previewNotReadyTitle': 'Aper?u non disponible',
  'previewNotReadyMessage': 'La traduction est termin?e mais l?aper?u n?est pas pr?t.',
  'previewNoMatchesTitle': 'Aucune ligne trouv?e',
  'previewNoMatchesMessage': 'Essayez un autre terme ou effacez le filtre.',
  'previewFailedTitle': '?chec du chargement',
  'exportingLabel': 'Export en cours...',
  'exportSubtitleLabel': 'Exporter les sous-titres',
  'exportedSnack': '{fileName} export? vers {path}',
  'exportFailedSnack': '?chec de l?export : {error}',
  'metadataFormat': 'Format',
  'metadataLines': 'Lignes',
  'metadataLanguages': 'Langues',
  'metadataEstimatedDuration': 'Dur?e estim?e',
  'subtitleSourcesTitle': 'Sources de sous-titres anglais',
  'subtitleSourcesSubtitle': 'Choisissez une source pour {title}{target}.',
  'subtitleSourcesFailedTitle': 'Impossible de charger les sources',
  'seriesSeasonsTitle': 'Choisir une saison',
  'seriesSeasonsSubtitle': 'Choisissez une saison de {title} pour voir les ?pisodes.',
  'seriesSeasonLabel': 'Saison {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} ?pisodes{year}',
  'seriesEpisodesTitle': 'Saison {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} ?pisodes{year}',
  'seriesEpisodeLabel': '?pisode {episodeNumber}',
  'seriesEpisodeMeta': 'Environ {runtime} min',
  'historyTitle': 'Historique',
  'historySubtitle': 'Rouvrez vos traductions r?centes.',
  'historyEmptyTitle': 'Historique vide',
  'historyEmptyMessage': 'Vos traductions appara?tront ici apr?s un flux complet.',
  'historyFailedTitle': '?chec du chargement',
  'homeRecentJobsTitle': 'T?ches r?centes',
  'homeRecentJobsSubtitle': 'Rouvrez vos derni?res sessions.',
  'homeNoRecentTitle': 'Aucune t?che r?cente',
  'homeNoRecentMessage': 'Lancez une recherche ou un import.',
  'homeFailedRecentTitle': '?chec du chargement',
  'homeTrustTitle': 'Pourquoi on lui fait confiance',
  'homeTrustSubtitle': 'Maquette aujourd?hui, produit demain.',
  'homeFutureTitle': 'D?p?ts pr?ts pour l?avenir',
  'homeFutureSubtitle': 'Interfaces isol?es du backend.',
  'homePreviewTitle': 'Flux centr? sur l?aper?u',
  'homePreviewSubtitle': 'V?rifiez avant d?exporter.',
  'homeStatesTitle': '?tats complets',
  'homeStatesSubtitle': 'Chargement, vide, retry, etc.',
  'navHome': 'Accueil',
  'navHistory': 'Historique',
  'navSettings': 'R?glages',
  'heroTitle': 'Traduisez plus vite',
  'heroSubtitle': 'Cherchez, choisissez, exportez en minutes.',
  'heroBadge': 'Flux premium',
  'heroHeadline': 'Qualit? studio',
  'heroBody': 'Choisissez recherche ou import, puis exportez.',
  'heroSearchCta': 'Rechercher film / s?rie',
  'heroUploadCta': 'Importer des sous-titres',
  'heroStatPathsTitle': '2 chemins',
  'heroStatPathsValue': 'Recherche ou import',
  'heroStatLanguagesTitle': '10 langues',
  'heroStatLanguagesValue': 'Pr?t pour l?aper?u',
  'heroStatMockTitle': 'APIs mock',
  'heroStatMockValue': 'Pr?t pour backend',
  'settingsTitle': 'R?glages',
  'settingsSubtitle': 'Langues, apparence, infos.',
  'settingsLanguageLabel': 'Langue cible pr?f?r?e',
  'settingsThemeLabel': 'Apparence',
  'themeSystem': 'Syst?me',
  'themeDark': 'Sombre',
  'themeLight': 'Clair',
  'settingsPremiumTitle': 'Premium (d?mo)',
  'settingsPremiumSubtitle': 'Abonnements plus tard.',
  'settingsSupportTitle': 'Support (d?mo)',
  'settingsSupportSubtitle': 'Page d?aide d?mo',
  'settingsPrivacyTitle': 'Politique de confidentialit?',
  'settingsPrivacySubtitle': 'Contenu d?mo',
  'settingsTermsTitle': 'Conditions d?utilisation',
  'settingsTermsSubtitle': 'Contenu d?mo',
  'settingsMaintenanceTitle': 'Maintenance',
  'settingsMaintenanceSubtitle': 'Effacer l?historique local.',
  'settingsHistoryClearedSnack': 'Historique effac?',
  'settingsAboutTitle': '? propos de SubFlix',
  'settingsVersion': 'Version {version}',
  'settingsClearCache': 'Vider le cache',
  'settingsCacheCleared': 'Cache vid?',
  'settingsFailedTitle': 'Chargement des r?glages ?chou?',
  'legalPlaceholderBody': 'Page d?mo.',
  'legalTitlePrivacy': 'Confidentialit?',
  'legalTitleTerms': 'Conditions',
  'legalTitleSupport': 'Support',
  'legalTitleAbout': '? propos',
  'legalBodyPrivacy': 'Seules des pr?f?rences mock sont stock?es.',
  'legalBodyTerms': 'Version mock pour tester les flux.',
  'legalBodySupport': 'Support d?mo pour l?instant.',
  'legalBodyAbout': 'Client Flutter premium pour la traduction.',
  'routeMissingSubtitleSourcesTitle': 'Sources',
  'routeMissingSubtitleSourcesMessage': 'Impossible d?identifier le titre. Recommencez.',
  'routeMissingSeriesSeasonsTitle': 'Saisons',
  'routeMissingSeriesSeasonsMessage': 'Impossible d?identifier la s?rie. Recommencez.',
  'routeMissingSeasonEpisodesTitle': '?pisodes',
  'routeMissingSeasonEpisodesMessage': 'Impossible d?identifier la saison. Recommencez.',
  'routeMissingTranslationSetupTitle': 'Configuration',
  'routeMissingTranslationSetupMessage': 'Source requise.',
  'routeMissingTranslationProgressTitle': 'Progression',
  'routeMissingTranslationProgressMessage': 'Aucune demande fournie.',
  'searchResultPopularity': 'Popularit? {score}',
  'subtitleSourceLines': '{lineCount} lignes',
  'subtitleSourceDownloads': '{downloads} t?l?chargements',
  'subtitleSourceRating': 'Note {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Film',
  'mediaTypeSeries': 'S?rie',
  'jobReuseTranslation': 'R?utiliser la traduction',
  'jobReuseSubtitle': 'R?utiliser les sous-titres',
  'jobConfidence': 'Confiance : {level}',
  'jobOpenPreview': 'Ouvrir l?aper?u',
  'onboardingPage1Title': 'Trouvez un film ou une s?rie.',
  'onboardingPage1Eyebrow': 'Rechercher et r?cup?rer',
  'onboardingPage1Description': 'Recherchez, v?rifiez les sources et lancez.',
  'onboardingPage1Highlight1': 'Catalogue mock fiable',
  'onboardingPage1Highlight2': 'Labels qualit? et badges',
  'onboardingPage1Highlight3': 'Pr?t pour un vrai backend',
  'onboardingPage2Title': 'Importez des fichiers `.srt` ou `.vtt`.',
  'onboardingPage2Eyebrow': 'Votre fichier',
  'onboardingPage2Description': 'Importez et suivez le m?me flux.',
  'onboardingPage2Highlight1': 'Validation locale et retry',
  'onboardingPage2Highlight2': 'Configuration coh?rente',
  'onboardingPage2Highlight3': 'Aper?u avant export',
  'onboardingPage3Title': 'Choisissez la langue et exportez.',
  'onboardingPage3Eyebrow': 'Traduire et exporter',
  'onboardingPage3Description': 'Basculez entre les modes et exportez.',
  'onboardingPage3Highlight1': 'Contr?les d?aper?u rapides',
  'onboardingPage3Highlight2': 'Historique ? port?e de main',
  'onboardingPage3Highlight3': 'Design premium',
  'onboardingStart': 'D?marrer',
  'onboardingNext': 'Suivant',
  'onboardingSkip': 'Passer',
  'onboardingContinue': 'Continuer',
  'onboardingEnterApp': 'Entrer dans SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'Traduction de sous-titres IA',
  'splashPreparing': 'Pr?paration du studio',
  'brandSubtitleCompact': 'Intelligence des sous-titres',
  'brandSubtitleFull': 'Studio IA de traduction',
  'comingSoonTitle': 'Bient?t disponible',
  'comingSoonMessage': 'Cette page est en pr?paration.',
};
