const Map<String, String> kStringsJa = <String, String>{
  'appTitle': "SubFlix",
  'searchTitles': "タイトルを検索",
  'searchMovieOrSeriesTitle': "映画・シリーズを検索",
  'searchMovieOrSeriesSubtitle': "タイトルを見つけて字幕ソースを確認し、数回のタップで翻訳ジョブを開始できます。",
  'searchHintText': "Dune、Breaking Bad、Severance などを検索...",
  'searchMockTitle': "モックカタログ内を検索",
  'searchMockMessage':
      "Inception、Dune、Breaking Bad、Severance、The Last of Us などを試して、字幕ソースの流れを確認してください。",
  'searchFailedTitle': "検索に失敗しました",
  'noTitlesMatchedTitle': "一致する結果がありません",
  'noTitlesMatchedMessage':
      "このタイトルはモックカタログで見つかりませんでした。より広い条件で検索するか、候補のタイトルを試してください。",
  'searchTrendingTitle': "人気の検索",
  'searchLoadingLabel': "検索中...",
  'searchFoundResults': "\"{query}\" の結果が {count} 件見つかりました",
  'searchNoResultsFor': "\"{query}\" の結果は見つかりませんでした",
  'searchTryDifferentKeywords': "別のキーワードで検索してみてください。",
  'retry': "再試行",
  'retryTranslation': "翻訳を再試行",
  'uploadSubtitleTitle': "字幕をアップロード",
  'uploadIntroTitle': "自分の字幕ファイルを使う",
  'uploadIntroSubtitle':
      "英語の `.srt` または `.vtt` ファイルを取り込み、バックエンドで検証・解析したあと、翻訳設定へ進みます。",
  'uploadChooseFile': "字幕ファイルを選択",
  'uploadSupportedFormatsTitle': "対応形式",
  'uploadSupportedFormatsSubtitle': "英語の `.srt` / `.vtt` 字幕ファイル",
  'uploadOpeningPicker': "ピッカーを開いています...",
  'uploadChooseFileShort': "ファイルを選択",
  'uploadPickSubtitle': "字幕ファイルを選ぶ",
  'uploadPickedFile': "字幕ファイルを選択しました",
  'uploadUseDemoFile': "デモファイルを使う",
  'uploadFailedTitle': "ファイルの取り込みに失敗しました",
  'uploadFailedMessage': "この字幕ファイルは読み込めませんでした。別のファイルか、より小さい書き出しを試してください。",
  'uploadFailedFallback': "別の字幕ファイルをお試しください。",
  'tryAgain': "もう一度試す",
  'uploadMetadataTitle': "字幕の詳細",
  'uploadReadyTitle': "翻訳の準備ができました",
  'uploadLineCount': "{lineCount} 行",
  'uploadEnglishSource': "英語ソース",
  'uploadContinueSetup': "翻訳設定へ進む",
  'translateSetupTitle': "翻訳設定",
  'translateSetupSubtitle': "対象言語を選び、字幕ソースを確認してから、バックエンド翻訳ジョブを開始します。",
  'translateSetupSourceTitle': "元の字幕",
  'translateSetupLanguageTitle': "翻訳先",
  'translateSetupOptionsTitle': "オプション",
  'translateSetupSelectLanguage': "言語を選択",
  'translateSetupReadyTitle': "AI翻訳の準備完了",
  'translateSetupReadyBody': "この字幕は、タイミングと cue 構造を保ったまま {language} に変換されます。",
  'translateSetupPreserveTiming': "タイミングを保持",
  'translateSetupPreserveTimingBody': "元ファイルに合わせて字幕のタイミングを維持します。",
  'translateSetupAutoDetect': "形式を自動検出",
  'translateSetupAutoDetectBody': "字幕の出力構造を自動で最適化します。",
  'subtitleSourceFormatLabel': "{format} 字幕ソース",
  'targetLanguage': "対象言語",
  'startTranslation': "翻訳を開始",
  'translationProgressTitle': "翻訳の進行状況",
  'translationProgressHeadline': "AI字幕翻訳を実行中です",
  'translationFailedTitle': "翻訳を完了できませんでした",
  'translationFailedMessage': "問題が発生しました。",
  'translationStageQueued': "翻訳待ちキューに入りました",
  'translationStageIdle': "翻訳リクエストを待機中",
  'translationStagePreparing': "字幕パッケージを準備中",
  'translationStageAligning': "タイムスタンプとシーン文脈を調整中",
  'translationStageGenerating': "字幕翻訳を生成中",
  'translationStageReadability': "読みやすさ調整を適用中",
  'translationStageReady': "翻訳の準備完了",
  'translationResultCompleteTitle': "翻訳が完了しました",
  'translationResultCompleteSubtitle': "字幕はプレビューまたはダウンロードの準備ができています。",
  'translationResultDetailsTitle': "翻訳の詳細",
  'translationResultMediaLabel': "作品タイトル",
  'translationResultSourceLabel': "元の言語",
  'translationResultTargetLabel': "翻訳先の言語",
  'translationResultMethodAi': "AIで翻訳済み",
  'translationResultMetricsTitle': "品質指標",
  'translationResultConfidenceLabel': "翻訳の信頼度",
  'translationResultTimingLabel': "タイミング精度",
  'translationResultTimingPreserved': "タイミング保持",
  'translationResultProcessedIn': "{duration} で処理完了",
  'translationResultWarning': "一部の専門用語は、文脈確認のために人の軽い見直しがあるとより安心です。",
  'translationResultPreviewCta': "字幕をプレビュー",
  'translationResultDownloadCta': "字幕をダウンロード",
  'translationResultHomeCta': "ホームに戻る",
  'translationPreviewTitle': "翻訳プレビュー",
  'translationPreviewHeader': "翻訳された字幕を確認",
  'translationPreviewSubtitle': "cue 内を検索し、表示モードを切り替え、納得できたら書き出してください。",
  'translationPreviewSearchHint': "字幕行を検索",
  'previewModeOriginal': "原文",
  'previewModeTranslated': "翻訳文",
  'previewModeBilingual': "バイリンガル",
  'previewNotReadyTitle': "プレビュー用 cue はまだ利用できません",
  'previewNotReadyMessage':
      "翻訳は完了しましたが、バックエンドからプレビュー cue がまだ返ってきていません。少し待って再読み込みしてください。",
  'previewNoMatchesTitle': "一致する字幕行がありません",
  'previewNoMatchesMessage': "別の検索語を試すか、フィルターを解除して全文を確認してください。",
  'previewFailedTitle': "プレビューの読み込みに失敗しました",
  'exportingLabel': "書き出し中...",
  'exportSubtitleLabel': "翻訳済み字幕を書き出す",
  'exportedSnack': "{fileName} を {path} に書き出しました",
  'exportFailedSnack': "書き出しに失敗しました: {error}",
  'metadataFormat': "形式",
  'metadataLines': "行数",
  'metadataLanguages': "言語",
  'metadataEstimatedDuration': "推定時間",
  'subtitleSourcesTitle': "英語字幕ソース",
  'subtitleSourcesSubtitle': "{title}{target} の字幕ソースを選び、次のステップで対象言語を選択してください。",
  'subtitleSourcesBannerTitle': "AI翻訳が利用できます",
  'subtitleSourcesBannerMessage': "字幕ソースを選択すると、字幕タイミングに最適化された翻訳設定へ進みます。",
  'subtitleSourcesFailedTitle': "字幕ソースを読み込めませんでした",
  'seriesSeasonsTitle': "シーズンを選択",
  'seriesSeasonsSubtitle': "{title} のシーズンを選んで、利用可能なエピソードを確認してください。",
  'seriesSeasonLabel': "シーズン {seasonNumber}",
  'seriesSeasonMeta': "{episodeCount} 話{year}",
  'seriesEpisodesTitle': "シーズン {seasonNumber}",
  'seriesEpisodesSubtitle': "{episodeCount} 話{year}",
  'seriesEpisodeLabel': "エピソード {episodeNumber}",
  'seriesEpisodeMeta': "約 {runtime} 分",
  'historyTitle': "翻訳履歴",
  'historySubtitle': "以前の字幕ジョブを開き直し、再度プレビューしたり、あとで書き出したりできます。",
  'historyEmptyTitle': "履歴は空です",
  'historyEmptyMessage': "検索またはアップロードの流れを完了すると、翻訳済み字幕ジョブがここに表示されます。",
  'historyFailedTitle': "履歴を読み込めませんでした",
  'historyCountLabel': "{count} 件の翻訳",
  'historyFilterAll': "すべて",
  'historyFilterMovies': "映画",
  'historyFilterSeries': "シリーズ",
  'historyFilterCompleted': "完了",
  'historyFilterAiTranslated': "AI翻訳",
  'historyFilterFailed': "失敗",
  'historyFilterReused': "再利用",
  'historyFailedItemMessage': "翻訳に失敗しました。タップしてやり直してください。",
  'homeRecentJobsTitle': "最近のジョブ",
  'homeRecentJobsSubtitle': "最初からやり直さずに、最新の字幕セッションを開き直せます。",
  'homeNoRecentTitle': "最近のジョブはまだありません",
  'homeNoRecentMessage': "映画検索を始めるか字幕ファイルをアップロードすると、最近の翻訳がここに表示されます。",
  'homeFailedRecentTitle': "最近のジョブを読み込めませんでした",
  'homeWelcomeTitle': "おかえりなさい",
  'homeWelcomeSubtitle': "字幕を見つけて翻訳",
  'homeSearchPlaceholder': "映画やシリーズを検索...",
  'homeQuickSearch': "検索",
  'homeQuickHistory': "履歴",
  'homeQuickUpload': "アップロード",
  'homeViewAll': "すべて見る",
  'homeTrendingNow': "今のトレンド",
  'homeTrustTitle': "チームに信頼される理由",
  'homeTrustSubtitle': "今はモックでも、実運用できる製品のように設計されています。",
  'homeFutureTitle': "将来対応のリポジトリ",
  'homeFutureSubtitle': "差し替え可能なモックリポジトリにより、UIコードはバックエンド変更の影響を受けにくくなります。",
  'homePreviewTitle': "プレビュー重視の翻訳フロー",
  'homePreviewSubtitle': "書き出し前に、原文・翻訳・バイリンガル表示で結果を確認できます。",
  'homeStatesTitle': "丁寧な状態設計込み",
  'homeStatesSubtitle': "読み込み、空状態、再試行、検証、モックのオフライン状態まで初日からUXに含まれています。",
  'navHome': "ホーム",
  'navHistory': "履歴",
  'navSettings': "設定",
  'heroTitle': "字幕をもっと速く翻訳",
  'heroSubtitle': "映画・シリーズのカタログを検索し、ソースを選び、数分で洗練された翻訳を出力できます。",
  'heroBadge': "プレミアム字幕ワークフロー",
  'heroHeadline': "スタジオ品質のフローで映画・シリーズ字幕を翻訳。",
  'heroBody': "検索可能なタイトルカタログか直接ファイルアップロードを選び、数分で洗練された字幕をプレビュー・書き出しできます。",
  'heroSearchCta': "映画 / シリーズを検索",
  'heroUploadCta': "字幕をアップロード",
  'heroStatPathsTitle': "2つの経路",
  'heroStatPathsValue': "検索またはアップロード",
  'heroStatLanguagesTitle': "10言語",
  'heroStatLanguagesValue': "プレビュー可能",
  'heroStatMockTitle': "モックAPI",
  'heroStatMockValue': "バックエンド接続準備済み",
  'settingsTitle': "設定",
  'settingsSubtitle': "好みを管理",
  'settingsProfileName': "SubFlix ユーザー",
  'settingsProfileTier': "プレミアム会員",
  'settingsLanguageLabel': "優先する翻訳先言語",
  'settingsThemeLabel': "外観",
  'themeSystem': "システム",
  'themeDark': "ダーク",
  'themeLight': "ライト",
  'settingsPremiumTitle': "プレミアム用プレースホルダー",
  'settingsPremiumSubtitle': "今後、購読・請求・クラウドプロジェクト同期をここに接続できます。",
  'settingsNotificationsTitle': "通知",
  'settingsNotificationsSubtitle': "通知設定を管理",
  'settingsHelpCenterTitle': "ヘルプセンター",
  'settingsContactTitle': "お問い合わせ",
  'settingsSupportTitle': "サポート用プレースホルダー",
  'settingsSupportSubtitle': "モックのヘルプ・問い合わせページ",
  'settingsPrivacyTitle': "プライバシーポリシー",
  'settingsPrivacySubtitle': "モックのプライバシー内容",
  'settingsTermsTitle': "利用規約",
  'settingsTermsSubtitle': "モックの規約内容",
  'settingsMaintenanceTitle': "メンテナンス",
  'settingsMaintenanceSubtitle': "この端末のバックエンド管理翻訳ジョブを消去し、履歴を空の状態から始めます。",
  'settingsHistoryClearedSnack': "この端末の翻訳履歴を消去しました",
  'settingsAboutTitle': "SubFlix について",
  'settingsVersion': "バージョン {version}",
  'settingsClearCache': "キャッシュを消去",
  'settingsCacheCleared': "キャッシュを消去しました",
  'settingsFailedTitle': "設定を読み込めませんでした",
  'legalPlaceholderBody': "このページはデモアプリ内のプレースホルダーです。本番用の法的コンテンツに差し替えてください。",
  'legalTitlePrivacy': "プライバシーポリシー",
  'legalTitleTerms': "利用規約",
  'legalTitleSupport': "サポート",
  'legalTitleAbout': "SubFlix について",
  'legalBodyPrivacy':
      "SubFlix は現在、モックの設定と翻訳履歴のみをローカル保存しています。将来的なバックエンド連携により、認証付き保存、監査ログ、サーバー管理の保持ポリシーへ置き換えられます。",
  'legalBodyTerms':
      "このモックビルドは、製品フロー、UI状態、アーキテクチャ境界を検証するためのものです。将来 NestJS と Postgres の本番バックエンドが接続されれば、実際の利用規約やデータ処理文言を追加できます。",
  'legalBodySupport':
      "サポートは現在プレースホルダーです。本番では、アプリ構造を変えずにメール、問題報告、プレミアム会員向け支援へ接続できます。",
  'legalBodyAbout':
      "SubFlix は AI 字幕翻訳向けのプレミアム志向 Flutter クライアントです。このビルドでは、実際のバックエンド接続前に UI とアーキテクチャを育てるため、モックリポジトリ、人工的な遅延、ローカル保存を使っています。",
  'routeMissingSubtitleSourcesTitle': "字幕ソース",
  'routeMissingSubtitleSourcesMessage':
      "どのタイトルの字幕ソースを読み込むべきか判断できませんでした。検索からやり直してください。",
  'routeMissingSeriesSeasonsTitle': "シリーズのシーズン",
  'routeMissingSeriesSeasonsMessage': "どのシリーズを読み込むべきか判断できませんでした。検索からやり直してください。",
  'routeMissingSeasonEpisodesTitle': "シーズンのエピソード",
  'routeMissingSeasonEpisodesMessage':
      "どのシーズンを読み込むべきか判断できませんでした。検索からやり直してください。",
  'routeMissingTranslationSetupTitle': "翻訳設定",
  'routeMissingTranslationSetupMessage': "翻訳設定画面を開く前に字幕ソースが必要です。",
  'routeMissingTranslationProgressTitle': "翻訳の進行状況",
  'routeMissingTranslationProgressMessage':
      "翻訳リクエストがありません。検索またはアップロードから新しい翻訳を始めてください。",
  'searchResultPopularity': "人気度 {score}",
  'subtitleSourceLines': "{lineCount} 行",
  'subtitleSourceDownloads': "{downloads} ダウンロード",
  'subtitleSourceRating': "評価 {rating}",
  'subtitleSourceHiLabel': "HI / SDH",
  'mediaTypeMovie': "映画",
  'mediaTypeSeries': "シリーズ",
  'jobReuseTranslation': "翻訳を再利用",
  'jobReuseSubtitle': "字幕を再利用",
  'jobConfidence': "信頼度: {level}",
  'jobOpenPreview': "プレビューを開く",
  'onboardingPage1Title': "映画やシリーズを探して、すぐ翻訳できる字幕を取得。",
  'onboardingPage1Eyebrow': "検索して取得",
  'onboardingPage1Description':
      "タイトルを検索し、利用可能な英語字幕ソースを確認して、すぐに使える翻訳フローを開始できます。",
  'onboardingPage1Highlight1': "開発しやすい決定論的モックカタログ",
  'onboardingPage1Highlight2': "字幕ソースの品質ラベルと形式バッジ",
  'onboardingPage1Highlight3': "後から実バックエンドへ差し替え可能",
  'onboardingPage2Title': "すでに台本があるなら `.srt` / `.vtt` をアップロード。",
  'onboardingPage2Eyebrow': "自分のファイルを使う",
  'onboardingPage2Description':
      "字幕ファイルを取り込み、形式を検証し、同じ洗練された翻訳パイプラインをアプリ内で実行できます。",
  'onboardingPage2Highlight1': "ローカル検証と丁寧な再試行状態",
  'onboardingPage2Highlight2': "検索とアップロードで一貫した設定",
  'onboardingPage2Highlight3': "不透明さをなくすため、書き出し前に確認",
  'onboardingPage3Title': "対象言語を選び、字幕を確認して、すぐ書き出し。",
  'onboardingPage3Eyebrow': "翻訳して書き出す",
  'onboardingPage3Description':
      "原文・翻訳・バイリンガル表示を切り替え、履歴を見返し、仕上がりに納得したらきれいな字幕ファイルを書き出せます。",
  'onboardingPage3Highlight1': "メタデータと検索付きの高速プレビュー操作",
  'onboardingPage3Highlight2': "履歴から以前のジョブにすぐ戻れる",
  'onboardingPage3Highlight3': "デモではなく、プレミアムなメディアツールのような設計",
  'onboardingStart': "翻訳を始める",
  'onboardingNext': "次へ",
  'onboardingSkip': "スキップ",
  'onboardingContinue': "続ける",
  'onboardingEnterApp': "SubFlix に入る",
  'splashHeadline': "SubFlix",
  'splashSubtitle': "AIによる字幕翻訳",
  'splashPreparing': "あなたの字幕スタジオを準備中",
  'brandSubtitleCompact': "字幕インテリジェンス",
  'brandSubtitleFull': "AI字幕翻訳スタジオ",
  'comingSoonTitle': "近日公開",
  'comingSoonMessage': "この画面はまだ準備中です。",
};
