const Map<String, String> kStringsHi = <String, String>{
  'appTitle': "SubFlix",
  'searchTitles': "शीर्षक खोजें",
  'searchMovieOrSeriesTitle': "फ़िल्म या सीरीज़ खोजें",
  'searchMovieOrSeriesSubtitle':
      "कोई शीर्षक ढूँढें, सबटाइटल स्रोत देखें और कुछ टैप में अनुवाद शुरू करें।",
  'searchHintText': "Dune, Breaking Bad, Severance खोजें...",
  'searchMockTitle': "मॉक कैटलॉग में कुछ भी खोजें",
  'searchMockMessage':
      "सबटाइटल स्रोतों का फ़्लो देखने के लिए Inception, Dune, Breaking Bad, Severance या The Last of Us जैसे शीर्षक आज़माएँ।",
  'searchFailedTitle': "खोज असफल रही",
  'noTitlesMatchedTitle': "कोई मिलान नहीं मिला",
  'noTitlesMatchedMessage':
      "हमें यह शीर्षक मॉक कैटलॉग में नहीं मिला। थोड़ा व्यापक खोजें या सुझाए गए शीर्षकों में से कोई चुनें।",
  'searchTrendingTitle': "ट्रेंडिंग खोजें",
  'searchLoadingLabel': "खोज जारी है...",
  'searchFoundResults': "\"{query}\" के लिए {count} परिणाम मिले",
  'searchNoResultsFor': "\"{query}\" के लिए कोई परिणाम नहीं मिला",
  'searchTryDifferentKeywords': "कुछ अलग कीवर्ड्स आज़माएँ।",
  'retry': "फिर से प्रयास करें",
  'retryTranslation': "अनुवाद फिर से करें",
  'uploadSubtitleTitle': "सबटाइटल अपलोड करें",
  'uploadIntroTitle': "अपनी सबटाइटल फ़ाइल इस्तेमाल करें",
  'uploadIntroSubtitle':
      "एक अंग्रेज़ी `.srt` या `.vtt` फ़ाइल इम्पोर्ट करें, बैकएंड से उसे वैलिडेट और पार्स करवाएँ, फिर अनुवाद सेटअप पर आगे बढ़ें।",
  'uploadChooseFile': "सबटाइटल फ़ाइल चुनें",
  'uploadSupportedFormatsTitle': "समर्थित फ़ॉर्मैट",
  'uploadSupportedFormatsSubtitle':
      "अंग्रेज़ी `.srt` और `.vtt` सबटाइटल फ़ाइलें",
  'uploadOpeningPicker': "फ़ाइल पिकर खुल रहा है...",
  'uploadChooseFileShort': "फ़ाइल चुनें",
  'uploadPickSubtitle': "सबटाइटल फ़ाइल चुनें",
  'uploadPickedFile': "सबटाइटल फ़ाइल चुनी गई",
  'uploadUseDemoFile': "डेमो फ़ाइल इस्तेमाल करें",
  'uploadFailedTitle': "फ़ाइल इम्पोर्ट असफल रहा",
  'uploadFailedMessage':
      "हम इस सबटाइटल फ़ाइल को पढ़ नहीं सके। कोई दूसरी फ़ाइल या छोटा एक्सपोर्ट आज़माएँ।",
  'uploadFailedFallback': "कृपया कोई दूसरी सबटाइटल फ़ाइल आज़माएँ।",
  'tryAgain': "फिर से कोशिश करें",
  'uploadMetadataTitle': "सबटाइटल विवरण",
  'uploadReadyTitle': "अनुवाद के लिए तैयार",
  'uploadLineCount': "{lineCount} पंक्तियाँ",
  'uploadEnglishSource': "अंग्रेज़ी स्रोत",
  'uploadContinueSetup': "अनुवाद सेटअप पर आगे बढ़ें",
  'translateSetupTitle': "अनुवाद सेटअप",
  'translateSetupSubtitle':
      "लक्षित भाषा चुनें, सबटाइटल स्रोत देखें और बैकएंड अनुवाद जॉब शुरू करें।",
  'translateSetupSourceTitle': "स्रोत सबटाइटल",
  'translateSetupLanguageTitle': "किस भाषा में",
  'translateSetupOptionsTitle': "विकल्प",
  'translateSetupSelectLanguage': "भाषा चुनें",
  'translateSetupReadyTitle': "AI अनुवाद तैयार है",
  'translateSetupReadyBody':
      "हमारा अनुवाद फ़्लो इस सबटाइटल को {language} में बदलेगा, साथ ही टाइमिंग और cue संरचना को साफ़-सुथरा बनाए रखेगा।",
  'translateSetupPreserveTiming': "टाइमिंग सुरक्षित रखें",
  'translateSetupPreserveTimingBody':
      "मूल सबटाइटल टाइमिंग को स्रोत फ़ाइल के साथ मिलाकर रखें।",
  'translateSetupAutoDetect': "फ़ॉर्मैट स्वतः पहचानें",
  'translateSetupAutoDetectBody': "सही सबटाइटल आउटपुट संरचना अपने आप चुनें।",
  'subtitleSourceFormatLabel': "{format} सबटाइटल स्रोत",
  'targetLanguage': "लक्षित भाषा",
  'startTranslation': "अनुवाद शुरू करें",
  'translationProgressTitle': "अनुवाद प्रगति",
  'translationProgressHeadline': "AI सबटाइटल अनुवाद जारी है",
  'translationFailedTitle': "अनुवाद पूरा नहीं हो सका",
  'translationFailedMessage': "कुछ गड़बड़ हो गई।",
  'translationStageQueued': "अनुवाद कतार में है",
  'translationStageIdle': "अनुवाद अनुरोध की प्रतीक्षा में",
  'translationStagePreparing': "सबटाइटल पैकेज तैयार किया जा रहा है",
  'translationStageAligning': "टाइमस्टैम्प और सीन संदर्भ मिलाए जा रहे हैं",
  'translationStageGenerating': "सबटाइटल अनुवाद बनाया जा रहा है",
  'translationStageReadability': "पढ़ने-लायक बनाने की जाँच लागू की जा रही है",
  'translationStageReady': "अनुवाद तैयार है",
  'translationResultCompleteTitle': "अनुवाद पूरा हुआ",
  'translationResultCompleteSubtitle':
      "आपका सबटाइटल अब प्रीव्यू या डाउनलोड के लिए तैयार है।",
  'translationResultDetailsTitle': "अनुवाद विवरण",
  'translationResultMediaLabel': "मीडिया शीर्षक",
  'translationResultSourceLabel': "स्रोत भाषा",
  'translationResultTargetLabel': "लक्षित भाषा",
  'translationResultMethodAi': "AI से अनुवादित",
  'translationResultMetricsTitle': "गुणवत्ता मेट्रिक्स",
  'translationResultConfidenceLabel': "अनुवाद विश्वसनीयता",
  'translationResultTimingLabel': "टाइमिंग सटीकता",
  'translationResultTimingPreserved': "टाइमिंग सुरक्षित रखी गई",
  'translationResultProcessedIn': "{duration} में प्रोसेस हुआ",
  'translationResultWarning':
      "कुछ तकनीकी शब्दों के लिए संदर्भ के हिसाब से तेज़ मानवीय समीक्षा अभी भी काम आ सकती है।",
  'translationResultPreviewCta': "सबटाइटल प्रीव्यू",
  'translationResultDownloadCta': "सबटाइटल डाउनलोड करें",
  'translationResultHomeCta': "होम पर वापस जाएँ",
  'translationPreviewTitle': "अनुवाद प्रीव्यू",
  'translationPreviewHeader': "अनुवादित सबटाइटल देखें",
  'translationPreviewSubtitle':
      "cues के अंदर खोजें, प्रीव्यू मोड बदलें और जब परिणाम सही लगे तब एक्सपोर्ट करें।",
  'translationPreviewSearchHint': "सबटाइटल पंक्तियाँ खोजें",
  'previewModeOriginal': "मूल",
  'previewModeTranslated': "अनुवादित",
  'previewModeBilingual': "द्विभाषी",
  'previewNotReadyTitle': "प्रीव्यू cues अभी उपलब्ध नहीं हैं",
  'previewNotReadyMessage':
      "अनुवाद पूरा हो गया, लेकिन बैकएंड ने अभी तक प्रीव्यू cues नहीं भेजे। एक क्षण बाद यह स्क्रीन फिर से लोड करें।",
  'previewNoMatchesTitle': "कोई सबटाइटल पंक्ति मेल नहीं खाई",
  'previewNoMatchesMessage':
      "कोई दूसरा खोज शब्द आज़माएँ या पूरा अनुवाद देखने के लिए फ़िल्टर हटाएँ।",
  'previewFailedTitle': "प्रीव्यू लोड नहीं हो सका",
  'exportingLabel': "एक्सपोर्ट किया जा रहा है...",
  'exportSubtitleLabel': "अनुवादित सबटाइटल एक्सपोर्ट करें",
  'exportedSnack': "{fileName} को {path} पर एक्सपोर्ट किया गया",
  'exportFailedSnack': "एक्सपोर्ट असफल रहा: {error}",
  'metadataFormat': "फ़ॉर्मैट",
  'metadataLines': "पंक्तियाँ",
  'metadataLanguages': "भाषाएँ",
  'metadataEstimatedDuration': "अनुमानित अवधि",
  'subtitleSourcesTitle': "अंग्रेज़ी सबटाइटल स्रोत",
  'subtitleSourcesSubtitle':
      "{title}{target} के लिए एक सबटाइटल स्रोत चुनें, फिर अगले चरण में लक्षित भाषा चुनें।",
  'subtitleSourcesBannerTitle': "AI अनुवाद उपलब्ध है",
  'subtitleSourcesBannerMessage':
      "एक सबटाइटल स्रोत चुनें और सबटाइटल टाइमिंग के लिए अनुकूलित, polished अनुवाद सेटअप पर आगे बढ़ें।",
  'subtitleSourcesFailedTitle': "सबटाइटल स्रोत लोड नहीं हो सके",
  'seriesSeasonsTitle': "एक सीज़न चुनें",
  'seriesSeasonsSubtitle':
      "उपलब्ध एपिसोड देखने के लिए {title} का एक सीज़न चुनें।",
  'seriesSeasonLabel': "सीज़न {seasonNumber}",
  'seriesSeasonMeta': "{episodeCount} एपिसोड{year}",
  'seriesEpisodesTitle': "सीज़न {seasonNumber}",
  'seriesEpisodesSubtitle': "{episodeCount} एपिसोड{year}",
  'seriesEpisodeLabel': "एपिसोड {episodeNumber}",
  'seriesEpisodeMeta': "लगभग {runtime} मिनट",
  'historyTitle': "अनुवाद इतिहास",
  'historySubtitle':
      "पुराने सबटाइटल जॉब फिर से खोलें, प्रीव्यू दोबारा देखें या बाद में एक्सपोर्ट करें।",
  'historyEmptyTitle': "इतिहास खाली है",
  'historyEmptyMessage':
      "जैसे ही आप खोज या अपलोड फ़्लो पूरा करेंगे, आपके अनुवादित सबटाइटल जॉब यहाँ दिखेंगे।",
  'historyFailedTitle': "इतिहास लोड नहीं हो सका",
  'historyCountLabel': "{count} अनुवाद",
  'historyFilterAll': "सभी",
  'historyFilterMovies': "फ़िल्में",
  'historyFilterSeries': "सीरीज़",
  'historyFilterCompleted': "पूर्ण",
  'historyFilterAiTranslated': "AI से अनुवादित",
  'historyFilterFailed': "असफल",
  'historyFilterReused': "दोबारा इस्तेमाल",
  'historyFailedItemMessage':
      "अनुवाद असफल रहा। फिर से शुरू करने के लिए टैप करें।",
  'homeRecentJobsTitle': "हाल के जॉब",
  'homeRecentJobsSubtitle':
      "शुरू से शुरू किए बिना अपनी ताज़ा सबटाइटल सेशन फिर खोलें।",
  'homeNoRecentTitle': "अभी कोई हालिया जॉब नहीं",
  'homeNoRecentMessage':
      "किसी फ़िल्म की खोज से शुरू करें या सबटाइटल फ़ाइल अपलोड करें, आपके हाल के अनुवाद यहाँ दिखेंगे।",
  'homeFailedRecentTitle': "हाल के जॉब लोड नहीं हो सके",
  'homeWelcomeTitle': "फिर से स्वागत है",
  'homeWelcomeSubtitle': "सबटाइटल खोजें और अनुवाद करें",
  'homeSearchPlaceholder': "फ़िल्में या सीरीज़ खोजें...",
  'homeQuickSearch': "खोज",
  'homeQuickHistory': "इतिहास",
  'homeQuickUpload': "अपलोड",
  'homeViewAll': "सब देखें",
  'homeTrendingNow': "अभी ट्रेंड में",
  'homeTrustTitle': "टीमें इस पर भरोसा क्यों करती हैं",
  'homeTrustSubtitle':
      "आज भले मॉक हो, लेकिन इसे असली प्रोडक्ट की तरह संरचित किया गया है।",
  'homeFutureTitle': "भविष्य के लिए तैयार repositories",
  'homeFutureSubtitle':
      "बदले जा सकने वाले mock repositories UI कोड को बैकएंड बदलावों से सुरक्षित रखते हैं।",
  'homePreviewTitle': "प्रीव्यू-केंद्रित अनुवाद फ़्लो",
  'homePreviewSubtitle':
      "एक्सपोर्ट से पहले परिणामों को मूल, अनुवादित या द्विभाषी रूप में देखें।",
  'homeStatesTitle': "सभी ज़रूरी states शामिल",
  'homeStatesSubtitle':
      "लोडिंग, खाली स्थिति, retry, validation और mock offline scenarios शुरू से ही UX का हिस्सा हैं।",
  'navHome': "होम",
  'navHistory': "इतिहास",
  'navSettings': "सेटिंग्स",
  'heroTitle': "सबटाइटल तेजी से अनुवाद करें",
  'heroSubtitle':
      "फ़िल्म और सीरीज़ कैटलॉग खोजें, स्रोत चुनें और कुछ ही मिनटों में polished अनुवाद एक्सपोर्ट करें।",
  'heroBadge': "प्रीमियम सबटाइटल वर्कफ़्लो",
  'heroHeadline':
      "स्टूडियो-ग्रेड फ़्लो के साथ फ़िल्म और सीरीज़ सबटाइटल का अनुवाद करें।",
  'heroBody':
      "खोजने योग्य शीर्षक कैटलॉग या सीधी फ़ाइल अपलोड में से चुनें, फिर कुछ मिनटों में प्रीव्यू देखें और polished सबटाइटल एक्सपोर्ट करें।",
  'heroSearchCta': "फ़िल्म / सीरीज़ खोजें",
  'heroUploadCta': "सबटाइटल अपलोड करें",
  'heroStatPathsTitle': "2 रास्ते",
  'heroStatPathsValue': "खोज या अपलोड",
  'heroStatLanguagesTitle': "10 भाषाएँ",
  'heroStatLanguagesValue': "प्रीव्यू के लिए तैयार",
  'heroStatMockTitle': "Mock APIs",
  'heroStatMockValue': "बैकएंड-रेडी लेयर",
  'settingsTitle': "सेटिंग्स",
  'settingsSubtitle': "अपनी पसंद प्रबंधित करें",
  'settingsProfileName': "SubFlix उपयोगकर्ता",
  'settingsProfileTier': "प्रीमियम सदस्य",
  'settingsLanguageLabel': "पसंदीदा लक्षित भाषा",
  'settingsThemeLabel': "दिखावट",
  'themeSystem': "सिस्टम",
  'themeDark': "डार्क",
  'themeLight': "लाइट",
  'settingsPremiumTitle': "प्रीमियम प्लेसहोल्डर",
  'settingsPremiumSubtitle':
      "आगे चलकर हम यहाँ सब्सक्रिप्शन, बिलिंग और क्लाउड प्रोजेक्ट सिंक जोड़ सकते हैं।",
  'settingsNotificationsTitle': "सूचनाएँ",
  'settingsNotificationsSubtitle': "सूचना प्राथमिकताएँ प्रबंधित करें",
  'settingsHelpCenterTitle': "सहायता केंद्र",
  'settingsContactTitle': "हमसे संपर्क करें",
  'settingsSupportTitle': "सपोर्ट प्लेसहोल्डर",
  'settingsSupportSubtitle': "मॉक सहायता और संपर्क पेज",
  'settingsPrivacyTitle': "गोपनीयता नीति",
  'settingsPrivacySubtitle': "मॉक गोपनीयता सामग्री",
  'settingsTermsTitle': "सेवा की शर्तें",
  'settingsTermsSubtitle': "मॉक शर्तें सामग्री",
  'settingsMaintenanceTitle': "रखरखाव",
  'settingsMaintenanceSubtitle':
      "इस डिवाइस के लिए बैकएंड-स्वामित्व वाले अनुवाद जॉब साफ़ करें और खाली इतिहास से शुरू करें।",
  'settingsHistoryClearedSnack': "इस डिवाइस का अनुवाद इतिहास साफ़ कर दिया गया",
  'settingsAboutTitle': "SubFlix के बारे में",
  'settingsVersion': "संस्करण {version}",
  'settingsClearCache': "कैश साफ़ करें",
  'settingsCacheCleared': "कैश साफ़ हो गया",
  'settingsFailedTitle': "सेटिंग्स लोड नहीं हो सकीं",
  'legalPlaceholderBody':
      "यह पेज डेमो ऐप में एक प्लेसहोल्डर है। इसे अपने प्रोडक्शन कानूनी कंटेंट से जोड़ें।",
  'legalTitlePrivacy': "गोपनीयता नीति",
  'legalTitleTerms': "सेवा की शर्तें",
  'legalTitleSupport': "सपोर्ट",
  'legalTitleAbout': "SubFlix के बारे में",
  'legalBodyPrivacy':
      "SubFlix फिलहाल केवल mock preferences और translation history को local persistence के जरिए डिवाइस पर रखता है। भविष्य में backend integration इसे authenticated storage, audit trails और server-managed retention policies से बदल सकती है।",
  'legalBodyTerms':
      "यह mock build प्रोडक्ट फ्लो, UI states और architecture boundaries को परखने के लिए बनाई गई है। जब बाद में production NestJS और Postgres backend जुड़ जाएगा, तब कानूनी हिस्से को वास्तविक सेवा शर्तों और data processing language के साथ बढ़ाया जा सकता है।",
  'legalBodySupport':
      "अभी के लिए support केवल एक placeholder है। प्रोडक्शन रिलीज़ में यह सेक्शन ईमेल, issue reporting और premium account help से जुड़ सकता है, बिना app shell बदले।",
  'legalBodyAbout':
      "SubFlix AI सबटाइटल अनुवाद के लिए एक premium-style Flutter client है। यह build mock repositories, artificial latency और local persistence का इस्तेमाल करती है ताकि असली backend जुड़ने से पहले UI और architecture विकसित हो सकें।",
  'routeMissingSubtitleSourcesTitle': "सबटाइटल स्रोत",
  'routeMissingSubtitleSourcesMessage':
      "हम तय नहीं कर सके कि किस शीर्षक के लिए सबटाइटल स्रोत लोड करने हैं। खोज से फिर शुरू करें।",
  'routeMissingSeriesSeasonsTitle': "सीरीज़ सीज़न",
  'routeMissingSeriesSeasonsMessage':
      "हम तय नहीं कर सके कि कौन-सी सीरीज़ लोड करनी है। खोज से फिर शुरू करें।",
  'routeMissingSeasonEpisodesTitle': "सीज़न एपिसोड",
  'routeMissingSeasonEpisodesMessage':
      "हम तय नहीं कर सके कि कौन-सा सीज़न लोड करना है। खोज से फिर शुरू करें।",
  'routeMissingTranslationSetupTitle': "अनुवाद सेटअप",
  'routeMissingTranslationSetupMessage':
      "अनुवाद सेटअप स्क्रीन खोलने से पहले एक सबटाइटल स्रोत ज़रूरी है।",
  'routeMissingTranslationProgressTitle': "अनुवाद प्रगति",
  'routeMissingTranslationProgressMessage':
      "कोई अनुवाद अनुरोध नहीं दिया गया। खोज या अपलोड से नया अनुवाद शुरू करें।",
  'searchResultPopularity': "लोकप्रियता {score}",
  'subtitleSourceLines': "{lineCount} पंक्तियाँ",
  'subtitleSourceDownloads': "{downloads} डाउनलोड",
  'subtitleSourceRating': "रेटिंग {rating}",
  'subtitleSourceHiLabel': "HI / SDH",
  'mediaTypeMovie': "फ़िल्म",
  'mediaTypeSeries': "सीरीज़",
  'jobReuseTranslation': "अनुवाद दोबारा इस्तेमाल करें",
  'jobReuseSubtitle': "सबटाइटल दोबारा इस्तेमाल करें",
  'jobConfidence': "विश्वास स्तर: {level}",
  'jobOpenPreview': "प्रीव्यू खोलें",
  'onboardingPage1Title':
      "फ़िल्में या सीरीज़ ढूँढें और अनुवाद के लिए तैयार सबटाइटल पाएँ।",
  'onboardingPage1Eyebrow': "खोजें और लाएँ",
  'onboardingPage1Description':
      "कोई शीर्षक खोजें, उपलब्ध अंग्रेज़ी सबटाइटल स्रोत देखें और ऐसा अनुवाद फ़्लो शुरू करें जो तुरंत महसूस हो।",
  'onboardingPage1Highlight1':
      "विश्वसनीय विकास के लिए deterministic mock catalog",
  'onboardingPage1Highlight2': "सबटाइटल स्रोत quality labels और format badges",
  'onboardingPage1Highlight3': "बाद में असली backend से जोड़ने के लिए तैयार",
  'onboardingPage2Title':
      "जब स्क्रिप्ट आपके पास हो, तब `.srt` या `.vtt` फ़ाइलें अपलोड करें।",
  'onboardingPage2Eyebrow': "अपनी फ़ाइल लाएँ",
  'onboardingPage2Description':
      "अपनी सबटाइटल फ़ाइल इम्पोर्ट करें, फ़ॉर्मैट वैलिडेट करें और ऐप छोड़े बिना वही polished translation pipeline चलाएँ।",
  'onboardingPage2Highlight1': "लोकल फ़ाइल वैलिडेशन और सहज retry states",
  'onboardingPage2Highlight2': "अपलोड और खोज के लिए एकसमान translation setup",
  'onboardingPage2Highlight3':
      "एक्सपोर्ट से पहले प्रीव्यू, ताकि कुछ भी धुंधला न लगे",
  'onboardingPage3Title':
      "लक्षित भाषाएँ चुनें, सबटाइटल प्रीव्यू देखें और तुरंत एक्सपोर्ट करें।",
  'onboardingPage3Eyebrow': "अनुवाद और एक्सपोर्ट",
  'onboardingPage3Description':
      "मूल, अनुवादित और द्विभाषी दृश्य में बदलें, इतिहास फिर देखें और जब परिणाम सही लगे तब साफ़-सुथरी सबटाइटल फ़ाइलें एक्सपोर्ट करें।",
  'onboardingPage3Highlight1': "मेटाडेटा और खोज के साथ तेज़ प्रीव्यू नियंत्रण",
  'onboardingPage3Highlight2': "इतिहास पुराने जॉब को बस एक टैप दूर रखता है",
  'onboardingPage3Highlight3': "डेमो नहीं, एक प्रीमियम मीडिया टूल जैसा डिज़ाइन",
  'onboardingStart': "अनुवाद शुरू करें",
  'onboardingNext': "अगला",
  'onboardingSkip': "छोड़ें",
  'onboardingContinue': "जारी रखें",
  'onboardingEnterApp': "SubFlix में प्रवेश करें",
  'splashHeadline': "SubFlix",
  'splashSubtitle': "AI-संचालित सबटाइटल अनुवाद",
  'splashPreparing': "आपका सबटाइटल स्टूडियो तैयार किया जा रहा है",
  'brandSubtitleCompact': "सबटाइटल इंटेलिजेंस",
  'brandSubtitleFull': "AI सबटाइटल अनुवाद स्टूडियो",
  'comingSoonTitle': "जल्द आ रहा है",
  'comingSoonMessage': "हम अभी यह स्क्रीन तैयार कर रहे हैं।",
};
