const Map<String, String> kStringsPt = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Buscar títulos',
  'searchMovieOrSeriesTitle': 'Buscar filme ou série',
  'searchMovieOrSeriesSubtitle':
      'Encontre um título, confira as fontes de legenda e inicie uma tradução com poucos toques.',
  'searchHintText': 'Busque por Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Pesquise qualquer coisa no catálogo de teste',
  'searchMockMessage':
      'Experimente títulos como Inception, Dune, Breaking Bad, Severance ou The Last of Us para explorar o fluxo de fontes de legenda.',
  'searchFailedTitle': 'A busca falhou',
  'noTitlesMatchedTitle': 'Nenhum resultado encontrado',
  'noTitlesMatchedMessage':
      'Não encontramos esse título no catálogo de teste. Tente uma busca mais ampla ou um dos títulos sugeridos.',
  'searchTrendingTitle': 'Buscas em alta',
  'searchLoadingLabel': 'Buscando...',
  'searchFoundResults': '{count} resultados encontrados para \'{query}\'',
  'searchNoResultsFor': 'Nenhum resultado encontrado para \'{query}\'',
  'searchTryDifferentKeywords': 'Tente buscar com outras palavras-chave.',
  'retry': 'Tentar novamente',
  'retryTranslation': 'Refazer tradução',
  'uploadSubtitleTitle': 'Enviar legenda',
  'uploadIntroTitle': 'Use o seu próprio arquivo de legenda',
  'uploadIntroSubtitle':
      'Importe um arquivo em inglês `.srt` ou `.vtt`, deixe o backend validar e interpretar o conteúdo e depois siga para a configuração da tradução.',
  'uploadChooseFile': 'Escolher arquivo de legenda',
  'uploadSupportedFormatsTitle': 'Formatos compatíveis',
  'uploadSupportedFormatsSubtitle':
      'Arquivos de legenda em inglês `.srt` e `.vtt`',
  'uploadOpeningPicker': 'Abrindo seletor...',
  'uploadChooseFileShort': 'Escolher arquivo',
  'uploadPickSubtitle': 'Selecionar arquivo de legenda',
  'uploadPickedFile': 'Arquivo de legenda selecionado',
  'uploadUseDemoFile': 'Usar arquivo de demonstração',
  'uploadFailedTitle': 'Falha ao importar o arquivo',
  'uploadFailedMessage':
      'Não foi possível ler este arquivo de legenda. Tente outro arquivo ou uma exportação menor.',
  'uploadFailedFallback': 'Tente outro arquivo de legenda.',
  'tryAgain': 'Tente novamente',
  'uploadMetadataTitle': 'Detalhes da legenda',
  'uploadReadyTitle': 'Pronto para traduzir',
  'uploadLineCount': '{lineCount} linhas',
  'uploadEnglishSource': 'Fonte em inglês',
  'uploadContinueSetup': 'Continuar para a configuração da tradução',
  'translateSetupTitle': 'Configuração da tradução',
  'translateSetupSubtitle':
      'Escolha o idioma de destino, revise a fonte da legenda e inicie a tradução no backend.',
  'translateSetupSourceTitle': 'Legenda de origem',
  'translateSetupLanguageTitle': 'Traduzir para',
  'translateSetupOptionsTitle': 'Opções',
  'translateSetupSelectLanguage': 'Selecionar idioma',
  'translateSetupReadyTitle': 'Tradução por IA pronta',
  'translateSetupReadyBody':
      'Nosso fluxo vai adaptar esta legenda para {language}, preservando o tempo e uma estrutura de cues limpa.',
  'translateSetupPreserveTiming': 'Preservar tempo',
  'translateSetupPreserveTimingBody':
      'Mantém os tempos originais da legenda alinhados com o arquivo de origem.',
  'translateSetupAutoDetect': 'Detectar formato automaticamente',
  'translateSetupAutoDetectBody':
      'Escolhe automaticamente a estrutura certa de saída da legenda.',
  'subtitleSourceFormatLabel': 'Fonte de legenda {format}',
  'targetLanguage': 'Idioma de destino',
  'startTranslation': 'Iniciar tradução',
  'translationProgressTitle': 'Progresso da tradução',
  'translationProgressHeadline': 'Tradução de legendas por IA em andamento',
  'translationFailedTitle': 'Não foi possível concluir a tradução',
  'translationFailedMessage': 'Algo deu errado.',
  'translationStageQueued': 'Na fila para tradução',
  'translationStageIdle': 'Aguardando um pedido de tradução',
  'translationStagePreparing': 'Preparando pacote de legendas',
  'translationStageAligning': 'Alinhando timestamps e contexto da cena',
  'translationStageGenerating': 'Gerando a tradução da legenda',
  'translationStageReadability': 'Aplicando revisão de legibilidade',
  'translationStageReady': 'Tradução pronta',
  'translationResultCompleteTitle': 'Tradução concluída',
  'translationResultCompleteSubtitle':
      'Sua legenda está pronta para visualizar ou baixar.',
  'translationResultDetailsTitle': 'Detalhes da tradução',
  'translationResultMediaLabel': 'Título da mídia',
  'translationResultSourceLabel': 'Idioma de origem',
  'translationResultTargetLabel': 'Idioma de destino',
  'translationResultMethodAi': 'Traduzido por IA',
  'translationResultMetricsTitle': 'Métricas de qualidade',
  'translationResultConfidenceLabel': 'Confiabilidade da tradução',
  'translationResultTimingLabel': 'Precisão do tempo',
  'translationResultTimingPreserved': 'Tempo preservado',
  'translationResultProcessedIn': 'Processado em {duration}',
  'translationResultWarning':
      'Alguns termos técnicos ainda podem se beneficiar de uma revisão humana rápida para garantir o contexto.',
  'translationResultPreviewCta': 'Visualizar legenda',
  'translationResultDownloadCta': 'Baixar legenda',
  'translationResultHomeCta': 'Voltar para a home',
  'translationPreviewTitle': 'Prévia da tradução',
  'translationPreviewHeader': 'Revise as legendas traduzidas',
  'translationPreviewSubtitle':
      'Pesquise dentro dos cues, alterne o modo de visualização e exporte quando o resultado estiver certo.',
  'translationPreviewSearchHint': 'Buscar linhas da legenda',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Traduzido',
  'previewModeBilingual': 'Bilíngue',
  'previewNotReadyTitle': 'Os cues de prévia ainda não estão disponíveis',
  'previewNotReadyMessage':
      'A tradução foi concluída, mas o backend ainda não retornou os cues de prévia. Tente recarregar esta tela em instantes.',
  'previewNoMatchesTitle': 'Nenhuma linha da legenda correspondeu',
  'previewNoMatchesMessage':
      'Tente outro termo de busca ou limpe o filtro para analisar a tradução completa.',
  'previewFailedTitle': 'Falha ao carregar a prévia',
  'exportingLabel': 'Exportando...',
  'exportSubtitleLabel': 'Exportar legenda traduzida',
  'exportedSnack': '{fileName} exportado para {path}',
  'exportFailedSnack': 'Falha na exportação: {error}',
  'metadataFormat': 'Formato',
  'metadataLines': 'Linhas',
  'metadataLanguages': 'Idiomas',
  'metadataEstimatedDuration': 'Duração estimada',
  'subtitleSourcesTitle': 'Fontes de legenda em inglês',
  'subtitleSourcesSubtitle':
      'Escolha uma fonte de legenda para {title}{target} e depois selecione o idioma de destino na próxima etapa.',
  'subtitleSourcesBannerTitle': 'Tradução por IA disponível',
  'subtitleSourcesBannerMessage':
      'Selecione uma fonte de legenda e siga para uma configuração refinada, ajustada ao timing da legenda.',
  'subtitleSourcesFailedTitle':
      'Não foi possível carregar as fontes de legenda',
  'seriesSeasonsTitle': 'Escolha uma temporada',
  'seriesSeasonsSubtitle':
      'Escolha uma temporada de {title} para ver os episódios disponíveis.',
  'seriesSeasonLabel': 'Temporada {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} episódios{year}',
  'seriesEpisodesTitle': 'Temporada {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} episódios{year}',
  'seriesEpisodeLabel': 'Episódio {episodeNumber}',
  'seriesEpisodeMeta': 'Aprox. {runtime} min',
  'historyTitle': 'Histórico de traduções',
  'historySubtitle':
      'Reabra trabalhos anteriores, revise a prévia novamente ou exporte depois.',
  'historyEmptyTitle': 'O histórico está vazio',
  'historyEmptyMessage':
      'Seus trabalhos de legenda traduzida aparecerão aqui depois que você concluir um fluxo de busca ou envio.',
  'historyFailedTitle': 'Não foi possível carregar o histórico',
  'historyCountLabel': '{count} traduções',
  'historyFilterAll': 'Todos',
  'historyFilterMovies': 'Filmes',
  'historyFilterSeries': 'Séries',
  'historyFilterCompleted': 'Concluídos',
  'historyFilterAiTranslated': 'Traduzido por IA',
  'historyFilterFailed': 'Falhou',
  'historyFilterReused': 'Reutilizado',
  'historyFailedItemMessage': 'A tradução falhou. Toque para começar de novo.',
  'homeRecentJobsTitle': 'Trabalhos recentes',
  'homeRecentJobsSubtitle':
      'Reabra suas sessões mais recentes sem começar do zero.',
  'homeNoRecentTitle': 'Ainda não há trabalhos recentes',
  'homeNoRecentMessage':
      'Comece com uma busca por filme ou envie um arquivo de legenda e suas traduções recentes aparecerão aqui.',
  'homeFailedRecentTitle': 'Não foi possível carregar os trabalhos recentes',
  'homeWelcomeTitle': 'Bem-vindo de volta',
  'homeWelcomeSubtitle': 'Encontre e traduza legendas',
  'homeSearchPlaceholder': 'Buscar filmes ou séries...',
  'homeQuickSearch': 'Buscar',
  'homeQuickHistory': 'Histórico',
  'homeQuickUpload': 'Enviar',
  'homeViewAll': 'Ver tudo',
  'homeTrendingNow': 'Em alta agora',
  'homeTrustTitle': 'Por que as equipes confiam nisso',
  'homeTrustSubtitle':
      'Hoje ainda é mockado, mas já foi estruturado como um produto real.',
  'homeFutureTitle': 'Repositórios prontos para o futuro',
  'homeFutureSubtitle':
      'Repositórios mock intercambiáveis mantêm o código de UI protegido contra mudanças no backend.',
  'homePreviewTitle': 'Fluxo de tradução guiado por prévia',
  'homePreviewSubtitle':
      'Analise os resultados antes de exportar nas visualizações original, traduzida ou bilíngue.',
  'homeStatesTitle': 'Estados bem resolvidos inclusos',
  'homeStatesSubtitle':
      'Carregamento, vazio, retry, validação e cenários mock offline fazem parte da UX desde o primeiro dia.',
  'navHome': 'Home',
  'navHistory': 'Histórico',
  'navSettings': 'Configurações',
  'heroTitle': 'Traduza legendas mais rápido',
  'heroSubtitle':
      'Pesquise catálogos de filmes e séries, escolha fontes e exporte traduções refinadas em minutos.',
  'heroBadge': 'Fluxo premium de legendas',
  'heroHeadline':
      'Traduza legendas de filmes e séries com um fluxo de nível profissional.',
  'heroBody':
      'Escolha entre um catálogo pesquisável ou o envio direto de arquivo, depois visualize e exporte legendas refinadas em poucos minutos.',
  'heroSearchCta': 'Buscar filme / série',
  'heroUploadCta': 'Enviar legenda',
  'heroStatPathsTitle': '2 caminhos',
  'heroStatPathsValue': 'Buscar ou enviar',
  'heroStatLanguagesTitle': '10 idiomas',
  'heroStatLanguagesValue': 'Prontos para prévia',
  'heroStatMockTitle': 'APIs mock',
  'heroStatMockValue': 'Camada pronta para backend',
  'settingsTitle': 'Configurações',
  'settingsSubtitle': 'Gerencie suas preferências',
  'settingsProfileName': 'Usuário SubFlix',
  'settingsProfileTier': 'Membro premium',
  'settingsLanguageLabel': 'Idioma de destino preferido',
  'settingsThemeLabel': 'Aparência',
  'themeSystem': 'Sistema',
  'themeDark': 'Escuro',
  'themeLight': 'Claro',
  'settingsPremiumTitle': 'Espaço premium',
  'settingsPremiumSubtitle':
      'Depois poderemos conectar aqui assinaturas, cobrança e sincronização de projetos na nuvem.',
  'settingsNotificationsTitle': 'Notificações',
  'settingsNotificationsSubtitle': 'Gerencie as preferências de notificação',
  'settingsHelpCenterTitle': 'Central de ajuda',
  'settingsContactTitle': 'Fale conosco',
  'settingsSupportTitle': 'Espaço de suporte',
  'settingsSupportSubtitle': 'Página mock de ajuda e contato',
  'settingsPrivacyTitle': 'Política de privacidade',
  'settingsPrivacySubtitle': 'Conteúdo mock de privacidade',
  'settingsTermsTitle': 'Termos de serviço',
  'settingsTermsSubtitle': 'Conteúdo mock de termos',
  'settingsMaintenanceTitle': 'Manutenção',
  'settingsMaintenanceSubtitle':
      'Limpe os trabalhos de tradução controlados pelo backend neste dispositivo e recomece com o histórico vazio.',
  'settingsHistoryClearedSnack':
      'Histórico de traduções apagado neste dispositivo',
  'settingsAboutTitle': 'Sobre o SubFlix',
  'settingsVersion': 'Versão {version}',
  'settingsClearCache': 'Limpar cache',
  'settingsCacheCleared': 'Cache limpo',
  'settingsFailedTitle': 'Falha ao carregar as configurações',
  'legalPlaceholderBody':
      'Esta página é apenas um placeholder no app de demonstração. Conecte-a ao seu conteúdo jurídico de produção.',
  'legalTitlePrivacy': 'Política de privacidade',
  'legalTitleTerms': 'Termos de serviço',
  'legalTitleSupport': 'Suporte',
  'legalTitleAbout': 'Sobre o SubFlix',
  'legalBodyPrivacy':
      'Atualmente, o SubFlix armazena apenas preferências mock e histórico de tradução no dispositivo por meio de persistência local. No futuro, uma integração com backend pode substituir isso por armazenamento autenticado, trilhas de auditoria e políticas de retenção gerenciadas pelo servidor.',
  'legalBodyTerms':
      'Este build mock foi criado para exercitar fluxos de produto, estados de UI e limites de arquitetura. Quando um backend de produção com NestJS e Postgres for conectado mais tarde, a camada jurídica poderá ser expandida com termos reais de serviço e linguagem de processamento de dados.',
  'legalBodySupport':
      'Por enquanto, o suporte é apenas um placeholder. Em uma versão de produção, esta seção poderá se conectar a e-mail, relato de problemas e ajuda para contas premium sem alterar a estrutura do app.',
  'legalBodyAbout':
      'O SubFlix é um cliente Flutter com proposta premium para tradução de legendas por IA. Este build usa repositórios mock, latência artificial e persistência local para que a UI e a arquitetura evoluam antes da conexão com um backend real.',
  'routeMissingSubtitleSourcesTitle': 'Fontes de legenda',
  'routeMissingSubtitleSourcesMessage':
      'Não conseguimos determinar para qual título as fontes de legenda devem ser carregadas. Recomece pela busca.',
  'routeMissingSeriesSeasonsTitle': 'Temporadas da série',
  'routeMissingSeriesSeasonsMessage':
      'Não conseguimos determinar qual série deve ser carregada. Recomece pela busca.',
  'routeMissingSeasonEpisodesTitle': 'Episódios da temporada',
  'routeMissingSeasonEpisodesMessage':
      'Não conseguimos determinar qual temporada deve ser carregada. Recomece pela busca.',
  'routeMissingTranslationSetupTitle': 'Configuração da tradução',
  'routeMissingTranslationSetupMessage':
      'É necessário ter uma fonte de legenda antes de abrir a tela de configuração da tradução.',
  'routeMissingTranslationProgressTitle': 'Progresso da tradução',
  'routeMissingTranslationProgressMessage':
      'Nenhum pedido de tradução foi fornecido. Inicie uma nova tradução pela busca ou pelo envio.',
  'searchResultPopularity': 'Popularidade {score}',
  'subtitleSourceLines': '{lineCount} linhas',
  'subtitleSourceDownloads': '{downloads} downloads',
  'subtitleSourceRating': 'Avaliação {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Filme',
  'mediaTypeSeries': 'Série',
  'jobReuseTranslation': 'Reutilizar tradução',
  'jobReuseSubtitle': 'Reutilizar legenda',
  'jobConfidence': 'Confiabilidade: {level}',
  'jobOpenPreview': 'Abrir prévia',
  'onboardingPage1Title':
      'Encontre filmes ou séries e puxe legendas prontas para traduzir.',
  'onboardingPage1Eyebrow': 'Buscar e obter',
  'onboardingPage1Description':
      'Pesquise um título, confira as fontes de legenda em inglês disponíveis e inicie um fluxo de tradução que parece imediato.',
  'onboardingPage1Highlight1':
      'Catálogo mock determinístico para desenvolvimento confiável',
  'onboardingPage1Highlight2': 'Rótulos de qualidade e badges de formato',
  'onboardingPage1Highlight3': 'Feito para trocar por um backend real depois',
  'onboardingPage2Title':
      'Envie arquivos `.srt` ou `.vtt` quando você já tiver o script.',
  'onboardingPage2Eyebrow': 'Use o seu próprio arquivo',
  'onboardingPage2Description':
      'Importe seu arquivo de legenda, valide o formato e rode o mesmo pipeline refinado sem sair do app.',
  'onboardingPage2Highlight1':
      'Validação local de arquivo e estados de retry bem resolvidos',
  'onboardingPage2Highlight2': 'Configuração consistente para envio e busca',
  'onboardingPage2Highlight3':
      'Prévia antes de exportar para que nada fique opaco',
  'onboardingPage3Title':
      'Escolha os idiomas de destino, visualize as legendas e exporte na hora.',
  'onboardingPage3Eyebrow': 'Traduzir e exportar',
  'onboardingPage3Description':
      'Alterne entre as visões original, traduzida e bilíngue, revisite o histórico e exporte arquivos limpos quando o resultado estiver do jeito certo.',
  'onboardingPage3Highlight1':
      'Controles rápidos de prévia com metadados e busca',
  'onboardingPage3Highlight2':
      'O histórico mantém trabalhos anteriores a um toque de distância',
  'onboardingPage3Highlight3':
      'Desenhado como uma ferramenta premium de mídia, não como demo',
  'onboardingStart': 'Iniciar tradução',
  'onboardingNext': 'Próximo',
  'onboardingSkip': 'Pular',
  'onboardingContinue': 'Continuar',
  'onboardingEnterApp': 'Entrar no SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'Tradução de legendas com IA',
  'splashPreparing': 'Preparando seu estúdio de legendas',
  'brandSubtitleCompact': 'Inteligência de legendas',
  'brandSubtitleFull': 'Estúdio de tradução de legendas por IA',
  'comingSoonTitle': 'Em breve',
  'comingSoonMessage': 'Ainda estamos preparando esta tela.',
};
