const Map<String, String> kStringsAr = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'البحث عن العناوين',
  'searchMovieOrSeriesTitle': 'ابحث عن فيلم أو مسلسل',
  'searchMovieOrSeriesSubtitle':
      'اعثر على عنوان، وتفقّد مصادر الترجمة، وابدأ مهمة الترجمة ببضع لمسات.',
  'searchHintText': 'ابحث عن Dune أو Breaking Bad أو Severance...',
  'searchMockTitle': 'ابحث عن أي شيء في الفهرس التجريبي',
  'searchMockMessage':
      'جرّب عناوين مثل Inception أو Dune أو Breaking Bad أو Severance أو The Last of Us لاستكشاف مسار مصادر الترجمة.',
  'searchFailedTitle': 'فشل البحث',
  'noTitlesMatchedTitle': 'لا توجد نتائج مطابقة',
  'noTitlesMatchedMessage':
      'لم نتمكن من العثور على هذا العنوان في الفهرس التجريبي. جرّب بحثًا أوسع أو أحد العناوين المقترحة.',
  'searchTrendingTitle': 'عمليات البحث الرائجة',
  'searchLoadingLabel': 'جارٍ البحث...',
  'searchFoundResults': 'تم العثور على {count} نتيجة لعبارة \'{query}\'',
  'searchNoResultsFor': 'لم يتم العثور على نتائج لعبارة \'{query}\'',
  'searchTryDifferentKeywords': 'جرّب البحث بكلمات مختلفة.',
  'retry': 'إعادة المحاولة',
  'retryTranslation': 'إعادة الترجمة',
  'uploadSubtitleTitle': 'رفع الترجمة',
  'uploadIntroTitle': 'استخدم ملف الترجمة الخاص بك',
  'uploadIntroSubtitle':
      'استورد ملف `.srt` أو `.vtt` باللغة الإنجليزية، ودع الخادم يتحقق منه ويحلّله، ثم تابع إلى إعداد الترجمة.',
  'uploadChooseFile': 'اختر ملف ترجمة',
  'uploadSupportedFormatsTitle': 'الصيغ المدعومة',
  'uploadSupportedFormatsSubtitle':
      'ملفات ترجمة إنجليزية بصيغة `.srt` و `.vtt`',
  'uploadOpeningPicker': 'جارٍ فتح أداة الاختيار...',
  'uploadChooseFileShort': 'اختر ملفًا',
  'uploadPickSubtitle': 'اختر ملف الترجمة',
  'uploadPickedFile': 'تم اختيار ملف الترجمة',
  'uploadUseDemoFile': 'استخدام ملف تجريبي',
  'uploadFailedTitle': 'فشل استيراد الملف',
  'uploadFailedMessage':
      'تعذّرت قراءة ملف الترجمة هذا. جرّب ملفًا آخر أو ملف تصدير أصغر.',
  'uploadFailedFallback': 'يرجى تجربة ملف ترجمة آخر.',
  'tryAgain': 'جرّب مرة أخرى',
  'uploadMetadataTitle': 'تفاصيل الترجمة',
  'uploadReadyTitle': 'جاهز للترجمة',
  'uploadLineCount': '{lineCount} سطرًا',
  'uploadEnglishSource': 'المصدر الإنجليزي',
  'uploadContinueSetup': 'متابعة إلى إعداد الترجمة',
  'translateSetupTitle': 'إعداد الترجمة',
  'translateSetupSubtitle':
      'اختر اللغة المستهدفة، وراجع مصدر الترجمة، ثم ابدأ مهمة الترجمة في الخادم.',
  'translateSetupSourceTitle': 'الترجمة المصدر',
  'translateSetupLanguageTitle': 'الترجمة إلى',
  'translateSetupOptionsTitle': 'الخيارات',
  'translateSetupSelectLanguage': 'اختر اللغة',
  'translateSetupReadyTitle': 'الترجمة بالذكاء الاصطناعي جاهزة',
  'translateSetupReadyBody':
      'سيحوّل مسار الترجمة لدينا هذه الترجمة إلى {language} مع الحفاظ على التوقيت وبنية الأسطر بشكل نظيف.',
  'translateSetupPreserveTiming': 'الحفاظ على التوقيت',
  'translateSetupPreserveTimingBody':
      'أبقِ توقيتات الترجمة الأصلية متطابقة مع الملف المصدر.',
  'translateSetupAutoDetect': 'اكتشاف الصيغة تلقائيًا',
  'translateSetupAutoDetectBody': 'اختر بنية إخراج الترجمة المناسبة تلقائيًا.',
  'subtitleSourceFormatLabel': 'مصدر ترجمة {format}',
  'targetLanguage': 'اللغة المستهدفة',
  'startTranslation': 'بدء الترجمة',
  'translationProgressTitle': 'تقدّم الترجمة',
  'translationProgressHeadline': 'ترجمة الترجمة بالذكاء الاصطناعي قيد التنفيذ',
  'translationFailedTitle': 'تعذّر إكمال الترجمة',
  'translationFailedMessage': 'حدث خطأ ما.',
  'translationStageQueued': 'في انتظار الدور للترجمة',
  'translationStageIdle': 'بانتظار طلب ترجمة',
  'translationStagePreparing': 'جارٍ تجهيز حزمة الترجمة',
  'translationStageAligning': 'جارٍ مواءمة الطوابع الزمنية وسياق المشهد',
  'translationStageGenerating': 'جارٍ إنشاء الترجمة',
  'translationStageReadability': 'جارٍ تحسين قابلية القراءة',
  'translationStageReady': 'الترجمة جاهزة',
  'translationResultCompleteTitle': 'اكتملت الترجمة',
  'translationResultCompleteSubtitle':
      'أصبحت الترجمة جاهزة للمعاينة أو التنزيل.',
  'translationResultDetailsTitle': 'تفاصيل الترجمة',
  'translationResultMediaLabel': 'عنوان العمل',
  'translationResultSourceLabel': 'لغة المصدر',
  'translationResultTargetLabel': 'اللغة المستهدفة',
  'translationResultMethodAi': 'مترجمة بالذكاء الاصطناعي',
  'translationResultMetricsTitle': 'مقاييس الجودة',
  'translationResultConfidenceLabel': 'ثقة الترجمة',
  'translationResultTimingLabel': 'دقة التوقيت',
  'translationResultTimingPreserved': 'تم الحفاظ على التوقيت',
  'translationResultProcessedIn': 'تمت المعالجة خلال {duration}',
  'translationResultWarning':
      'قد تستفيد بعض المصطلحات التقنية من مراجعة بشرية سريعة لفهم السياق.',
  'translationResultPreviewCta': 'معاينة الترجمة',
  'translationResultDownloadCta': 'تنزيل الترجمة',
  'translationResultHomeCta': 'العودة إلى الرئيسية',
  'translationPreviewTitle': 'معاينة الترجمة',
  'translationPreviewHeader': 'راجع الترجمات المترجمة',
  'translationPreviewSubtitle':
      'ابحث داخل الأسطر، وبدّل أوضاع المعاينة، ثم صدّر الملف عندما تبدو الترجمة مناسبة.',
  'translationPreviewSearchHint': 'ابحث في أسطر الترجمة',
  'previewModeOriginal': 'الأصل',
  'previewModeTranslated': 'المترجم',
  'previewModeBilingual': 'ثنائي اللغة',
  'previewNotReadyTitle': 'أسطر المعاينة غير متاحة بعد',
  'previewNotReadyMessage':
      'اكتملت الترجمة، لكن الخادم لم يُرجع أسطر المعاينة بعد. جرّب إعادة تحميل هذه الشاشة بعد لحظة.',
  'previewNoMatchesTitle': 'لم تتم مطابقة أي أسطر',
  'previewNoMatchesMessage':
      'جرّب كلمة بحث مختلفة أو أزل التصفية لمراجعة الترجمة كاملة.',
  'previewFailedTitle': 'فشل تحميل المعاينة',
  'exportingLabel': 'جارٍ التصدير...',
  'exportSubtitleLabel': 'تصدير الترجمة المترجمة',
  'exportedSnack': 'تم تصدير {fileName} إلى {path}',
  'exportFailedSnack': 'فشل التصدير: {error}',
  'metadataFormat': 'الصيغة',
  'metadataLines': 'الأسطر',
  'metadataLanguages': 'اللغات',
  'metadataEstimatedDuration': 'المدة التقديرية',
  'subtitleSourcesTitle': 'مصادر الترجمة الإنجليزية',
  'subtitleSourcesSubtitle':
      'اختر مصدر ترجمة لـ {title}{target}، ثم اختر اللغة المستهدفة في الخطوة التالية.',
  'subtitleSourcesBannerTitle': 'الترجمة بالذكاء الاصطناعي متاحة',
  'subtitleSourcesBannerMessage':
      'اختر مصدر ترجمة وتابع إلى إعداد ترجمة مصقول ومهيأ لتوقيت الترجمة.',
  'subtitleSourcesFailedTitle': 'تعذّر تحميل مصادر الترجمة',
  'seriesSeasonsTitle': 'اختر موسمًا',
  'seriesSeasonsSubtitle': 'اختر موسمًا من {title} لتصفّح الحلقات المتاحة.',
  'seriesSeasonLabel': 'الموسم {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} حلقة{year}',
  'seriesEpisodesTitle': 'الموسم {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} حلقة{year}',
  'seriesEpisodeLabel': 'الحلقة {episodeNumber}',
  'seriesEpisodeMeta': 'حوالي {runtime} دقيقة',
  'historyTitle': 'سجل الترجمات',
  'historySubtitle':
      'أعد فتح مهام الترجمة السابقة، وراجع المعاينة مجددًا، أو صدّرها لاحقًا.',
  'historyEmptyTitle': 'السجل فارغ',
  'historyEmptyMessage':
      'ستظهر مهام الترجمة المنجزة هنا بعد إكمال مسار البحث أو الرفع.',
  'historyFailedTitle': 'تعذّر تحميل السجل',
  'historyCountLabel': '{count} ترجمة',
  'historyFilterAll': 'الكل',
  'historyFilterMovies': 'الأفلام',
  'historyFilterSeries': 'المسلسلات',
  'historyFilterCompleted': 'مكتملة',
  'historyFilterAiTranslated': 'مترجمة بالذكاء الاصطناعي',
  'historyFilterFailed': 'فاشلة',
  'historyFilterReused': 'معاد استخدامها',
  'historyFailedItemMessage': 'فشلت الترجمة. اضغط للبدء من جديد.',
  'homeRecentJobsTitle': 'المهام الأخيرة',
  'homeRecentJobsSubtitle':
      'أعد فتح أحدث جلسات الترجمة لديك دون البدء من الصفر.',
  'homeNoRecentTitle': 'لا توجد مهام حديثة بعد',
  'homeNoRecentMessage':
      'ابدأ بالبحث عن فيلم أو ارفع ملف ترجمة، وستظهر ترجماتك الأخيرة هنا.',
  'homeFailedRecentTitle': 'تعذّر تحميل المهام الأخيرة',
  'homeWelcomeTitle': 'مرحبًا بعودتك',
  'homeWelcomeSubtitle': 'اعثر على الترجمات وترجمها',
  'homeSearchPlaceholder': 'ابحث عن أفلام أو مسلسلات...',
  'homeQuickSearch': 'بحث',
  'homeQuickHistory': 'السجل',
  'homeQuickUpload': 'رفع',
  'homeViewAll': 'عرض الكل',
  'homeTrendingNow': 'الرائج الآن',
  'homeTrustTitle': 'لماذا تثق به الفرق',
  'homeTrustSubtitle': 'مُحاكى اليوم، لكنه مبني كمنتج قابل للإطلاق فعليًا.',
  'homeFutureTitle': 'مستودعات جاهزة للمستقبل',
  'homeFutureSubtitle':
      'تُبقي المستودعات التجريبية القابلة للاستبدال واجهة المستخدم معزولة عن تغييرات الخادم.',
  'homePreviewTitle': 'مسار ترجمة قائم على المعاينة أولًا',
  'homePreviewSubtitle':
      'راجع النتائج قبل التصدير عبر العرض الأصلي أو المترجم أو الثنائي اللغة.',
  'homeStatesTitle': 'حالات استخدام سلسة مضمّنة',
  'homeStatesSubtitle':
      'التحميل، والفراغ، وإعادة المحاولة، والتحقق، وسيناريوهات عدم الاتصال التجريبية جزء من تجربة الاستخدام منذ اليوم الأول.',
  'navHome': 'الرئيسية',
  'navHistory': 'السجل',
  'navSettings': 'الإعدادات',
  'heroTitle': 'ترجم الترجمات بسرعة أكبر',
  'heroSubtitle':
      'ابحث في فهارس الأفلام والمسلسلات، واختر المصادر، وصدّر ترجمات مصقولة خلال دقائق.',
  'heroBadge': 'مسار ترجمة احترافي',
  'heroHeadline': 'ترجم ترجمات الأفلام والمسلسلات بمسار عمل بمستوى الاستوديو.',
  'heroBody':
      'اختر بين فهرس عناوين قابل للبحث أو رفع ملف مباشر، ثم عاين وصدّر ترجمات مصقولة خلال دقائق.',
  'heroSearchCta': 'ابحث عن فيلم / مسلسل',
  'heroUploadCta': 'رفع الترجمة',
  'heroStatPathsTitle': 'مساران',
  'heroStatPathsValue': 'بحث أو رفع',
  'heroStatLanguagesTitle': '10 لغات',
  'heroStatLanguagesValue': 'جاهزة للمعاينة',
  'heroStatMockTitle': 'واجهات وهمية',
  'heroStatMockValue': 'نقطة جاهزة للخادم',
  'settingsTitle': 'الإعدادات',
  'settingsSubtitle': 'أدر تفضيلاتك',
  'settingsProfileName': 'مستخدم SubFlix',
  'settingsProfileTier': 'عضو مميز',
  'settingsLanguageLabel': 'اللغة المستهدفة المفضلة',
  'settingsThemeLabel': 'المظهر',
  'themeSystem': 'النظام',
  'themeDark': 'داكن',
  'themeLight': 'فاتح',
  'settingsPremiumTitle': 'عنصر مميز تجريبي',
  'settingsPremiumSubtitle':
      'لاحقًا يمكننا ربط الاشتراكات والفوترة ومزامنة المشاريع السحابية هنا.',
  'settingsNotificationsTitle': 'الإشعارات',
  'settingsNotificationsSubtitle': 'أدر تفضيلات الإشعارات',
  'settingsHelpCenterTitle': 'مركز المساعدة',
  'settingsContactTitle': 'تواصل معنا',
  'settingsSupportTitle': 'قسم دعم تجريبي',
  'settingsSupportSubtitle': 'صفحة مساعدة واتصال تجريبية',
  'settingsPrivacyTitle': 'سياسة الخصوصية',
  'settingsPrivacySubtitle': 'محتوى خصوصية تجريبي',
  'settingsTermsTitle': 'شروط الخدمة',
  'settingsTermsSubtitle': 'محتوى شروط تجريبي',
  'settingsMaintenanceTitle': 'الصيانة',
  'settingsMaintenanceSubtitle':
      'امسح مهام الترجمة التابعة للخادم لهذا الجهاز وابدأ بسجل فارغ.',
  'settingsHistoryClearedSnack': 'تم مسح سجل الترجمة لهذا الجهاز',
  'settingsAboutTitle': 'حول SubFlix',
  'settingsVersion': 'الإصدار {version}',
  'settingsClearCache': 'مسح الذاكرة المؤقتة',
  'settingsCacheCleared': 'تم مسح الذاكرة المؤقتة',
  'settingsFailedTitle': 'فشل تحميل الإعدادات',
  'legalPlaceholderBody':
      'هذه الصفحة مجرد عنصر نائب في التطبيق التجريبي. اربطها بمحتواك القانوني الحقيقي في نسخة الإنتاج.',
  'legalTitlePrivacy': 'سياسة الخصوصية',
  'legalTitleTerms': 'شروط الخدمة',
  'legalTitleSupport': 'الدعم',
  'legalTitleAbout': 'حول SubFlix',
  'legalBodyPrivacy':
      'يخزن SubFlix حاليًا التفضيلات التجريبية وسجل الترجمة فقط على الجهاز عبر التخزين المحلي. يمكن أن يستبدل تكامل خادم مستقبلي ذلك بتخزين موثّق، ومسارات تدقيق، وسياسات احتفاظ تُدار من الخادم.',
  'legalBodyTerms':
      'تهدف هذه النسخة التجريبية إلى اختبار تدفقات المنتج، وحالات الواجهة، وحدود البنية. وعندما يتم ربط خادم إنتاجي يعتمد على NestJS وPostgres لاحقًا، يمكن توسيع السطح القانوني بشروط خدمة حقيقية وصياغات لمعالجة البيانات.',
  'legalBodySupport':
      'الدعم مجرد عنصر نائب حاليًا. في إصدار الإنتاج يمكن لهذا القسم أن يتصل بالبريد الإلكتروني، وتقارير المشكلات، ومساعدة الحسابات المميزة مع بقاء هيكل التطبيق كما هو.',
  'legalBodyAbout':
      'SubFlix عميل Flutter بطابع احترافي لترجمة الترجمة بالذكاء الاصطناعي. تستخدم هذه النسخة مستودعات وهمية، وتأخيرًا اصطناعيًا، وتخزينًا محليًا حتى تتطور الواجهة والبنية قبل ربط خادم حقيقي.',
  'routeMissingSubtitleSourcesTitle': 'مصادر الترجمة',
  'routeMissingSubtitleSourcesMessage':
      'لم نتمكن من تحديد العنوان الذي يجب تحميل مصادر الترجمة له. ابدأ مجددًا من البحث.',
  'routeMissingSeriesSeasonsTitle': 'مواسم المسلسل',
  'routeMissingSeriesSeasonsMessage':
      'لم نتمكن من تحديد المسلسل المطلوب تحميله. ابدأ مجددًا من البحث.',
  'routeMissingSeasonEpisodesTitle': 'حلقات الموسم',
  'routeMissingSeasonEpisodesMessage':
      'لم نتمكن من تحديد الموسم المطلوب تحميله. ابدأ مجددًا من البحث.',
  'routeMissingTranslationSetupTitle': 'إعداد الترجمة',
  'routeMissingTranslationSetupMessage':
      'مصدر الترجمة مطلوب قبل فتح شاشة إعداد الترجمة.',
  'routeMissingTranslationProgressTitle': 'تقدّم الترجمة',
  'routeMissingTranslationProgressMessage':
      'لم يتم توفير طلب ترجمة. ابدأ ترجمة جديدة من البحث أو الرفع.',
  'searchResultPopularity': 'الشعبية {score}',
  'subtitleSourceLines': '{lineCount} سطرًا',
  'subtitleSourceDownloads': '{downloads} تنزيلًا',
  'subtitleSourceRating': 'التقييم {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'فيلم',
  'mediaTypeSeries': 'مسلسل',
  'jobReuseTranslation': 'إعادة استخدام الترجمة',
  'jobReuseSubtitle': 'إعادة استخدام ملف الترجمة',
  'jobConfidence': 'الثقة: {level}',
  'jobOpenPreview': 'فتح المعاينة',
  'onboardingPage1Title':
      'اعثر على أفلام أو مسلسلات واسحب ترجمات جاهزة للترجمة.',
  'onboardingPage1Eyebrow': 'ابحث واجلب',
  'onboardingPage1Description':
      'ابحث عن عنوان، وراجع مصادر الترجمة الإنجليزية المتاحة، وابدأ مسار ترجمة يبدو فوريًا.',
  'onboardingPage1Highlight1': 'فهرس تجريبي حتمي لتطوير موثوق',
  'onboardingPage1Highlight2': 'بطاقات جودة المصدر وشارات الصيغة',
  'onboardingPage1Highlight3': 'مصمم ليستبدل بخادم حقيقي لاحقًا',
  'onboardingPage2Title':
      'ارفع ملفات `.srt` أو `.vtt` عندما تكون الترجمة لديك بالفعل.',
  'onboardingPage2Eyebrow': 'استخدم ملفك الخاص',
  'onboardingPage2Description':
      'استورد ملف الترجمة، وتحقق من الصيغة، وشغّل مسار الترجمة المصقول نفسه دون مغادرة التطبيق.',
  'onboardingPage2Highlight1':
      'تحقق محلي من الملفات مع حالات إعادة محاولة سلسة',
  'onboardingPage2Highlight2': 'إعداد ترجمة متسق بين الرفع والبحث',
  'onboardingPage2Highlight3': 'عاين قبل التصدير حتى لا يبدو شيء غامضًا',
  'onboardingPage3Title': 'اختر اللغات المستهدفة، وعاين الترجمة، وصدّر فورًا.',
  'onboardingPage3Eyebrow': 'ترجم وصدّر',
  'onboardingPage3Description':
      'بدّل بين العرض الأصلي والمترجم والثنائي اللغة، وارجع إلى السجل، وصدّر ملفات ترجمة نظيفة عندما تبدو النتيجة صحيحة.',
  'onboardingPage3Highlight1': 'عناصر معاينة سريعة مع البيانات الوصفية والبحث',
  'onboardingPage3Highlight2': 'يبقي السجل المهام السابقة على بُعد لمسة',
  'onboardingPage3Highlight3': 'مصمم كأداة وسائط احترافية لا كعرض تجريبي',
  'onboardingStart': 'ابدأ الترجمة',
  'onboardingNext': 'التالي',
  'onboardingSkip': 'تخطَّ',
  'onboardingContinue': 'متابعة',
  'onboardingEnterApp': 'ادخل إلى SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'ترجمة ترجمة مدعومة بالذكاء الاصطناعي',
  'splashPreparing': 'جارٍ تجهيز استوديو الترجمة الخاص بك',
  'brandSubtitleCompact': 'ذكاء الترجمة',
  'brandSubtitleFull': 'استوديو ترجمة الترجمة بالذكاء الاصطناعي',
  'comingSoonTitle': 'قريبًا',
  'comingSoonMessage': 'ما زلنا نجهّز هذه الشاشة.',
};
