const Map<String, String> kStringsDe = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Titel suchen',
  'searchMovieOrSeriesTitle': 'Film oder Serie suchen',
  'searchMovieOrSeriesSubtitle':
      'Finde einen Titel, prüfe Untertitelquellen und starte mit wenigen Tippvorgängen einen Übersetzungsauftrag.',
  'searchHintText': 'Suche nach Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Suche im Demo-Katalog nach beliebigen Titeln',
  'searchMockMessage':
      'Probiere Titel wie Inception, Dune, Breaking Bad, Severance oder The Last of Us aus, um den Ablauf der Untertitelquellen zu erkunden.',
  'searchFailedTitle': 'Suche fehlgeschlagen',
  'noTitlesMatchedTitle': 'Keine Treffer',
  'noTitlesMatchedMessage':
      'Wir konnten diesen Titel im Demo-Katalog nicht finden. Versuche eine allgemeinere Suche oder einen der vorgeschlagenen Titel.',
  'searchTrendingTitle': 'Beliebte Suchen',
  'searchLoadingLabel': 'Suche läuft...',
  'searchFoundResults': '{count} Ergebnisse für \'{query}\' gefunden',
  'searchNoResultsFor': 'Keine Ergebnisse für \'{query}\' gefunden',
  'searchTryDifferentKeywords': 'Versuche es mit anderen Suchbegriffen.',
  'retry': 'Erneut versuchen',
  'retryTranslation': 'Übersetzung erneut starten',
  'uploadSubtitleTitle': 'Untertitel hochladen',
  'uploadIntroTitle': 'Eigene Untertiteldatei verwenden',
  'uploadIntroSubtitle':
      'Importiere eine englische `.srt`- oder `.vtt`-Datei, lasse sie vom Backend prüfen und parsen und fahre dann mit der Übersetzungseinrichtung fort.',
  'uploadChooseFile': 'Untertiteldatei auswählen',
  'uploadSupportedFormatsTitle': 'Unterstützte Formate',
  'uploadSupportedFormatsSubtitle':
      'Englische Untertiteldateien im Format `.srt` und `.vtt`',
  'uploadOpeningPicker': 'Dateiauswahl wird geöffnet...',
  'uploadChooseFileShort': 'Datei wählen',
  'uploadPickSubtitle': 'Untertiteldatei wählen',
  'uploadPickedFile': 'Untertiteldatei ausgewählt',
  'uploadUseDemoFile': 'Demo-Datei verwenden',
  'uploadFailedTitle': 'Dateiimport fehlgeschlagen',
  'uploadFailedMessage':
      'Diese Untertiteldatei konnte nicht gelesen werden. Versuche eine andere Datei oder einen kleineren Export.',
  'uploadFailedFallback': 'Bitte versuche eine andere Untertiteldatei.',
  'tryAgain': 'Noch einmal versuchen',
  'uploadMetadataTitle': 'Untertiteldetails',
  'uploadReadyTitle': 'Bereit zur Übersetzung',
  'uploadLineCount': '{lineCount} Zeilen',
  'uploadEnglishSource': 'Englische Quelle',
  'uploadContinueSetup': 'Weiter zur Übersetzungseinrichtung',
  'translateSetupTitle': 'Übersetzung einrichten',
  'translateSetupSubtitle':
      'Wähle die Zielsprache, prüfe die Untertitelquelle und starte dann den Übersetzungsauftrag im Backend.',
  'translateSetupSourceTitle': 'Quelluntertitel',
  'translateSetupLanguageTitle': 'Übersetzen nach',
  'translateSetupOptionsTitle': 'Optionen',
  'translateSetupSelectLanguage': 'Sprache auswählen',
  'translateSetupReadyTitle': 'KI-Übersetzung bereit',
  'translateSetupReadyBody':
      'Unser Übersetzungsablauf überträgt diesen Untertitel in {language}, mit erhaltenem Timing und sauberer Cue-Struktur.',
  'translateSetupPreserveTiming': 'Timing beibehalten',
  'translateSetupPreserveTimingBody':
      'Behält die ursprünglichen Untertitelzeiten in Übereinstimmung mit der Quelldatei bei.',
  'translateSetupAutoDetect': 'Format automatisch erkennen',
  'translateSetupAutoDetectBody':
      'Wählt automatisch die passende Ausgabestruktur für Untertitel.',
  'subtitleSourceFormatLabel': '{format}-Untertitelquelle',
  'targetLanguage': 'Zielsprache',
  'startTranslation': 'Übersetzung starten',
  'translationProgressTitle': 'Übersetzungsfortschritt',
  'translationProgressHeadline': 'KI-Untertitelübersetzung läuft',
  'translationFailedTitle': 'Übersetzung konnte nicht abgeschlossen werden',
  'translationFailedMessage': 'Etwas ist schiefgelaufen.',
  'translationStageQueued': 'Zur Übersetzung eingereiht',
  'translationStageIdle': 'Warten auf eine Übersetzungsanfrage',
  'translationStagePreparing': 'Untertitelpaket wird vorbereitet',
  'translationStageAligning':
      'Zeitstempel und Szenenkontext werden abgeglichen',
  'translationStageGenerating': 'Untertitelübersetzung wird erstellt',
  'translationStageReadability': 'Lesbarkeitsprüfung wird angewendet',
  'translationStageReady': 'Übersetzung bereit',
  'translationResultCompleteTitle': 'Übersetzung abgeschlossen',
  'translationResultCompleteSubtitle':
      'Dein Untertitel ist zur Vorschau oder zum Download bereit.',
  'translationResultDetailsTitle': 'Übersetzungsdetails',
  'translationResultMediaLabel': 'Medientitel',
  'translationResultSourceLabel': 'Ausgangssprache',
  'translationResultTargetLabel': 'Zielsprache',
  'translationResultMethodAi': 'Mit KI übersetzt',
  'translationResultMetricsTitle': 'Qualitätsmetriken',
  'translationResultConfidenceLabel': 'Übersetzungssicherheit',
  'translationResultTimingLabel': 'Timing-Genauigkeit',
  'translationResultTimingPreserved': 'Timing beibehalten',
  'translationResultProcessedIn': 'Verarbeitet in {duration}',
  'translationResultWarning':
      'Einige Fachbegriffe profitieren womöglich noch von einer kurzen menschlichen Kontextprüfung.',
  'translationResultPreviewCta': 'Untertitel ansehen',
  'translationResultDownloadCta': 'Untertitel herunterladen',
  'translationResultHomeCta': 'Zurück zur Startseite',
  'translationPreviewTitle': 'Übersetzungsvorschau',
  'translationPreviewHeader': 'Übersetzte Untertitel prüfen',
  'translationPreviewSubtitle':
      'Suche innerhalb der Cues, wechsle den Vorschaumodus und exportiere erst, wenn die Übersetzung stimmt.',
  'translationPreviewSearchHint': 'Untertitelzeilen durchsuchen',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Übersetzt',
  'previewModeBilingual': 'Zweisprachig',
  'previewNotReadyTitle': 'Vorschau-Cues sind noch nicht verfügbar',
  'previewNotReadyMessage':
      'Die Übersetzung ist fertig, aber das Backend hat noch keine Vorschau-Cues zurückgegeben. Lade diesen Bildschirm in einem Moment erneut.',
  'previewNoMatchesTitle': 'Keine Untertitelzeilen gefunden',
  'previewNoMatchesMessage':
      'Versuche einen anderen Suchbegriff oder entferne den Filter, um die komplette Übersetzung zu prüfen.',
  'previewFailedTitle': 'Vorschau konnte nicht geladen werden',
  'exportingLabel': 'Exportiere...',
  'exportSubtitleLabel': 'Übersetzten Untertitel exportieren',
  'exportedSnack': '{fileName} nach {path} exportiert',
  'exportFailedSnack': 'Export fehlgeschlagen: {error}',
  'metadataFormat': 'Format',
  'metadataLines': 'Zeilen',
  'metadataLanguages': 'Sprachen',
  'metadataEstimatedDuration': 'Geschätzte Dauer',
  'subtitleSourcesTitle': 'Englische Untertitelquellen',
  'subtitleSourcesSubtitle':
      'Wähle eine Untertitelquelle für {title}{target} und danach im nächsten Schritt die Zielsprache.',
  'subtitleSourcesBannerTitle': 'KI-Übersetzung verfügbar',
  'subtitleSourcesBannerMessage':
      'Wähle eine Untertitelquelle und fahre mit einer ausgereiften Übersetzungseinrichtung fort, die auf Untertitel-Timing abgestimmt ist.',
  'subtitleSourcesFailedTitle':
      'Untertitelquellen konnten nicht geladen werden',
  'seriesSeasonsTitle': 'Staffel auswählen',
  'seriesSeasonsSubtitle':
      'Wähle eine Staffel von {title}, um verfügbare Folgen zu sehen.',
  'seriesSeasonLabel': 'Staffel {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} Folgen{year}',
  'seriesEpisodesTitle': 'Staffel {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} Folgen{year}',
  'seriesEpisodeLabel': 'Folge {episodeNumber}',
  'seriesEpisodeMeta': 'Ca. {runtime} Min.',
  'historyTitle': 'Übersetzungsverlauf',
  'historySubtitle':
      'Öffne frühere Untertitelaufträge erneut, prüfe die Vorschau noch einmal oder exportiere sie später.',
  'historyEmptyTitle': 'Der Verlauf ist leer',
  'historyEmptyMessage':
      'Deine übersetzten Untertitelaufträge erscheinen hier, sobald du einen Such- oder Upload-Ablauf abgeschlossen hast.',
  'historyFailedTitle': 'Verlauf konnte nicht geladen werden',
  'historyCountLabel': '{count} Übersetzungen',
  'historyFilterAll': 'Alle',
  'historyFilterMovies': 'Filme',
  'historyFilterSeries': 'Serien',
  'historyFilterCompleted': 'Abgeschlossen',
  'historyFilterAiTranslated': 'Mit KI übersetzt',
  'historyFilterFailed': 'Fehlgeschlagen',
  'historyFilterReused': 'Wiederverwendet',
  'historyFailedItemMessage':
      'Übersetzung fehlgeschlagen. Tippe, um neu zu starten.',
  'homeRecentJobsTitle': 'Letzte Aufträge',
  'homeRecentJobsSubtitle':
      'Öffne deine neuesten Untertitel-Sitzungen erneut, ohne von vorn zu beginnen.',
  'homeNoRecentTitle': 'Noch keine letzten Aufträge',
  'homeNoRecentMessage':
      'Starte mit einer Filmsuche oder lade eine Untertiteldatei hoch, dann erscheinen deine letzten Übersetzungen hier.',
  'homeFailedRecentTitle': 'Letzte Aufträge konnten nicht geladen werden',
  'homeWelcomeTitle': 'Willkommen zurück',
  'homeWelcomeSubtitle': 'Untertitel finden und übersetzen',
  'homeSearchPlaceholder': 'Filme oder Serien suchen...',
  'homeQuickSearch': 'Suchen',
  'homeQuickHistory': 'Verlauf',
  'homeQuickUpload': 'Hochladen',
  'homeViewAll': 'Alle anzeigen',
  'homeTrendingNow': 'Gerade im Trend',
  'homeTrustTitle': 'Warum Teams darauf vertrauen',
  'homeTrustSubtitle':
      'Heute noch simuliert, aber schon wie ein echtes Produkt strukturiert.',
  'homeFutureTitle': 'Zukunftssichere Repositories',
  'homeFutureSubtitle':
      'Austauschbare Mock-Repositories schützen den UI-Code vor Änderungen im Backend.',
  'homePreviewTitle': 'Vorschau-orientierter Übersetzungsablauf',
  'homePreviewSubtitle':
      'Prüfe Ergebnisse vor dem Export in der Original-, übersetzten oder zweisprachigen Ansicht.',
  'homeStatesTitle': 'Saubere Zustände inklusive',
  'homeStatesSubtitle':
      'Lade-, Leer-, Retry-, Validierungs- und Mock-Offline-Szenarien gehören von Anfang an zur UX.',
  'navHome': 'Start',
  'navHistory': 'Verlauf',
  'navSettings': 'Einstellungen',
  'heroTitle': 'Untertitel schneller übersetzen',
  'heroSubtitle':
      'Durchsuche Film- und Serienkataloge, wähle Quellen und exportiere in Minuten sauber ausgearbeitete Übersetzungen.',
  'heroBadge': 'Premium-Untertitel-Workflow',
  'heroHeadline':
      'Übersetze Film- und Serienuntertitel mit einem Workflow auf Studio-Niveau.',
  'heroBody':
      'Wähle zwischen einem durchsuchbaren Titelkatalog oder direktem Dateiupload und sieh dir ausgearbeitete Untertitel in wenigen Minuten an oder exportiere sie.',
  'heroSearchCta': 'Film / Serie suchen',
  'heroUploadCta': 'Untertitel hochladen',
  'heroStatPathsTitle': '2 Wege',
  'heroStatPathsValue': 'Suchen oder hochladen',
  'heroStatLanguagesTitle': '10 Sprachen',
  'heroStatLanguagesValue': 'Bereit zur Vorschau',
  'heroStatMockTitle': 'Mock-APIs',
  'heroStatMockValue': 'Backend-fähige Schnittstelle',
  'settingsTitle': 'Einstellungen',
  'settingsSubtitle': 'Verwalte deine Einstellungen',
  'settingsProfileName': 'SubFlix-Nutzer',
  'settingsProfileTier': 'Premium-Mitglied',
  'settingsLanguageLabel': 'Bevorzugte Zielsprache',
  'settingsThemeLabel': 'Darstellung',
  'themeSystem': 'System',
  'themeDark': 'Dunkel',
  'themeLight': 'Hell',
  'settingsPremiumTitle': 'Premium-Platzhalter',
  'settingsPremiumSubtitle':
      'Später können wir hier Abos, Abrechnung und Cloud-Projektsynchronisierung anbinden.',
  'settingsNotificationsTitle': 'Benachrichtigungen',
  'settingsNotificationsSubtitle': 'Benachrichtigungseinstellungen verwalten',
  'settingsHelpCenterTitle': 'Hilfecenter',
  'settingsContactTitle': 'Kontakt',
  'settingsSupportTitle': 'Support-Platzhalter',
  'settingsSupportSubtitle': 'Demo-Seite für Hilfe und Kontakt',
  'settingsPrivacyTitle': 'Datenschutzrichtlinie',
  'settingsPrivacySubtitle': 'Demo-Inhalt zum Datenschutz',
  'settingsTermsTitle': 'Nutzungsbedingungen',
  'settingsTermsSubtitle': 'Demo-Inhalt zu den Bedingungen',
  'settingsMaintenanceTitle': 'Wartung',
  'settingsMaintenanceSubtitle':
      'Lösche backendverwaltete Übersetzungsaufträge für dieses Gerät und starte mit leerem Verlauf.',
  'settingsHistoryClearedSnack':
      'Übersetzungsverlauf für dieses Gerät gelöscht',
  'settingsAboutTitle': 'Über SubFlix',
  'settingsVersion': 'Version {version}',
  'settingsClearCache': 'Cache leeren',
  'settingsCacheCleared': 'Cache geleert',
  'settingsFailedTitle': 'Einstellungen konnten nicht geladen werden',
  'legalPlaceholderBody':
      'Diese Seite ist in der Demo-App nur ein Platzhalter. Verbinde sie mit deinen rechtlichen Inhalten für die Produktion.',
  'legalTitlePrivacy': 'Datenschutzrichtlinie',
  'legalTitleTerms': 'Nutzungsbedingungen',
  'legalTitleSupport': 'Support',
  'legalTitleAbout': 'Über SubFlix',
  'legalBodyPrivacy':
      'SubFlix speichert derzeit nur Demo-Einstellungen und Übersetzungsverlauf lokal auf dem Gerät. Eine spätere Backend-Integration kann das durch authentifizierten Speicher, Audit-Trails und serverseitig verwaltete Aufbewahrungsrichtlinien ersetzen.',
  'legalBodyTerms':
      'Dieser Demo-Build dient dazu, Produktabläufe, UI-Zustände und Architekturgrenzen zu erproben. Wenn später ein produktives NestJS- und Postgres-Backend angebunden wird, kann die rechtliche Basis um echte Nutzungsbedingungen und Formulierungen zur Datenverarbeitung erweitert werden.',
  'legalBodySupport':
      'Der Support ist derzeit nur ein Platzhalter. In einer Produktionsversion kann dieser Bereich E-Mail, Problemberichte und Hilfe für Premium-Konten anbinden, ohne die App-Struktur zu verändern.',
  'legalBodyAbout':
      'SubFlix ist ein Flutter-Client im Premium-Stil für KI-Untertitelübersetzung. Dieser Build verwendet Mock-Repositories, künstliche Latenz und lokale Speicherung, damit UI und Architektur reifen können, bevor ein echtes Backend angeschlossen wird.',
  'routeMissingSubtitleSourcesTitle': 'Untertitelquellen',
  'routeMissingSubtitleSourcesMessage':
      'Es konnte nicht bestimmt werden, für welchen Titel Untertitelquellen geladen werden sollen. Starte die Suche erneut.',
  'routeMissingSeriesSeasonsTitle': 'Serienstaffeln',
  'routeMissingSeriesSeasonsMessage':
      'Es konnte nicht bestimmt werden, welche Serie geladen werden soll. Starte die Suche erneut.',
  'routeMissingSeasonEpisodesTitle': 'Staffelfolgen',
  'routeMissingSeasonEpisodesMessage':
      'Es konnte nicht bestimmt werden, welche Staffel geladen werden soll. Starte die Suche erneut.',
  'routeMissingTranslationSetupTitle': 'Übersetzungseinrichtung',
  'routeMissingTranslationSetupMessage':
      'Bevor der Bildschirm für die Übersetzungseinrichtung geöffnet werden kann, ist eine Untertitelquelle erforderlich.',
  'routeMissingTranslationProgressTitle': 'Übersetzungsfortschritt',
  'routeMissingTranslationProgressMessage':
      'Es wurde keine Übersetzungsanfrage übergeben. Starte eine neue Übersetzung aus Suche oder Upload.',
  'searchResultPopularity': 'Beliebtheit {score}',
  'subtitleSourceLines': '{lineCount} Zeilen',
  'subtitleSourceDownloads': '{downloads} Downloads',
  'subtitleSourceRating': 'Bewertung {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Film',
  'mediaTypeSeries': 'Serie',
  'jobReuseTranslation': 'Übersetzung wiederverwenden',
  'jobReuseSubtitle': 'Untertitel wiederverwenden',
  'jobConfidence': 'Sicherheit: {level}',
  'jobOpenPreview': 'Vorschau öffnen',
  'onboardingPage1Title':
      'Finde Filme oder Serien und hole sofort übersetzbare Untertitel.',
  'onboardingPage1Eyebrow': 'Suchen und laden',
  'onboardingPage1Description':
      'Suche einen Titel, prüfe die verfügbaren englischen Untertitelquellen und starte einen Übersetzungsablauf, der sich sofort anfühlt.',
  'onboardingPage1Highlight1':
      'Deterministischer Demo-Katalog für verlässliche Entwicklung',
  'onboardingPage1Highlight2':
      'Qualitätslabels und Format-Badges für Untertitelquellen',
  'onboardingPage1Highlight3':
      'So gebaut, dass später ein echtes Backend angeschlossen werden kann',
  'onboardingPage2Title':
      'Lade `.srt`- oder `.vtt`-Dateien hoch, wenn du das Skript schon hast.',
  'onboardingPage2Eyebrow': 'Eigene Datei verwenden',
  'onboardingPage2Description':
      'Importiere deine Untertiteldatei, prüfe das Format und nutze dieselbe ausgereifte Übersetzungspipeline, ohne die App zu verlassen.',
  'onboardingPage2Highlight1': 'Lokale Dateiprüfung und saubere Retry-Zustände',
  'onboardingPage2Highlight2':
      'Konsistente Übersetzungseinrichtung für Upload und Suche',
  'onboardingPage2Highlight3':
      'Vor dem Export ansehen, damit nichts undurchsichtig wirkt',
  'onboardingPage3Title':
      'Wähle Zielsprachen, prüfe Untertitel und exportiere sofort.',
  'onboardingPage3Eyebrow': 'Übersetzen und exportieren',
  'onboardingPage3Description':
      'Wechsle zwischen Original-, Übersetzungs- und zweisprachiger Ansicht, gehe in den Verlauf zurück und exportiere saubere Untertiteldateien, sobald das Ergebnis passt.',
  'onboardingPage3Highlight1':
      'Schnelle Vorschau-Steuerung mit Metadaten und Suche',
  'onboardingPage3Highlight2':
      'Der Verlauf hält frühere Aufträge nur einen Tipp entfernt',
  'onboardingPage3Highlight3':
      'Gestaltet wie ein Premium-Medienwerkzeug, nicht wie eine Demo',
  'onboardingStart': 'Übersetzung starten',
  'onboardingNext': 'Weiter',
  'onboardingSkip': 'Überspringen',
  'onboardingContinue': 'Fortfahren',
  'onboardingEnterApp': 'SubFlix öffnen',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'KI-gestützte Untertitelübersetzung',
  'splashPreparing': 'Dein Untertitelstudio wird vorbereitet',
  'brandSubtitleCompact': 'Untertitel-Intelligenz',
  'brandSubtitleFull': 'KI-Untertitelübersetzungsstudio',
  'comingSoonTitle': 'Demnächst',
  'comingSoonMessage': 'Dieser Bildschirm wird noch vorbereitet.',
};
