const Map<String, String> kStringsFa = <String, String>{
  'appTitle': "SubFlix",
  'searchTitles': "جستجوی عنوان‌ها",
  'searchMovieOrSeriesTitle': "جستجوی فیلم یا سریال",
  'searchMovieOrSeriesSubtitle':
      "یک عنوان پیدا کن، منابع زیرنویس را بررسی کن و فقط با چند لمس ترجمه را شروع کن.",
  'searchHintText': "مثلاً Dune یا Breaking Bad یا Severance را جستجو کن...",
  'searchMockTitle': "هر چیزی را در کاتالوگ آزمایشی جستجو کن",
  'searchMockMessage':
      "برای دیدن جریان انتخاب منبع زیرنویس، عنوان‌هایی مثل Inception، Dune، Breaking Bad، Severance یا The Last of Us را امتحان کن.",
  'searchFailedTitle': "جستجو ناموفق بود",
  'noTitlesMatchedTitle': "نتیجه‌ای پیدا نشد",
  'noTitlesMatchedMessage':
      "نتوانستیم این عنوان را در کاتالوگ آزمایشی پیدا کنیم. یک جستجوی کلی‌تر یا یکی از عنوان‌های پیشنهادی را امتحان کن.",
  'searchTrendingTitle': "جستجوهای پرطرفدار",
  'searchLoadingLabel': "در حال جستجو...",
  'searchFoundResults': "{count} نتیجه برای \"{query}\" پیدا شد",
  'searchNoResultsFor': "نتیجه‌ای برای \"{query}\" پیدا نشد",
  'searchTryDifferentKeywords': "با کلمات کلیدی دیگری جستجو کن.",
  'retry': "تلاش دوباره",
  'retryTranslation': "ترجمه دوباره",
  'uploadSubtitleTitle': "آپلود زیرنویس",
  'uploadIntroTitle': "فایل زیرنویس خودت را بیاور",
  'uploadIntroSubtitle':
      "یک فایل انگلیسی `.srt` یا `.vtt` وارد کن، بگذار بک‌اند آن را بررسی و پردازش کند، سپس وارد مرحله تنظیم ترجمه شو.",
  'uploadChooseFile': "انتخاب فایل زیرنویس",
  'uploadSupportedFormatsTitle': "فرمت‌های پشتیبانی‌شده",
  'uploadSupportedFormatsSubtitle': "فایل‌های زیرنویس انگلیسی `.srt` و `.vtt`",
  'uploadOpeningPicker': "در حال باز کردن انتخاب‌گر فایل...",
  'uploadChooseFileShort': "انتخاب فایل",
  'uploadPickSubtitle': "فایل زیرنویس را انتخاب کن",
  'uploadPickedFile': "فایل زیرنویس انتخاب شد",
  'uploadUseDemoFile': "استفاده از فایل نمونه",
  'uploadFailedTitle': "وارد کردن فایل ناموفق بود",
  'uploadFailedMessage':
      "نتوانستیم این فایل زیرنویس را بخوانیم. یک فایل دیگر یا خروجی سبک‌تر را امتحان کن.",
  'uploadFailedFallback': "لطفاً یک فایل زیرنویس دیگر را امتحان کن.",
  'tryAgain': "دوباره امتحان کن",
  'uploadMetadataTitle': "جزئیات زیرنویس",
  'uploadReadyTitle': "آماده ترجمه",
  'uploadLineCount': "{lineCount} خط",
  'uploadEnglishSource': "منبع انگلیسی",
  'uploadContinueSetup': "ادامه به تنظیمات ترجمه",
  'translateSetupTitle': "تنظیمات ترجمه",
  'translateSetupSubtitle':
      "زبان مقصد را انتخاب کن، منبع زیرنویس را بررسی کن و بعد کار ترجمه را در بک‌اند شروع کن.",
  'translateSetupSourceTitle': "زیرنویس مبدأ",
  'translateSetupLanguageTitle': "ترجمه به",
  'translateSetupOptionsTitle': "گزینه‌ها",
  'translateSetupSelectLanguage': "انتخاب زبان",
  'translateSetupReadyTitle': "ترجمه با هوش مصنوعی آماده است",
  'translateSetupReadyBody':
      "جریان ترجمه ما این زیرنویس را با حفظ زمان‌بندی و ساختار تمیز cueها به {language} تبدیل می‌کند.",
  'translateSetupPreserveTiming': "حفظ زمان‌بندی",
  'translateSetupPreserveTimingBody':
      "زمان‌بندی اصلی زیرنویس را با فایل مبدأ هماهنگ نگه می‌دارد.",
  'translateSetupAutoDetect': "تشخیص خودکار فرمت",
  'translateSetupAutoDetectBody':
      "ساختار مناسب خروجی زیرنویس را به‌صورت خودکار انتخاب می‌کند.",
  'subtitleSourceFormatLabel': "منبع زیرنویس {format}",
  'targetLanguage': "زبان مقصد",
  'startTranslation': "شروع ترجمه",
  'translationProgressTitle': "روند ترجمه",
  'translationProgressHeadline': "ترجمه زیرنویس با هوش مصنوعی در حال انجام است",
  'translationFailedTitle': "ترجمه کامل نشد",
  'translationFailedMessage': "مشکلی پیش آمد.",
  'translationStageQueued': "در صف ترجمه",
  'translationStageIdle': "در انتظار درخواست ترجمه",
  'translationStagePreparing': "در حال آماده‌سازی بسته زیرنویس",
  'translationStageAligning': "در حال هماهنگ‌سازی زمان‌ها و فضای صحنه",
  'translationStageGenerating': "در حال تولید ترجمه زیرنویس",
  'translationStageReadability': "در حال اعمال بازبینی خوانایی",
  'translationStageReady': "ترجمه آماده است",
  'translationResultCompleteTitle': "ترجمه کامل شد",
  'translationResultCompleteSubtitle':
      "زیرنویس تو برای پیش‌نمایش یا دانلود آماده است.",
  'translationResultDetailsTitle': "جزئیات ترجمه",
  'translationResultMediaLabel': "عنوان اثر",
  'translationResultSourceLabel': "زبان مبدأ",
  'translationResultTargetLabel': "زبان مقصد",
  'translationResultMethodAi': "ترجمه‌شده با هوش مصنوعی",
  'translationResultMetricsTitle': "شاخص‌های کیفیت",
  'translationResultConfidenceLabel': "میزان اطمینان ترجمه",
  'translationResultTimingLabel': "دقت زمان‌بندی",
  'translationResultTimingPreserved': "زمان‌بندی حفظ شده",
  'translationResultProcessedIn': "در {duration} پردازش شد",
  'translationResultWarning':
      "بعضی اصطلاحات تخصصی شاید هنوز برای درک بهتر بافت جمله به یک بازبینی انسانی سریع نیاز داشته باشند.",
  'translationResultPreviewCta': "پیش‌نمایش زیرنویس",
  'translationResultDownloadCta': "دانلود زیرنویس",
  'translationResultHomeCta': "بازگشت به خانه",
  'translationPreviewTitle': "پیش‌نمایش ترجمه",
  'translationPreviewHeader': "زیرنویس‌های ترجمه‌شده را بررسی کن",
  'translationPreviewSubtitle':
      "در cueها جستجو کن، حالت نمایش را عوض کن و وقتی نتیجه درست بود خروجی بگیر.",
  'translationPreviewSearchHint': "جستجو در خطوط زیرنویس",
  'previewModeOriginal': "اصل",
  'previewModeTranslated': "ترجمه‌شده",
  'previewModeBilingual': "دوزبانه",
  'previewNotReadyTitle': "cueهای پیش‌نمایش هنوز آماده نیستند",
  'previewNotReadyMessage':
      "ترجمه تمام شده، اما بک‌اند هنوز cueهای پیش‌نمایش را برنگردانده است. کمی بعد دوباره این صفحه را بارگذاری کن.",
  'previewNoMatchesTitle': "هیچ خطی پیدا نشد",
  'previewNoMatchesMessage':
      "یک عبارت دیگر را جستجو کن یا فیلتر را پاک کن تا کل ترجمه را ببینی.",
  'previewFailedTitle': "بارگذاری پیش‌نمایش ناموفق بود",
  'exportingLabel': "در حال خروجی گرفتن...",
  'exportSubtitleLabel': "خروجی گرفتن از زیرنویس ترجمه‌شده",
  'exportedSnack': "{fileName} در {path} ذخیره شد",
  'exportFailedSnack': "خروجی ناموفق بود: {error}",
  'metadataFormat': "فرمت",
  'metadataLines': "خطوط",
  'metadataLanguages': "زبان‌ها",
  'metadataEstimatedDuration': "مدت زمان تقریبی",
  'subtitleSourcesTitle': "منابع زیرنویس انگلیسی",
  'subtitleSourcesSubtitle':
      "برای {title}{target} یک منبع زیرنویس انتخاب کن و در مرحله بعد زبان مقصد را مشخص کن.",
  'subtitleSourcesBannerTitle': "ترجمه با هوش مصنوعی در دسترس است",
  'subtitleSourcesBannerMessage':
      "یک منبع زیرنویس انتخاب کن و وارد تنظیمات ترجمه‌ای شو که برای زمان‌بندی زیرنویس بهینه شده است.",
  'subtitleSourcesFailedTitle': "بارگذاری منابع زیرنویس ممکن نشد",
  'seriesSeasonsTitle': "یک فصل انتخاب کن",
  'seriesSeasonsSubtitle':
      "یک فصل از {title} را انتخاب کن تا قسمت‌های موجود را ببینی.",
  'seriesSeasonLabel': "فصل {seasonNumber}",
  'seriesSeasonMeta': "{episodeCount} قسمت{year}",
  'seriesEpisodesTitle': "فصل {seasonNumber}",
  'seriesEpisodesSubtitle': "{episodeCount} قسمت{year}",
  'seriesEpisodeLabel': "قسمت {episodeNumber}",
  'seriesEpisodeMeta': "حدود {runtime} دقیقه",
  'historyTitle': "تاریخچه ترجمه‌ها",
  'historySubtitle':
      "کارهای قبلی را دوباره باز کن، پیش‌نمایش را دوباره ببین یا بعداً خروجی بگیر.",
  'historyEmptyTitle': "تاریخچه خالی است",
  'historyEmptyMessage':
      "بعد از کامل کردن فرایند جستجو یا آپلود، ترجمه‌های انجام‌شده اینجا ظاهر می‌شوند.",
  'historyFailedTitle': "بارگذاری تاریخچه ممکن نشد",
  'historyCountLabel': "{count} ترجمه",
  'historyFilterAll': "همه",
  'historyFilterMovies': "فیلم‌ها",
  'historyFilterSeries': "سریال‌ها",
  'historyFilterCompleted': "تکمیل‌شده",
  'historyFilterAiTranslated': "ترجمه‌شده با هوش مصنوعی",
  'historyFilterFailed': "ناموفق",
  'historyFilterReused': "استفاده‌شده دوباره",
  'historyFailedItemMessage': "ترجمه ناموفق بود. برای شروع دوباره لمس کن.",
  'homeRecentJobsTitle': "کارهای اخیر",
  'homeRecentJobsSubtitle':
      "آخرین جلسه‌های ترجمه‌ات را بدون شروع از صفر دوباره باز کن.",
  'homeNoRecentTitle': "هنوز کاری در بخش اخیرها نیست",
  'homeNoRecentMessage':
      "با جستجوی فیلم یا آپلود فایل زیرنویس شروع کن تا ترجمه‌های اخیرت اینجا دیده شوند.",
  'homeFailedRecentTitle': "بارگذاری کارهای اخیر ممکن نشد",
  'homeWelcomeTitle': "خوش برگشتی",
  'homeWelcomeSubtitle': "زیرنویس پیدا کن و ترجمه کن",
  'homeSearchPlaceholder': "جستجوی فیلم یا سریال...",
  'homeQuickSearch': "جستجو",
  'homeQuickHistory': "تاریخچه",
  'homeQuickUpload': "آپلود",
  'homeViewAll': "مشاهده همه",
  'homeTrendingNow': "ترندهای فعلی",
  'homeTrustTitle': "چرا تیم‌ها به آن اعتماد می‌کنند",
  'homeTrustSubtitle':
      "فعلاً آزمایشی است، اما ساختارش مثل یک محصول واقعی و قابل انتشار طراحی شده.",
  'homeFutureTitle': "ریپازیتوری‌های آماده آینده",
  'homeFutureSubtitle':
      "ریپازیتوری‌های ماک قابل تعویض باعث می‌شوند کد UI از تغییرات بک‌اند در امان بماند.",
  'homePreviewTitle': "جریان ترجمه با محوریت پیش‌نمایش",
  'homePreviewSubtitle':
      "قبل از خروجی گرفتن، نتیجه را در حالت اصلی، ترجمه‌شده یا دوزبانه بررسی کن.",
  'homeStatesTitle': "همه وضعیت‌های لازم در نظر گرفته شده",
  'homeStatesSubtitle':
      "لودینگ، حالت خالی، تلاش دوباره، اعتبارسنجی و سناریوهای آفلاین آزمایشی از همان روز اول جزئی از UX هستند.",
  'navHome': "خانه",
  'navHistory': "تاریخچه",
  'navSettings': "تنظیمات",
  'heroTitle': "زیرنویس‌ها را سریع‌تر ترجمه کن",
  'heroSubtitle':
      "در کاتالوگ فیلم و سریال جستجو کن، منبع انتخاب کن و در چند دقیقه خروجی تمیز بگیر.",
  'heroBadge': "جریان حرفه‌ای زیرنویس",
  'heroHeadline': "زیرنویس فیلم و سریال را با یک جریان در حد استودیو ترجمه کن.",
  'heroBody':
      "بین کاتالوگ قابل جستجو یا آپلود مستقیم فایل یکی را انتخاب کن، سپس در چند دقیقه پیش‌نمایش بگیر و زیرنویس نهایی را خروجی بگیر.",
  'heroSearchCta': "جستجوی فیلم / سریال",
  'heroUploadCta': "آپلود زیرنویس",
  'heroStatPathsTitle': "۲ مسیر",
  'heroStatPathsValue': "جستجو یا آپلود",
  'heroStatLanguagesTitle': "۱۰ زبان",
  'heroStatLanguagesValue': "آماده پیش‌نمایش",
  'heroStatMockTitle': "APIهای ماک",
  'heroStatMockValue': "آماده اتصال به بک‌اند",
  'settingsTitle': "تنظیمات",
  'settingsSubtitle': "ترجیحاتت را مدیریت کن",
  'settingsProfileName': "کاربر SubFlix",
  'settingsProfileTier': "عضو پریمیوم",
  'settingsLanguageLabel': "زبان مقصد ترجیحی",
  'settingsThemeLabel': "ظاهر",
  'themeSystem': "سیستم",
  'themeDark': "تیره",
  'themeLight': "روشن",
  'settingsPremiumTitle': "بخش پریمیوم آزمایشی",
  'settingsPremiumSubtitle':
      "بعداً می‌توانیم اشتراک‌ها، پرداخت و همگام‌سازی پروژه ابری را اینجا وصل کنیم.",
  'settingsNotificationsTitle': "اعلان‌ها",
  'settingsNotificationsSubtitle': "تنظیمات اعلان‌ها را مدیریت کن",
  'settingsHelpCenterTitle': "مرکز راهنما",
  'settingsContactTitle': "تماس با ما",
  'settingsSupportTitle': "بخش پشتیبانی آزمایشی",
  'settingsSupportSubtitle': "صفحه نمونه برای راهنما و تماس",
  'settingsPrivacyTitle': "حریم خصوصی",
  'settingsPrivacySubtitle': "محتوای آزمایشی حریم خصوصی",
  'settingsTermsTitle': "شرایط استفاده",
  'settingsTermsSubtitle': "محتوای آزمایشی شرایط استفاده",
  'settingsMaintenanceTitle': "نگه‌داری",
  'settingsMaintenanceSubtitle':
      "کارهای ترجمه وابسته به بک‌اند را برای این دستگاه پاک کن و با یک تاریخچه خالی شروع کن.",
  'settingsHistoryClearedSnack': "تاریخچه ترجمه برای این دستگاه پاک شد",
  'settingsAboutTitle': "درباره SubFlix",
  'settingsVersion': "نسخه {version}",
  'settingsClearCache': "پاک کردن کش",
  'settingsCacheCleared': "کش پاک شد",
  'settingsFailedTitle': "بارگذاری تنظیمات ناموفق بود",
  'legalPlaceholderBody':
      "این صفحه در نسخه دمو فقط یک جای‌نگهدار است. آن را به محتوای حقوقی واقعی محصولت وصل کن.",
  'legalTitlePrivacy': "حریم خصوصی",
  'legalTitleTerms': "شرایط استفاده",
  'legalTitleSupport': "پشتیبانی",
  'legalTitleAbout': "درباره SubFlix",
  'legalBodyPrivacy':
      "SubFlix فعلاً فقط ترجیحات آزمایشی و تاریخچه ترجمه را با ذخیره‌سازی محلی روی دستگاه نگه می‌دارد. در آینده می‌توان این بخش را با یک بک‌اند واقعی به ذخیره‌سازی احراز هویت‌شده، مسیرهای ممیزی و سیاست‌های نگه‌داری سمت سرور ارتقا داد.",
  'legalBodyTerms':
      "این نسخه آزمایشی برای سنجش جریان‌های محصول، وضعیت‌های رابط کاربری و مرزهای معماری ساخته شده است. وقتی بعداً یک بک‌اند واقعی مبتنی بر NestJS و Postgres متصل شود، بخش حقوقی هم می‌تواند با شرایط واقعی سرویس و متن‌های مربوط به پردازش داده گسترش پیدا کند.",
  'legalBodySupport':
      "بخش پشتیبانی فعلاً فقط جای‌نگهدار است. در نسخه واقعی، این قسمت می‌تواند بدون تغییر در ساختار اپ به ایمیل، گزارش مشکل و پشتیبانی حساب‌های پریمیوم متصل شود.",
  'legalBodyAbout':
      "SubFlix یک کلاینت Flutter با حس‌وحال پریمیوم برای ترجمه زیرنویس با هوش مصنوعی است. این بیلد از ریپازیتوری‌های ماک، تأخیر مصنوعی و ذخیره‌سازی محلی استفاده می‌کند تا قبل از اتصال بک‌اند واقعی، UI و معماری به بلوغ برسند.",
  'routeMissingSubtitleSourcesTitle': "منابع زیرنویس",
  'routeMissingSubtitleSourcesMessage':
      "نتوانستیم تشخیص دهیم منابع زیرنویس برای کدام عنوان باید بارگذاری شوند. دوباره از جستجو شروع کن.",
  'routeMissingSeriesSeasonsTitle': "فصل‌های سریال",
  'routeMissingSeriesSeasonsMessage':
      "نتوانستیم تشخیص دهیم کدام سریال باید بارگذاری شود. دوباره از جستجو شروع کن.",
  'routeMissingSeasonEpisodesTitle': "قسمت‌های فصل",
  'routeMissingSeasonEpisodesMessage':
      "نتوانستیم تشخیص دهیم کدام فصل باید بارگذاری شود. دوباره از جستجو شروع کن.",
  'routeMissingTranslationSetupTitle': "تنظیمات ترجمه",
  'routeMissingTranslationSetupMessage':
      "قبل از باز شدن صفحه تنظیمات ترجمه، وجود یک منبع زیرنویس ضروری است.",
  'routeMissingTranslationProgressTitle': "روند ترجمه",
  'routeMissingTranslationProgressMessage':
      "هیچ درخواست ترجمه‌ای ارسال نشده است. یک ترجمه جدید را از مسیر جستجو یا آپلود شروع کن.",
  'searchResultPopularity': "محبوبیت {score}",
  'subtitleSourceLines': "{lineCount} خط",
  'subtitleSourceDownloads': "{downloads} دانلود",
  'subtitleSourceRating': "امتیاز {rating}",
  'subtitleSourceHiLabel': "HI / SDH",
  'mediaTypeMovie': "فیلم",
  'mediaTypeSeries': "سریال",
  'jobReuseTranslation': "استفاده دوباره از ترجمه",
  'jobReuseSubtitle': "استفاده دوباره از زیرنویس",
  'jobConfidence': "اطمینان: {level}",
  'jobOpenPreview': "باز کردن پیش‌نمایش",
  'onboardingPage1Title':
      "فیلم یا سریال پیدا کن و زیرنویس آماده ترجمه را بگیر.",
  'onboardingPage1Eyebrow': "جستجو و دریافت",
  'onboardingPage1Description':
      "یک عنوان جستجو کن، منابع زیرنویس انگلیسی موجود را ببین و جریان ترجمه‌ای را شروع کن که سریع و روان احساس می‌شود.",
  'onboardingPage1Highlight1': "کاتالوگ ماک قطعی برای توسعه مطمئن",
  'onboardingPage1Highlight2': "برچسب کیفیت منبع و نشان فرمت زیرنویس",
  'onboardingPage1Highlight3':
      "طوری ساخته شده که بعداً به بک‌اند واقعی وصل شود",
  'onboardingPage2Title': "وقتی فایل را داری، `.srt` یا `.vtt` آپلود کن.",
  'onboardingPage2Eyebrow': "فایل خودت را بیاور",
  'onboardingPage2Description':
      "فایل زیرنویس را وارد کن، فرمت را اعتبارسنجی کن و بدون خروج از اپ همان مسیر ترجمه حرفه‌ای را اجرا کن.",
  'onboardingPage2Highlight1':
      "اعتبارسنجی محلی فایل و حالت‌های تلاش دوباره روان",
  'onboardingPage2Highlight2': "تنظیمات ترجمه یکدست برای آپلود و جستجو",
  'onboardingPage2Highlight3':
      "قبل از خروجی گرفتن پیش‌نمایش ببین تا چیزی مبهم نماند",
  'onboardingPage3Title':
      "زبان مقصد را انتخاب کن، پیش‌نمایش ببین و فوری خروجی بگیر.",
  'onboardingPage3Eyebrow': "ترجمه و خروجی",
  'onboardingPage3Description':
      "بین نمایش اصلی، ترجمه‌شده و دوزبانه جابه‌جا شو، به تاریخچه سر بزن و وقتی نتیجه درست بود فایل تمیز زیرنویس را خروجی بگیر.",
  'onboardingPage3Highlight1':
      "کنترل‌های سریع پیش‌نمایش همراه با متادیتا و جستجو",
  'onboardingPage3Highlight2':
      "تاریخچه، کارهای قبلی را فقط با یک لمس در دسترس نگه می‌دارد",
  'onboardingPage3Highlight3':
      "طراحی‌شده مثل یک ابزار رسانه‌ای پریمیوم، نه یک دمو",
  'onboardingStart': "شروع ترجمه",
  'onboardingNext': "بعدی",
  'onboardingSkip': "رد کردن",
  'onboardingContinue': "ادامه",
  'onboardingEnterApp': "ورود به SubFlix",
  'splashHeadline': "SubFlix",
  'splashSubtitle': "ترجمه زیرنویس با هوش مصنوعی",
  'splashPreparing': "در حال آماده‌سازی استودیوی زیرنویس تو",
  'brandSubtitleCompact': "هوش زیرنویس",
  'brandSubtitleFull': "استودیوی ترجمه زیرنویس با هوش مصنوعی",
  'comingSoonTitle': "به‌زودی",
  'comingSoonMessage': "هنوز در حال آماده کردن این صفحه هستیم.",
};
