const Map<String, String> kStringsEs = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Buscar t?tulos',
  'searchMovieOrSeriesTitle': 'Buscar pel?cula o serie',
  'searchMovieOrSeriesSubtitle': 'Encuentra un t?tulo, revisa fuentes y lanza la traducci?n.',
  'searchHintText': 'Buscar Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Buscar en el cat?logo demo',
  'searchMockMessage': 'Prueba Inception, Dune, Breaking Bad, Severance.',
  'searchFailedTitle': 'B?squeda fallida',
  'noTitlesMatchedTitle': 'No hubo coincidencias',
  'noTitlesMatchedMessage': 'No se encontr? en el cat?logo demo. Prueba otra b?squeda.',
  'retry': 'Reintentar',
  'retryTranslation': 'Reintentar traducci?n',
  'uploadSubtitleTitle': 'Subir subt?tulos',
  'uploadIntroTitle': 'Trae tu archivo de subt?tulos',
  'uploadIntroSubtitle': 'Importa un archivo `.srt` o `.vtt` en ingl?s.',
  'uploadChooseFile': 'Elegir archivo',
  'uploadSupportedFormatsTitle': 'Formatos compatibles',
  'uploadSupportedFormatsSubtitle': 'Archivos `.srt` y `.vtt` en ingl?s',
  'uploadOpeningPicker': 'Abriendo selector...',
  'uploadChooseFileShort': 'Elegir',
  'uploadPickSubtitle': 'Seleccionar archivo de subt?tulos',
  'uploadPickedFile': 'Archivo seleccionado',
  'uploadUseDemoFile': 'Usar archivo demo',
  'uploadFailedTitle': 'Error al importar',
  'uploadFailedMessage': 'No se pudo leer el archivo. Prueba con otro.',
  'uploadFailedFallback': 'Por favor prueba con otro archivo.',
  'tryAgain': 'Intentar de nuevo',
  'uploadMetadataTitle': 'Detalles de subt?tulos',
  'uploadReadyTitle': 'Listo para traducir',
  'uploadLineCount': '{lineCount} l?neas',
  'uploadEnglishSource': 'Fuente en ingl?s',
  'uploadContinueSetup': 'Continuar configuraci?n',
  'translateSetupTitle': 'Configuraci?n de traducci?n',
  'translateSetupSubtitle': 'Elige el idioma objetivo e inicia la traducci?n.',
  'subtitleSourceFormatLabel': 'Fuente {format}',
  'targetLanguage': 'Idioma objetivo',
  'startTranslation': 'Iniciar traducci?n',
  'translationProgressTitle': 'Progreso',
  'translationProgressHeadline': 'Traducci?n IA en curso',
  'translationFailedTitle': 'La traducci?n fall?',
  'translationFailedMessage': 'Algo sali? mal.',
  'translationStageQueued': 'En cola',
  'translationStageIdle': 'Esperando solicitud',
  'translationStagePreparing': 'Preparando paquete',
  'translationStageAligning': 'Alineando tiempos',
  'translationStageGenerating': 'Generando traducci?n',
  'translationStageReadability': 'Mejorando legibilidad',
  'translationStageReady': 'Traducci?n lista',
  'translationPreviewTitle': 'Vista previa',
  'translationPreviewHeader': 'Revisar traducci?n',
  'translationPreviewSubtitle': 'Busca, cambia el modo y exporta.',
  'translationPreviewSearchHint': 'Buscar en subt?tulos',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Traducido',
  'previewModeBilingual': 'Biling?e',
  'previewNotReadyTitle': 'Vista previa no disponible',
  'previewNotReadyMessage': 'La traducci?n termin?, pero la vista previa a?n no lleg?.',
  'previewNoMatchesTitle': 'No hay coincidencias',
  'previewNoMatchesMessage': 'Prueba otro t?rmino o limpia el filtro.',
  'previewFailedTitle': 'Error al cargar la vista previa',
  'exportingLabel': 'Exportando...',
  'exportSubtitleLabel': 'Exportar subt?tulos traducidos',
  'exportedSnack': '{fileName} exportado a {path}',
  'exportFailedSnack': 'Fall? la exportaci?n: {error}',
  'metadataFormat': 'Formato',
  'metadataLines': 'L?neas',
  'metadataLanguages': 'Idiomas',
  'metadataEstimatedDuration': 'Duraci?n estimada',
  'subtitleSourcesTitle': 'Fuentes de subt?tulos en ingl?s',
  'subtitleSourcesSubtitle': 'Elige una fuente para {title}{target}.',
  'subtitleSourcesFailedTitle': 'No se pudieron cargar las fuentes',
  'seriesSeasonsTitle': 'Elegir temporada',
  'seriesSeasonsSubtitle': 'Elige una temporada de {title}.',
  'seriesSeasonLabel': 'Temporada {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} episodios{year}',
  'seriesEpisodesTitle': 'Temporada {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} episodios{year}',
  'seriesEpisodeLabel': 'Episodio {episodeNumber}',
  'seriesEpisodeMeta': 'Aprox. {runtime} min',
  'historyTitle': 'Historial',
  'historySubtitle': 'Reabre trabajos anteriores.',
  'historyEmptyTitle': 'Historial vac?o',
  'historyEmptyMessage': 'Aparecer?n aqu? tras completar un flujo.',
  'historyFailedTitle': 'No se pudo cargar el historial',
  'homeRecentJobsTitle': 'Trabajos recientes',
  'homeRecentJobsSubtitle': 'Reabre sesiones recientes r?pidamente.',
  'homeNoRecentTitle': 'Sin trabajos recientes',
  'homeNoRecentMessage': 'Empieza con b?squeda o subida.',
  'homeFailedRecentTitle': 'No se pudieron cargar trabajos recientes',
  'homeTrustTitle': 'Por qu? conf?an en ?l',
  'homeTrustSubtitle': 'Demo hoy, listo para producto real.',
  'homeFutureTitle': 'Repositorios preparados para el futuro',
  'homeFutureSubtitle': 'UI aislada del backend.',
  'homePreviewTitle': 'Flujo con vista previa',
  'homePreviewSubtitle': 'Revisa antes de exportar.',
  'homeStatesTitle': 'Estados completos',
  'homeStatesSubtitle': 'Carga, vac?o y reintento incluidos.',
  'navHome': 'Inicio',
  'navHistory': 'Historial',
  'navSettings': 'Ajustes',
  'heroTitle': 'Traduce subt?tulos m?s r?pido',
  'heroSubtitle': 'Busca, elige y exporta en minutos.',
  'heroBadge': 'Flujo premium',
  'heroHeadline': 'Traducci?n nivel estudio',
  'heroBody': 'Elige b?squeda o subida y exporta.',
  'heroSearchCta': 'Buscar pel?cula / serie',
  'heroUploadCta': 'Subir subt?tulos',
  'heroStatPathsTitle': '2 rutas',
  'heroStatPathsValue': 'B?squeda o subida',
  'heroStatLanguagesTitle': '10 idiomas',
  'heroStatLanguagesValue': 'Listo para vista previa',
  'heroStatMockTitle': 'APIs mock',
  'heroStatMockValue': 'Backend listo',
  'settingsTitle': 'Ajustes',
  'settingsSubtitle': 'Administra idioma, apariencia e informaci?n.',
  'settingsLanguageLabel': 'Idioma objetivo preferido',
  'settingsThemeLabel': 'Apariencia',
  'themeSystem': 'Sistema',
  'themeDark': 'Oscuro',
  'themeLight': 'Claro',
  'settingsPremiumTitle': 'Premium (placeholder)',
  'settingsPremiumSubtitle': 'Suscripciones m?s adelante.',
  'settingsSupportTitle': 'Soporte (placeholder)',
  'settingsSupportSubtitle': 'P?gina de soporte demo',
  'settingsPrivacyTitle': 'Pol?tica de privacidad',
  'settingsPrivacySubtitle': 'Contenido demo',
  'settingsTermsTitle': 'T?rminos de servicio',
  'settingsTermsSubtitle': 'Contenido demo',
  'settingsMaintenanceTitle': 'Mantenimiento',
  'settingsMaintenanceSubtitle': 'Borrar historial de este dispositivo.',
  'settingsHistoryClearedSnack': 'Historial borrado',
  'settingsAboutTitle': 'Acerca de SubFlix',
  'settingsVersion': 'Versi?n {version}',
  'settingsClearCache': 'Borrar cach?',
  'settingsCacheCleared': 'Cach? borrada',
  'settingsFailedTitle': 'No se pudieron cargar los ajustes',
  'legalPlaceholderBody': 'Esta p?gina es un placeholder.',
  'legalTitlePrivacy': 'Privacidad',
  'legalTitleTerms': 'T?rminos',
  'legalTitleSupport': 'Soporte',
  'legalTitleAbout': 'Acerca de',
  'legalBodyPrivacy': 'Solo se guardan preferencias de demo.',
  'legalBodyTerms': 'Esta versi?n es para pruebas.',
  'legalBodySupport': 'Soporte se conectar? m?s adelante.',
  'legalBodyAbout': 'Cliente Flutter para traducci?n de subt?tulos.',
  'routeMissingSubtitleSourcesTitle': 'Fuentes de subt?tulos',
  'routeMissingSubtitleSourcesMessage': 'No se pudo identificar el t?tulo.',
  'routeMissingSeriesSeasonsTitle': 'Temporadas',
  'routeMissingSeriesSeasonsMessage': 'No se pudo identificar la serie.',
  'routeMissingSeasonEpisodesTitle': 'Episodios',
  'routeMissingSeasonEpisodesMessage': 'No se pudo identificar la temporada.',
  'routeMissingTranslationSetupTitle': 'Configuraci?n',
  'routeMissingTranslationSetupMessage': 'Se requiere una fuente.',
  'routeMissingTranslationProgressTitle': 'Progreso',
  'routeMissingTranslationProgressMessage': 'No hay solicitud de traducci?n.',
  'searchResultPopularity': 'Popularidad {score}',
  'subtitleSourceLines': '{lineCount} l?neas',
  'subtitleSourceDownloads': '{downloads} descargas',
  'subtitleSourceRating': 'Valoraci?n {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Pel?cula',
  'mediaTypeSeries': 'Serie',
  'jobReuseTranslation': 'Reutilizar traducci?n',
  'jobReuseSubtitle': 'Reutilizar subt?tulos',
  'jobConfidence': 'Confianza: {level}',
  'jobOpenPreview': 'Abrir vista previa',
  'onboardingPage1Title': 'Encuentra pel?culas o series.',
  'onboardingPage1Eyebrow': 'Buscar y traer',
  'onboardingPage1Description': 'Busca y revisa fuentes.',
  'onboardingPage1Highlight1': 'Cat?logo demo confiable',
  'onboardingPage1Highlight2': 'Etiquetas de calidad',
  'onboardingPage1Highlight3': 'Listo para backend real',
  'onboardingPage2Title': 'Sube `.srt` o `.vtt`.',
  'onboardingPage2Eyebrow': 'Tu archivo',
  'onboardingPage2Description': 'Importa el archivo y contin?a.',
  'onboardingPage2Highlight1': 'Validaci?n local',
  'onboardingPage2Highlight2': 'Configuraci?n consistente',
  'onboardingPage2Highlight3': 'Vista previa antes de exportar',
  'onboardingPage3Title': 'Elige idioma y exporta.',
  'onboardingPage3Eyebrow': 'Traducir y exportar',
  'onboardingPage3Description': 'Cambia de modo y exporta.',
  'onboardingPage3Highlight1': 'Controles r?pidos de vista previa',
  'onboardingPage3Highlight2': 'Historial siempre disponible',
  'onboardingPage3Highlight3': 'Dise?o premium',
  'onboardingStart': 'Empezar',
  'onboardingNext': 'Siguiente',
  'onboardingSkip': 'Saltar',
  'onboardingContinue': 'Continuar',
  'onboardingEnterApp': 'Entrar a SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'Traducci?n de subt?tulos con IA',
  'splashPreparing': 'Preparando el estudio',
  'brandSubtitleCompact': 'Inteligencia de subt?tulos',
  'brandSubtitleFull': 'Estudio de traducci?n con IA',
  'comingSoonTitle': 'Pr?ximamente',
  'comingSoonMessage': 'Esta pantalla se est? preparando.',
};
