const Map<String, String> kStringsEn = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Search titles',
  'searchMovieOrSeriesTitle': 'Search movie or series',
  'searchMovieOrSeriesSubtitle':
      'Find a title, inspect subtitle sources, and launch a translation job with a few taps.',
  'searchHintText': 'Search for Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Search anything in the mock catalog',
  'searchMockMessage':
      'Try titles like Inception, Dune, Breaking Bad, Severance, or The Last of Us to explore the subtitle source flow.',
  'searchFailedTitle': 'Search failed',
  'noTitlesMatchedTitle': 'No titles matched',
  'noTitlesMatchedMessage':
      'We could not find that title in the mock catalog. Try a broader search or one of the suggested shows.',
  'searchTrendingTitle': 'Trending searches',
  'searchLoadingLabel': 'Searching...',
  'searchFoundResults': 'Found {count} results for "{query}"',
  'searchNoResultsFor': 'No results found for "{query}"',
  'searchTryDifferentKeywords': 'Try searching with different keywords.',
  'retry': 'Retry',
  'retryTranslation': 'Retry translation',
  'uploadSubtitleTitle': 'Upload subtitle',
  'uploadIntroTitle': 'Bring your own subtitle file',
  'uploadIntroSubtitle':
      'Import an English `.srt` or `.vtt` file, let the backend validate and parse it, then continue into translation setup.',
  'uploadChooseFile': 'Choose subtitle file',
  'uploadSupportedFormatsTitle': 'Supported formats',
  'uploadSupportedFormatsSubtitle': 'English `.srt` and `.vtt` subtitle files',
  'uploadOpeningPicker': 'Opening picker...',
  'uploadChooseFileShort': 'Choose file',
  'uploadPickSubtitle': 'Pick subtitle file',
  'uploadPickedFile': 'Picked subtitle file',
  'uploadUseDemoFile': 'Use demo file',
  'uploadFailedTitle': 'File import failed',
  'uploadFailedMessage':
      'We could not read this subtitle file. Try a different file or pick a smaller export.',
  'uploadFailedFallback': 'Please try another subtitle file.',
  'tryAgain': 'Try again',
  'uploadMetadataTitle': 'Subtitle details',
  'uploadReadyTitle': 'Ready to translate',
  'uploadLineCount': '{lineCount} lines',
  'uploadEnglishSource': 'English source',
  'uploadContinueSetup': 'Continue to translation setup',
  'translateSetupTitle': 'Translate setup',
  'translateSetupSubtitle':
      'Choose the target language, review the subtitle source, and start the backend translation job.',
  'subtitleSourceFormatLabel': '{format} subtitle source',
  'targetLanguage': 'Target language',
  'startTranslation': 'Start translation',
  'translationProgressTitle': 'Translation progress',
  'translationProgressHeadline': 'AI subtitle translation in progress',
  'translationFailedTitle': 'Translation could not finish',
  'translationFailedMessage': 'Something went wrong.',
  'translationStageQueued': 'Queued for translation',
  'translationStageIdle': 'Waiting for a translation request',
  'translationStagePreparing': 'Preparing subtitle package',
  'translationStageAligning': 'Aligning timestamps and scene context',
  'translationStageGenerating': 'Generating subtitle translation',
  'translationStageReadability': 'Applying readability pass',
  'translationStageReady': 'Translation ready',
  'translationResultCompleteTitle': 'Translation complete',
  'translationResultCompleteSubtitle':
      'Your subtitle is ready to preview or download.',
  'translationResultDetailsTitle': 'Translation details',
  'translationResultMediaLabel': 'Media title',
  'translationResultSourceLabel': 'Source language',
  'translationResultTargetLabel': 'Target language',
  'translationResultMethodAi': 'AI translated',
  'translationResultMetricsTitle': 'Quality metrics',
  'translationResultConfidenceLabel': 'Translation confidence',
  'translationResultTimingLabel': 'Timing accuracy',
  'translationResultTimingPreserved': 'Timing preserved',
  'translationResultProcessedIn': 'Processed in {duration}',
  'translationResultWarning':
      'Some technical terms may still benefit from a quick human review for context.',
  'translationResultPreviewCta': 'Preview subtitle',
  'translationResultDownloadCta': 'Download subtitle',
  'translationResultHomeCta': 'Back to home',
  'translationPreviewTitle': 'Translation preview',
  'translationPreviewHeader': 'Review translated subtitles',
  'translationPreviewSubtitle':
      'Search inside cues, switch preview modes, then export once the translation looks right.',
  'translationPreviewSearchHint': 'Search subtitle lines',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Translated',
  'previewModeBilingual': 'Bilingual',
  'previewNotReadyTitle': 'Preview cues are not available yet',
  'previewNotReadyMessage':
      'The translation finished, but the backend did not return preview cues yet. Try reloading this screen in a moment.',
  'previewNoMatchesTitle': 'No subtitle lines matched',
  'previewNoMatchesMessage':
      'Try a different search term or clear the filter to inspect the full translation.',
  'previewFailedTitle': 'Preview failed to load',
  'exportingLabel': 'Exporting...',
  'exportSubtitleLabel': 'Export translated subtitle',
  'exportedSnack': 'Exported {fileName} to {path}',
  'exportFailedSnack': 'Export failed: {error}',
  'metadataFormat': 'Format',
  'metadataLines': 'Lines',
  'metadataLanguages': 'Languages',
  'metadataEstimatedDuration': 'Estimated duration',
  'subtitleSourcesTitle': 'English subtitle sources',
  'subtitleSourcesSubtitle':
      'Pick a subtitle source for {title}{target}, then choose the target language in the next step.',
  'subtitleSourcesFailedTitle': 'Could not load subtitle sources',
  'seriesSeasonsTitle': 'Choose a season',
  'seriesSeasonsSubtitle':
      'Pick a season of {title} to browse available episodes.',
  'seriesSeasonLabel': 'Season {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} episodes{year}',
  'seriesEpisodesTitle': 'Season {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} episodes{year}',
  'seriesEpisodeLabel': 'Episode {episodeNumber}',
  'seriesEpisodeMeta': 'Approx. {runtime} min',
  'historyTitle': 'Translation history',
  'historySubtitle':
      'Reopen previous subtitle jobs, inspect the preview again, or export them later.',
  'historyEmptyTitle': 'History is empty',
  'historyEmptyMessage':
      'Your translated subtitle jobs will appear here after you complete a search or upload workflow.',
  'historyFailedTitle': 'Could not load history',
  'homeRecentJobsTitle': 'Recent jobs',
  'homeRecentJobsSubtitle':
      'Reopen your latest subtitle sessions without starting over.',
  'homeNoRecentTitle': 'No recent jobs yet',
  'homeNoRecentMessage':
      'Start with a movie search or upload a subtitle file and your recent translations will appear here.',
  'homeFailedRecentTitle': 'Could not load recent jobs',
  'homeWelcomeTitle': 'Welcome back',
  'homeWelcomeSubtitle': 'Find and translate subtitles',
  'homeSearchPlaceholder': 'Search movies or series...',
  'homeQuickSearch': 'Search',
  'homeQuickHistory': 'History',
  'homeQuickUpload': 'Upload',
  'homeViewAll': 'View all',
  'homeTrendingNow': 'Trending now',
  'homeTrustTitle': 'Why teams trust it',
  'homeTrustSubtitle':
      'Mocked today, but structured like a product that can ship for real.',
  'homeFutureTitle': 'Future-ready repositories',
  'homeFutureSubtitle':
      'Swappable mock repositories keep UI code insulated from backend changes.',
  'homePreviewTitle': 'Preview-first translation flow',
  'homePreviewSubtitle':
      'Inspect results before export with original, translated, or bilingual views.',
  'homeStatesTitle': 'Graceful states included',
  'homeStatesSubtitle':
      'Loading, empty, retry, validation, and mock offline scenarios are part of the UX from day one.',
  'navHome': 'Home',
  'navHistory': 'History',
  'navSettings': 'Settings',
  'heroTitle': 'Translate subtitles faster',
  'heroSubtitle':
      'Search movie and series catalogs, pick sources, and export polished translations in minutes.',
  'heroBadge': 'Premium subtitle workflow',
  'heroHeadline':
      'Translate movie and series subtitles with a studio-grade flow.',
  'heroBody':
      'Choose between a searchable title catalog or direct file upload, then preview and export polished subtitles in minutes.',
  'heroSearchCta': 'Search movie / series',
  'heroUploadCta': 'Upload subtitle',
  'heroStatPathsTitle': '2 paths',
  'heroStatPathsValue': 'Search or upload',
  'heroStatLanguagesTitle': '10 languages',
  'heroStatLanguagesValue': 'Ready for preview',
  'heroStatMockTitle': 'Mock APIs',
  'heroStatMockValue': 'Backend-ready seam',
  'settingsTitle': 'Settings',
  'settingsSubtitle':
      'Manage subtitle defaults, appearance, app information, and placeholder premium controls.',
  'settingsLanguageLabel': 'Preferred target language',
  'settingsThemeLabel': 'Appearance',
  'themeSystem': 'System',
  'themeDark': 'Dark',
  'themeLight': 'Light',
  'settingsPremiumTitle': 'Premium placeholder',
  'settingsPremiumSubtitle':
      'Later we can connect subscriptions, billing, and cloud project sync here.',
  'settingsSupportTitle': 'Support placeholder',
  'settingsSupportSubtitle': 'Mock help and contact page',
  'settingsPrivacyTitle': 'Privacy policy',
  'settingsPrivacySubtitle': 'Mock privacy content',
  'settingsTermsTitle': 'Terms of service',
  'settingsTermsSubtitle': 'Mock terms content',
  'settingsMaintenanceTitle': 'Maintenance',
  'settingsMaintenanceSubtitle':
      'Clear backend-owned translation jobs for this device and start with an empty history state.',
  'settingsHistoryClearedSnack': 'Translation history cleared for this device',
  'settingsAboutTitle': 'About SubFlix',
  'settingsVersion': 'Version {version}',
  'settingsClearCache': 'Clear cache',
  'settingsCacheCleared': 'Cache cleared',
  'settingsFailedTitle': 'Settings failed to load',
  'legalPlaceholderBody':
      'This page is a placeholder in the demo app. Hook it up to your production legal content.',
  'legalTitlePrivacy': 'Privacy Policy',
  'legalTitleTerms': 'Terms of Service',
  'legalTitleSupport': 'Support',
  'legalTitleAbout': 'About SubFlix',
  'legalBodyPrivacy':
      'SubFlix currently stores only mock preferences and translation history on device through local persistence. A future backend integration can replace this with authenticated storage, audit trails, and server-managed retention policies.',
  'legalBodyTerms':
      'This mock build is intended to exercise product flows, UI states, and architecture boundaries. When a production NestJS and Postgres backend is connected later, the legal surface can be expanded with real service terms and data processing language.',
  'legalBodySupport':
      'Support is a placeholder for now. In a production release this section can connect to email, issue reporting, and premium account help while keeping the app shell unchanged.',
  'legalBodyAbout':
      'SubFlix is a premium-style Flutter client for AI subtitle translation. This build uses mock repositories, artificial latency, and local persistence so the UI and architecture can evolve before a real backend is attached.',
  'routeMissingSubtitleSourcesTitle': 'Subtitle sources',
  'routeMissingSubtitleSourcesMessage':
      'We could not determine which title to load subtitle sources for. Start again from search.',
  'routeMissingSeriesSeasonsTitle': 'Series seasons',
  'routeMissingSeriesSeasonsMessage':
      'We could not determine which series to load. Start again from search.',
  'routeMissingSeasonEpisodesTitle': 'Season episodes',
  'routeMissingSeasonEpisodesMessage':
      'We could not determine which season to load. Start again from search.',
  'routeMissingTranslationSetupTitle': 'Translation setup',
  'routeMissingTranslationSetupMessage':
      'A subtitle source is required before the translation setup screen can open.',
  'routeMissingTranslationProgressTitle': 'Translation progress',
  'routeMissingTranslationProgressMessage':
      'No translation request was provided. Start a new translation from search or upload.',
  'searchResultPopularity': 'Popularity {score}',
  'subtitleSourceLines': '{lineCount} lines',
  'subtitleSourceDownloads': '{downloads} downloads',
  'subtitleSourceRating': '{rating} rating',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Movie',
  'mediaTypeSeries': 'Series',
  'jobReuseTranslation': 'Reuse translation',
  'jobReuseSubtitle': 'Reuse subtitle',
  'jobConfidence': 'Confidence: {level}',
  'jobOpenPreview': 'Open preview',
  'onboardingPage1Title':
      'Find movies or series and pull ready-to-translate subtitles.',
  'onboardingPage1Eyebrow': 'Search and fetch',
  'onboardingPage1Description':
      'Search a title, review the available English subtitle sources, and launch a translation workflow that feels instant.',
  'onboardingPage1Highlight1':
      'Deterministic mock catalog for reliable development',
  'onboardingPage1Highlight2':
      'Subtitle source quality labels and format badges',
  'onboardingPage1Highlight3': 'Built to swap into a real backend later',
  'onboardingPage2Title':
      'Upload `.srt` or `.vtt` files when you already have the script.',
  'onboardingPage2Eyebrow': 'Bring your own file',
  'onboardingPage2Description':
      'Import your subtitle file, validate the format, and run the same polished translation pipeline without leaving the app.',
  'onboardingPage2Highlight1':
      'Local file validation and graceful retry states',
  'onboardingPage2Highlight2':
      'Consistent translation setup for uploads and search',
  'onboardingPage2Highlight3': 'Preview before export so nothing feels opaque',
  'onboardingPage3Title':
      'Pick target languages, preview subtitles, and export instantly.',
  'onboardingPage3Eyebrow': 'Translate and export',
  'onboardingPage3Description':
      'Switch between original, translated, and bilingual views, revisit history, and export clean subtitle files once the result looks right.',
  'onboardingPage3Highlight1': 'Fast preview controls with metadata and search',
  'onboardingPage3Highlight2': 'History keeps previous jobs a tap away',
  'onboardingPage3Highlight3': 'Designed like a premium media tool, not a demo',
  'onboardingStart': 'Start translation',
  'onboardingNext': 'Next',
  'onboardingSkip': 'Skip',
  'onboardingContinue': 'Continue',
  'onboardingEnterApp': 'Enter SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'AI-powered subtitle translation',
  'splashPreparing': 'Preparing your subtitle studio',
  'brandSubtitleCompact': 'Subtitle intelligence',
  'brandSubtitleFull': 'AI subtitle translation studio',
  'comingSoonTitle': 'Coming soon',
  'comingSoonMessage': 'We are still preparing this screen.',
};
