const Map<String, String> kStringsAr = <String, String>{
  'appTitle': 'ساب فليكس',
  'searchTitles': 'البحث عن العناوين',
  'searchMovieOrSeriesTitle': 'البحث عن فيلم أو مسلسل',
  'searchMovieOrSeriesSubtitle':
      'يمكنك العثور على عنوان، واستعراض مصادر الترجمة، وبدء الترجمة خلال بضع نقرات.',
  'searchHintText': 'ابحث عن Dune أو Breaking Bad أو Severance...',
  'searchMockTitle': 'البحث في الكتالوج التجريبي',
  'searchMockMessage':
      'يمكنك تجربة عناوين مثل Inception أو Dune أو Breaking Bad أو Severance أو The Last of Us لاستعراض مصادر الترجمة.',
  'searchFailedTitle': 'تعذر إجراء البحث',
  'noTitlesMatchedTitle': 'لم يتم العثور على نتائج',
  'noTitlesMatchedMessage':
      'لم يتم العثور على هذا العنوان في الكتالوج التجريبي. يرجى تجربة بحث أوسع أو اختيار أحد العناوين المقترحة.',
  'retry': 'إعادة المحاولة',
  'retryTranslation': 'إعادة محاولة الترجمة',
  'uploadSubtitleTitle': 'رفع الترجمة',
  'uploadIntroTitle': 'إضافة ملف ترجمة',
  'uploadIntroSubtitle':
      'يرجى اختيار ملف ترجمة باللغة الإنجليزية بصيغة `.srt` أو `.vtt` ليتم التحقق منه ومعالجته، ثم الانتقال إلى إعداد الترجمة.',
  'uploadChooseFile': 'اختيار ملف الترجمة',
  'uploadSupportedFormatsTitle': 'الصيغ المدعومة',
  'uploadSupportedFormatsSubtitle': 'ملفات الترجمة الإنجليزية `.srt` و `.vtt`',
  'uploadOpeningPicker': 'جارٍ فتح الملفات...',
  'uploadChooseFileShort': 'اختيار ملف',
  'uploadPickSubtitle': 'اختيار ملف ترجمة',
  'uploadPickedFile': 'تم اختيار ملف الترجمة',
  'uploadUseDemoFile': 'استخدام ملف تجريبي',
  'uploadFailedTitle': 'تعذر استيراد الملف',
  'uploadFailedMessage':
      'تعذر قراءة ملف الترجمة هذا. يرجى اختيار ملف آخر أو استخدام ملف أصغر.',
  'uploadFailedFallback': 'يرجى اختيار ملف ترجمة آخر.',
  'tryAgain': 'حاول مرة أخرى',
  'uploadMetadataTitle': 'تفاصيل الترجمة',
  'uploadReadyTitle': 'جاهز للترجمة',
  'uploadLineCount': '{lineCount} سطر',
  'uploadEnglishSource': 'المصدر الإنجليزي',
  'uploadContinueSetup': 'المتابعة إلى إعداد الترجمة',
  'translateSetupTitle': 'إعداد الترجمة',
  'translateSetupSubtitle':
      'يرجى اختيار اللغة الهدف، ومراجعة مصدر الترجمة، ثم بدء الترجمة.',
  'subtitleSourceFormatLabel': 'ترجمة {format}',
  'targetLanguage': 'اللغة الهدف',
  'startTranslation': 'بدء الترجمة',
  'translationProgressTitle': 'تقدم الترجمة',
  'translationProgressHeadline': 'جارٍ ترجمة الترجمة باستخدام الذكاء الاصطناعي',
  'translationFailedTitle': 'تعذر إكمال الترجمة',
  'translationFailedMessage': 'حدث خطأ ما.',
  'translationStageQueued': 'في قائمة الانتظار',
  'translationStageIdle': 'بانتظار طلب الترجمة',
  'translationStagePreparing': 'جارٍ تجهيز ملف الترجمة',
  'translationStageAligning': 'جارٍ ضبط التوقيت وسياق المشهد',
  'translationStageGenerating': 'جارٍ إنشاء الترجمة',
  'translationStageReadability': 'جارٍ تحسين قابلية القراءة',
  'translationStageReady': 'الترجمة جاهزة',
  'translationPreviewTitle': 'معاينة الترجمة',
  'translationPreviewHeader': 'مراجعة الترجمة',
  'translationPreviewSubtitle':
      'يمكنك البحث داخل الأسطر، وتغيير وضع المعاينة، ثم تصدير الملف بعد مراجعة النتيجة.',
  'translationPreviewSearchHint': 'البحث داخل أسطر الترجمة',
  'previewModeOriginal': 'الأصلي',
  'previewModeTranslated': 'المترجم',
  'previewModeBilingual': 'ثنائي اللغة',
  'previewNotReadyTitle': 'المعاينة غير متاحة بعد',
  'previewNotReadyMessage':
      'اكتملت الترجمة، لكن المعاينة لم تصبح متاحة بعد. يرجى إعادة تحميل هذه الشاشة بعد قليل.',
  'previewNoMatchesTitle': 'لم يتم العثور على نتائج مطابقة',
  'previewNoMatchesMessage':
      'يرجى تجربة كلمة بحث مختلفة أو إزالة الفلتر لعرض الترجمة كاملة.',
  'previewFailedTitle': 'تعذر تحميل المعاينة',
  'exportingLabel': 'جارٍ التصدير...',
  'exportSubtitleLabel': 'تصدير الترجمة',
  'exportedSnack': 'تم حفظ {fileName} في {path}',
  'exportFailedSnack': 'فشل التصدير: {error}',
  'metadataFormat': 'الصيغة',
  'metadataLines': 'عدد الأسطر',
  'metadataLanguages': 'اللغات',
  'metadataEstimatedDuration': 'المدة التقديرية',
  'subtitleSourcesTitle': 'مصادر الترجمة الإنجليزية',
  'subtitleSourcesSubtitle':
      'يرجى اختيار مصدر ترجمة لـ {title}{target}، ثم اختيار اللغة الهدف في الخطوة التالية.',
  'subtitleSourcesFailedTitle': 'تعذر تحميل مصادر الترجمة',
  'seriesSeasonsTitle': 'اختيار الموسم',
  'seriesSeasonsSubtitle': 'يرجى اختيار موسم من {title} لعرض الحلقات المتاحة.',
  'seriesSeasonLabel': 'الموسم {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} حلقات{year}',
  'seriesEpisodesTitle': 'الموسم {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} حلقات{year}',
  'seriesEpisodeLabel': 'الحلقة {episodeNumber}',
  'seriesEpisodeMeta': 'حوالي {runtime} دقيقة',
  'historyTitle': 'سجل الترجمة',
  'historySubtitle':
      'يمكنك إعادة فتح الترجمات السابقة، ومراجعة المعاينة مرة أخرى، أو تصديرها لاحقًا.',
  'historyEmptyTitle': 'السجل فارغ',
  'historyEmptyMessage': 'ستظهر الترجمات هنا بعد إكمال البحث أو رفع ملف ترجمة.',
  'historyFailedTitle': 'تعذر تحميل السجل',
  'homeRecentJobsTitle': 'الترجمات الأخيرة',
  'homeRecentJobsSubtitle': 'يمكنك فتح أحدث جلسات الترجمة دون البدء من جديد.',
  'homeNoRecentTitle': 'لا توجد ترجمات حديثة بعد',
  'homeNoRecentMessage':
      'يرجى البدء بالبحث عن فيلم أو رفع ملف ترجمة، وستظهر الترجمات الأخيرة هنا.',
  'homeFailedRecentTitle': 'تعذر تحميل الترجمات الأخيرة',
  'homeTrustTitle': 'لماذا تثق به الفرق',
  'homeTrustSubtitle':
      'هذه نسخة تجريبية حاليًا، لكنها منظمة مثل منتج جاهز للإطلاق.',
  'homeFutureTitle': 'مستودعات جاهزة للمستقبل',
  'homeFutureSubtitle':
      'تحافظ المستودعات التجريبية القابلة للاستبدال على عزل واجهة المستخدم عن تغييرات الخادم.',
  'homePreviewTitle': 'ترجمة تبدأ بالمعاينة',
  'homePreviewSubtitle':
      'يمكن مراجعة النتائج قبل التصدير من خلال العرض الأصلي أو المترجم أو الثنائي اللغة.',
  'homeStatesTitle': 'جميع الحالات مدعومة بسلاسة',
  'homeStatesSubtitle':
      'حالات التحميل والفراغ وإعادة المحاولة والتحقق وحتى سيناريوهات عدم الاتصال التجريبية جزء من التجربة منذ البداية.',
  'navHome': 'الرئيسية',
  'navHistory': 'السجل',
  'navSettings': 'الإعدادات',
  'heroTitle': 'ترجمة الترجمة بشكل أسرع',
  'heroSubtitle':
      'ابحث في كتالوجات الأفلام والمسلسلات، واختر المصدر، واحصل على ترجمة جاهزة خلال دقائق.',
  'heroBadge': 'تجربة ترجمة احترافية',
  'heroHeadline': 'ترجمة ترجمات الأفلام والمسلسلات بتجربة احترافية.',
  'heroBody':
      'يمكن الاختيار بين البحث في الكتالوج أو رفع ملف ترجمة مباشرة، ثم معاينة النتيجة وتصديرها خلال دقائق.',
  'heroSearchCta': 'البحث عن فيلم / مسلسل',
  'heroUploadCta': 'رفع ترجمة',
  'heroStatPathsTitle': 'مساران',
  'heroStatPathsValue': 'بحث أو رفع',
  'heroStatLanguagesTitle': '10 لغات',
  'heroStatLanguagesValue': 'جاهزة للمعاينة',
  'heroStatMockTitle': 'واجهات تجريبية',
  'heroStatMockValue': 'جاهزة للربط بالخادم',
  'settingsTitle': 'الإعدادات',
  'settingsSubtitle':
      'إدارة إعدادات الترجمة الافتراضية والمظهر ومعلومات التطبيق وعناصر بريميوم التجريبية.',
  'settingsLanguageLabel': 'لغة الهدف المفضلة',
  'settingsThemeLabel': 'المظهر',
  'themeSystem': 'النظام',
  'themeDark': 'داكن',
  'themeLight': 'فاتح',
  'settingsPremiumTitle': 'عنصر بريميوم تجريبي',
  'settingsPremiumSubtitle':
      'يمكن إضافة الاشتراكات والفوترة ومزامنة المشاريع السحابية هنا لاحقًا.',
  'settingsSupportTitle': 'عنصر دعم تجريبي',
  'settingsSupportSubtitle': 'صفحة مساعدة وتواصل تجريبية',
  'settingsPrivacyTitle': 'سياسة الخصوصية',
  'settingsPrivacySubtitle': 'محتوى خصوصية تجريبي',
  'settingsTermsTitle': 'شروط الخدمة',
  'settingsTermsSubtitle': 'محتوى شروط تجريبي',
  'settingsMaintenanceTitle': 'الصيانة',
  'settingsMaintenanceSubtitle':
      'يرجى مسح مهام الترجمة الخاصة بهذا الجهاز والبدء بسجل فارغ.',
  'settingsHistoryClearedSnack': 'تم مسح سجل الترجمة لهذا الجهاز',
  'settingsAboutTitle': 'حول SubFlix',
  'settingsVersion': 'الإصدار {version}',
  'settingsClearCache': 'مسح ذاكرة التخزين المؤقت',
  'settingsCacheCleared': 'تم مسح ذاكرة التخزين المؤقت',
  'settingsFailedTitle': 'فشل تحميل الإعدادات',
  'legalPlaceholderBody':
      'هذه الصفحة عنصر نائب في التطبيق التجريبي. يمكن ربطها بالمحتوى القانوني الفعلي في الإصدار الإنتاجي.',
  'legalTitlePrivacy': 'سياسة الخصوصية',
  'legalTitleTerms': 'شروط الخدمة',
  'legalTitleSupport': 'الدعم',
  'legalTitleAbout': 'حول SubFlix',
  'legalBodyPrivacy':
      'يخزن SubFlix حاليًا التفضيلات التجريبية وسجل الترجمة محليًا على الجهاز فقط. ويمكن أن يحل التكامل المستقبلي مع الخادم محل ذلك من خلال تخزين موثّق وسجلات تدقيق وسياسات احتفاظ تُدار من جهة الخادم.',
  'legalBodyTerms':
      'تم إنشاء هذا الإصدار التجريبي لاختبار تدفقات المنتج وحالات الواجهة وحدود المعمارية. وعند ربط خادم NestJS وقاعدة بيانات Postgres لاحقًا، يمكن توسيع هذا القسم ببنود خدمة فعلية وصياغات خاصة بمعالجة البيانات.',
  'legalBodySupport':
      'الدعم عنصر نائب حاليًا. وفي الإصدار النهائي يمكن لهذا القسم أن يتصل بالبريد الإلكتروني والإبلاغ عن المشكلات ومساعدة الحسابات المميزة، مع بقاء هيكل التطبيق كما هو.',
  'legalBodyAbout':
      'SubFlix هو تطبيق Flutter بطابع احترافي لترجمة الترجمة باستخدام الذكاء الاصطناعي. يعتمد هذا الإصدار على مستودعات تجريبية وتأخير اصطناعي وتخزين محلي حتى تتمكن الواجهة والمعمارية من التطور قبل ربط خادم حقيقي.',
  'routeMissingSubtitleSourcesTitle': 'مصادر الترجمة',
  'routeMissingSubtitleSourcesMessage':
      'تعذر تحديد العنوان المطلوب تحميل مصادر الترجمة له. يرجى البدء من البحث مرة أخرى.',
  'routeMissingSeriesSeasonsTitle': 'مواسم المسلسل',
  'routeMissingSeriesSeasonsMessage':
      'تعذر تحديد المسلسل المطلوب تحميله. يرجى البدء من البحث مرة أخرى.',
  'routeMissingSeasonEpisodesTitle': 'حلقات الموسم',
  'routeMissingSeasonEpisodesMessage':
      'تعذر تحديد الموسم المطلوب تحميله. يرجى البدء من البحث مرة أخرى.',
  'routeMissingTranslationSetupTitle': 'إعداد الترجمة',
  'routeMissingTranslationSetupMessage':
      'يلزم تحديد مصدر ترجمة قبل فتح شاشة إعداد الترجمة.',
  'routeMissingTranslationProgressTitle': 'تقدم الترجمة',
  'routeMissingTranslationProgressMessage':
      'لم يتم تقديم طلب ترجمة. يرجى بدء ترجمة جديدة من البحث أو الرفع.',
  'searchResultPopularity': 'الشعبية {score}',
  'subtitleSourceLines': '{lineCount} سطر',
  'subtitleSourceDownloads': '{downloads} تنزيل',
  'subtitleSourceRating': 'التقييم {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'فيلم',
  'mediaTypeSeries': 'مسلسل',
  'jobReuseTranslation': 'إعادة استخدام الترجمة',
  'jobReuseSubtitle': 'إعادة استخدام ملف الترجمة',
  'jobConfidence': 'مستوى الثقة: {level}',
  'jobOpenPreview': 'فتح المعاينة',
  'onboardingPage1Title':
      'اعثر على الأفلام أو المسلسلات واحصل على ترجمات جاهزة للترجمة.',
  'onboardingPage1Eyebrow': 'البحث والاستيراد',
  'onboardingPage1Description':
      'ابحث عن عنوان، وراجع مصادر الترجمة الإنجليزية المتاحة، وابدأ الترجمة بسرعة.',
  'onboardingPage1Highlight1': 'كتالوج تجريبي ثابت لتطوير موثوق',
  'onboardingPage1Highlight2': 'ملصقات جودة المصدر وشارات الصيغة',
  'onboardingPage1Highlight3': 'مصمم للاتصال بخادم حقيقي لاحقًا',
  'onboardingPage2Title':
      'يمكن رفع ملفات `.srt` أو `.vtt` عندما يكون ملف الترجمة متوفرًا.',
  'onboardingPage2Eyebrow': 'إضافة ملفك الخاص',
  'onboardingPage2Description':
      'استورد ملف الترجمة، وتحقق من الصيغة، ثم تابع نفس مسار الترجمة دون مغادرة التطبيق.',
  'onboardingPage2Highlight1': 'تحقق محلي من الملف مع حالات إعادة محاولة واضحة',
  'onboardingPage2Highlight2': 'إعداد ترجمة موحد للرفع والبحث',
  'onboardingPage2Highlight3': 'معاينة قبل التصدير لمزيد من الوضوح',
  'onboardingPage3Title': 'اختر اللغة الهدف، وعاين الترجمة، ثم صدّرها فورًا.',
  'onboardingPage3Eyebrow': 'الترجمة والتصدير',
  'onboardingPage3Description':
      'يمكن التبديل بين العرض الأصلي والمترجم والثنائي اللغة، والعودة إلى السجل، ثم تصدير ملف ترجمة نظيف عند جاهزية النتيجة.',
  'onboardingPage3Highlight1':
      'عناصر تحكم سريعة للمعاينة مع البيانات الوصفية والبحث',
  'onboardingPage3Highlight2': 'يبقي السجل المهام السابقة على بُعد نقرة واحدة',
  'onboardingPage3Highlight3': 'مصمم كأداة احترافية، لا كعرض تجريبي',
  'onboardingStart': 'ابدأ الترجمة',
  'onboardingNext': 'التالي',
  'onboardingSkip': 'تخطي',
  'onboardingContinue': 'متابعة',
  'onboardingEnterApp': 'الدخول إلى SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'ترجمة الترجمة بالذكاء الاصطناعي',
  'splashPreparing': 'جارٍ تجهيز استوديو الترجمة الخاص بك',
  'brandSubtitleCompact': 'ذكاء الترجمة',
  'brandSubtitleFull': 'استوديو ترجمة الترجمة بالذكاء الاصطناعي',
  'comingSoonTitle': 'قريبًا',
  'comingSoonMessage': 'ما زلنا نجهّز هذه الشاشة.',
};
