const Map<String, String> kStringsFa = <String, String>{
  'appTitle': 'ساب‌فلیکس',
  'searchTitles': 'جستجوی عناوین',
  'searchMovieOrSeriesTitle': 'جستجوی فیلم یا سریال',
  'searchMovieOrSeriesSubtitle':
      'عنوان موردنظر را پیدا کنید، منابع زیرنویس را بررسی کنید و با چند لمس ترجمه را شروع کنید.',
  'searchHintText': 'جستجو برای Dune، Breaking Bad، Severance...',
  'searchMockTitle': 'جستجو در کاتالوگ آزمایشی',
  'searchMockMessage':
      'برای بررسی روند انتخاب منبع زیرنویس، عنوان‌هایی مثل Inception، Dune، Breaking Bad، Severance یا The Last of Us را جستجو کنید.',
  'searchFailedTitle': 'جستجو انجام نشد',
  'noTitlesMatchedTitle': 'نتیجه‌ای پیدا نشد',
  'noTitlesMatchedMessage':
      'این عنوان در کاتالوگ آزمایشی پیدا نشد. یک عبارت کلی‌تر جستجو کنید یا یکی از عنوان‌های پیشنهادی را امتحان کنید.',
  'retry': 'تلاش دوباره',
  'retryTranslation': 'تلاش دوباره برای ترجمه',
  'uploadSubtitleTitle': 'آپلود زیرنویس',
  'uploadIntroTitle': 'افزودن فایل زیرنویس',
  'uploadIntroSubtitle':
      'یک فایل انگلیسی با فرمت `.srt` یا `.vtt` انتخاب کنید تا بررسی و پردازش شود، سپس به مرحله تنظیمات ترجمه بروید.',
  'uploadChooseFile': 'انتخاب فایل زیرنویس',
  'uploadSupportedFormatsTitle': 'فرمت‌های پشتیبانی‌شده',
  'uploadSupportedFormatsSubtitle': 'فایل‌های زیرنویس انگلیسی `.srt` و `.vtt`',
  'uploadOpeningPicker': 'در حال باز کردن فایل‌ها...',
  'uploadChooseFileShort': 'انتخاب فایل',
  'uploadPickSubtitle': 'انتخاب فایل زیرنویس',
  'uploadPickedFile': 'فایل زیرنویس انتخاب شد',
  'uploadUseDemoFile': 'استفاده از فایل نمونه',
  'uploadFailedTitle': 'خواندن فایل انجام نشد',
  'uploadFailedMessage':
      'امکان خواندن این فایل زیرنویس وجود ندارد. لطفاً فایل دیگری را انتخاب کنید یا از فایل کوچک‌تری استفاده کنید.',
  'uploadFailedFallback': 'لطفاً فایل زیرنویس دیگری را انتخاب کنید.',
  'tryAgain': 'تلاش دوباره',
  'uploadMetadataTitle': 'جزئیات زیرنویس',
  'uploadReadyTitle': 'آماده ترجمه',
  'uploadLineCount': '{lineCount} خط',
  'uploadEnglishSource': 'منبع انگلیسی',
  'uploadContinueSetup': 'ادامه به تنظیمات ترجمه',
  'translateSetupTitle': 'تنظیمات ترجمه',
  'translateSetupSubtitle':
      'زبان مقصد را انتخاب کنید، منبع زیرنویس را بررسی کنید و ترجمه را شروع کنید.',
  'subtitleSourceFormatLabel': 'زیرنویس {format}',
  'targetLanguage': 'زبان مقصد',
  'startTranslation': 'شروع ترجمه',
  'translationProgressTitle': 'وضعیت ترجمه',
  'translationProgressHeadline': 'ترجمه زیرنویس با هوش مصنوعی در حال انجام است',
  'translationFailedTitle': 'ترجمه کامل نشد',
  'translationFailedMessage': 'مشکلی پیش آمده است.',
  'translationStageQueued': 'در صف ترجمه',
  'translationStageIdle': 'در انتظار درخواست ترجمه',
  'translationStagePreparing': 'در حال آماده‌سازی زیرنویس',
  'translationStageAligning': 'در حال هماهنگ‌سازی زمان‌بندی و صحنه‌ها',
  'translationStageGenerating': 'در حال ترجمه زیرنویس',
  'translationStageReadability': 'در حال بهبود خوانایی',
  'translationStageReady': 'ترجمه آماده است',
  'translationPreviewTitle': 'پیش‌نمایش ترجمه',
  'translationPreviewHeader': 'بررسی زیرنویس ترجمه‌شده',
  'translationPreviewSubtitle':
      'در میان خطوط جستجو کنید، حالت نمایش را تغییر دهید و پس از بررسی، خروجی بگیرید.',
  'translationPreviewSearchHint': 'جستجو در زیرنویس',
  'previewModeOriginal': 'اصلی',
  'previewModeTranslated': 'ترجمه',
  'previewModeBilingual': 'دوزبانه',
  'previewNotReadyTitle': 'پیش‌نمایش هنوز آماده نیست',
  'previewNotReadyMessage':
      'ترجمه انجام شده است، اما پیش‌نمایش هنوز آماده نیست. لطفاً کمی بعد دوباره این صفحه را باز کنید.',
  'previewNoMatchesTitle': 'موردی پیدا نشد',
  'previewNoMatchesMessage':
      'لطفاً عبارت دیگری را جستجو کنید یا فیلتر را پاک کنید تا همه خطوط نمایش داده شوند.',
  'previewFailedTitle': 'بارگذاری پیش‌نمایش انجام نشد',
  'exportingLabel': 'در حال گرفتن خروجی...',
  'exportSubtitleLabel': 'خروجی گرفتن از زیرنویس ترجمه‌شده',
  'exportedSnack': '{fileName} در {path} ذخیره شد',
  'exportFailedSnack': 'گرفتن خروجی انجام نشد: {error}',
  'metadataFormat': 'فرمت',
  'metadataLines': 'تعداد خطوط',
  'metadataLanguages': 'زبان‌ها',
  'metadataEstimatedDuration': 'مدت تقریبی',
  'subtitleSourcesTitle': 'منابع زیرنویس انگلیسی',
  'subtitleSourcesSubtitle':
      'یک منبع زیرنویس برای {title}{target} انتخاب کنید، سپس در مرحله بعد زبان مقصد را مشخص کنید.',
  'subtitleSourcesFailedTitle': 'بارگذاری منابع زیرنویس انجام نشد',
  'seriesSeasonsTitle': 'انتخاب فصل',
  'seriesSeasonsSubtitle':
      'برای مشاهده قسمت‌های موجود، یکی از فصل‌های {title} را انتخاب کنید.',
  'seriesSeasonLabel': 'فصل {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} قسمت{year}',
  'seriesEpisodesTitle': 'فصل {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} قسمت{year}',
  'seriesEpisodeLabel': 'قسمت {episodeNumber}',
  'seriesEpisodeMeta': 'حدود {runtime} دقیقه',
  'historyTitle': 'تاریخچه ترجمه',
  'historySubtitle':
      'ترجمه‌های قبلی را دوباره باز کنید، پیش‌نمایش را ببینید یا بعداً خروجی بگیرید.',
  'historyEmptyTitle': 'تاریخچه خالی است',
  'historyEmptyMessage':
      'پس از تکمیل ترجمه‌ها، موارد انجام‌شده در این بخش نمایش داده می‌شوند.',
  'historyFailedTitle': 'بارگذاری تاریخچه انجام نشد',
  'homeRecentJobsTitle': 'ترجمه‌های اخیر',
  'homeRecentJobsSubtitle':
      'آخرین ترجمه‌های خود را بدون نیاز به شروع دوباره باز کنید.',
  'homeNoRecentTitle': 'هنوز ترجمه‌ای وجود ندارد',
  'homeNoRecentMessage':
      'با جستجوی فیلم یا آپلود فایل زیرنویس شروع کنید تا ترجمه‌های اخیر در این بخش نمایش داده شوند.',
  'homeFailedRecentTitle': 'بارگذاری ترجمه‌های اخیر انجام نشد',
  'homeTrustTitle': 'چرا تیم‌ها به این محصول اعتماد می‌کنند',
  'homeTrustSubtitle':
      'این نسخه فعلاً آزمایشی است، اما از ابتدا مانند یک محصول واقعی طراحی شده است.',
  'homeFutureTitle': 'آماده برای توسعه در آینده',
  'homeFutureSubtitle':
      'ساختار ریپازیتوری‌ها به‌گونه‌ای طراحی شده است که رابط کاربری از تغییرات بک‌اند جدا بماند.',
  'homePreviewTitle': 'ترجمه همراه با پیش‌نمایش',
  'homePreviewSubtitle':
      'پیش از گرفتن خروجی، نتیجه را در حالت اصلی، ترجمه یا دوزبانه بررسی کنید.',
  'homeStatesTitle': 'همه وضعیت‌ها از ابتدا در نظر گرفته شده‌اند',
  'homeStatesSubtitle':
      'حالت‌های بارگذاری، خالی، تلاش دوباره، اعتبارسنجی و حتی حالت آفلاین آزمایشی از ابتدا در تجربه کاربری لحاظ شده‌اند.',
  'navHome': 'خانه',
  'navHistory': 'تاریخچه',
  'navSettings': 'تنظیمات',
  'heroTitle': 'زیرنویس را سریع‌تر ترجمه کنید',
  'heroSubtitle':
      'فیلم و سریال را جستجو کنید، منبع زیرنویس را انتخاب کنید و در چند دقیقه خروجی بگیرید.',
  'heroBadge': 'تجربه حرفه‌ای ترجمه زیرنویس',
  'heroHeadline': 'زیرنویس فیلم و سریال را با یک روند حرفه‌ای ترجمه کنید.',
  'heroBody':
      'می‌توانید جستجو در کاتالوگ را انتخاب کنید یا فایل زیرنویس را مستقیم آپلود کنید، سپس پیش‌نمایش ببینید و خروجی بگیرید.',
  'heroSearchCta': 'جستجوی فیلم / سریال',
  'heroUploadCta': 'آپلود زیرنویس',
  'heroStatPathsTitle': '۲ مسیر',
  'heroStatPathsValue': 'جستجو یا آپلود',
  'heroStatLanguagesTitle': '۱۰ زبان',
  'heroStatLanguagesValue': 'آماده پیش‌نمایش',
  'heroStatMockTitle': 'API آزمایشی',
  'heroStatMockValue': 'آماده اتصال به بک‌اند',
  'settingsTitle': 'تنظیمات',
  'settingsSubtitle':
      'تنظیمات پیش‌فرض ترجمه، ظاهر برنامه، اطلاعات اپ و گزینه‌های آزمایشی پریمیوم را مدیریت کنید.',
  'settingsLanguageLabel': 'زبان مقصد پیش‌فرض',
  'settingsThemeLabel': 'ظاهر',
  'themeSystem': 'سیستم',
  'themeDark': 'تیره',
  'themeLight': 'روشن',
  'settingsPremiumTitle': 'بخش پریمیوم آزمایشی',
  'settingsPremiumSubtitle':
      'بعداً می‌توان امکان اشتراک، پرداخت و همگام‌سازی ابری را در این بخش اضافه کرد.',
  'settingsSupportTitle': 'بخش پشتیبانی آزمایشی',
  'settingsSupportSubtitle': 'صفحه راهنما و تماس آزمایشی',
  'settingsPrivacyTitle': 'حریم خصوصی',
  'settingsPrivacySubtitle': 'محتوای آزمایشی حریم خصوصی',
  'settingsTermsTitle': 'شرایط استفاده',
  'settingsTermsSubtitle': 'محتوای آزمایشی شرایط استفاده',
  'settingsMaintenanceTitle': 'نگهداری',
  'settingsMaintenanceSubtitle':
      'ترجمه‌های ذخیره‌شده این دستگاه را پاک کنید و با تاریخچه خالی شروع کنید.',
  'settingsHistoryClearedSnack': 'تاریخچه ترجمه این دستگاه پاک شد',
  'settingsAboutTitle': 'درباره SubFlix',
  'settingsVersion': 'نسخه {version}',
  'settingsClearCache': 'پاک کردن کش',
  'settingsCacheCleared': 'کش پاک شد',
  'settingsFailedTitle': 'بارگذاری تنظیمات انجام نشد',
  'legalPlaceholderBody':
      'این صفحه در نسخه دمو فقط یک بخش نمونه است. می‌توانید بعداً محتوای حقوقی واقعی را به آن اضافه کنید.',
  'legalTitlePrivacy': 'حریم خصوصی',
  'legalTitleTerms': 'شرایط استفاده',
  'legalTitleSupport': 'پشتیبانی',
  'legalTitleAbout': 'درباره SubFlix',
  'legalBodyPrivacy':
      'SubFlix در حال حاضر فقط تنظیمات آزمایشی و تاریخچه ترجمه را به‌صورت محلی روی دستگاه ذخیره می‌کند. در آینده این بخش می‌تواند با ذخیره‌سازی امن، گزارش‌های سیستمی و سیاست‌های نگهداری سمت سرور جایگزین شود.',
  'legalBodyTerms':
      'این نسخه آزمایشی برای بررسی روندهای محصول، وضعیت‌های رابط کاربری و ساختار معماری طراحی شده است. پس از اتصال بک‌اند واقعی NestJS و پایگاه داده Postgres، این بخش می‌تواند با شرایط واقعی سرویس تکمیل شود.',
  'legalBodySupport':
      'پشتیبانی فعلاً فقط جنبه نمایشی دارد. در نسخه نهایی می‌تواند به ایمیل، گزارش مشکل و پشتیبانی حساب‌های پریمیوم متصل شود.',
  'legalBodyAbout':
      'SubFlix یک اپ Flutter با ظاهر حرفه‌ای برای ترجمه زیرنویس با هوش مصنوعی است. این نسخه از ریپازیتوری‌های آزمایشی، تأخیر مصنوعی و ذخیره‌سازی محلی استفاده می‌کند تا پیش از اتصال به بک‌اند واقعی، رابط کاربری و معماری به‌خوبی شکل بگیرند.',
  'routeMissingSubtitleSourcesTitle': 'منابع زیرنویس',
  'routeMissingSubtitleSourcesMessage':
      'مشخص نیست منابع زیرنویس مربوط به کدام عنوان باید بارگذاری شوند. لطفاً دوباره از بخش جستجو شروع کنید.',
  'routeMissingSeriesSeasonsTitle': 'فصل‌های سریال',
  'routeMissingSeriesSeasonsMessage':
      'مشخص نیست کدام سریال باید بارگذاری شود. لطفاً دوباره از بخش جستجو شروع کنید.',
  'routeMissingSeasonEpisodesTitle': 'قسمت‌های فصل',
  'routeMissingSeasonEpisodesMessage':
      'مشخص نیست کدام فصل باید بارگذاری شود. لطفاً دوباره از بخش جستجو شروع کنید.',
  'routeMissingTranslationSetupTitle': 'تنظیمات ترجمه',
  'routeMissingTranslationSetupMessage':
      'برای باز کردن صفحه تنظیمات ترجمه، باید یک منبع زیرنویس انتخاب شده باشد.',
  'routeMissingTranslationProgressTitle': 'وضعیت ترجمه',
  'routeMissingTranslationProgressMessage':
      'هیچ درخواست ترجمه‌ای ثبت نشده است. لطفاً از طریق جستجو یا آپلود، یک ترجمه جدید شروع کنید.',
  'searchResultPopularity': 'محبوبیت {score}',
  'subtitleSourceLines': '{lineCount} خط',
  'subtitleSourceDownloads': '{downloads} دانلود',
  'subtitleSourceRating': 'امتیاز {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'فیلم',
  'mediaTypeSeries': 'سریال',
  'jobReuseTranslation': 'استفاده دوباره از ترجمه',
  'jobReuseSubtitle': 'استفاده دوباره از زیرنویس',
  'jobConfidence': 'میزان اطمینان: {level}',
  'jobOpenPreview': 'باز کردن پیش‌نمایش',
  'onboardingPage1Title':
      'فیلم یا سریال را پیدا کنید و زیرنویس آماده ترجمه دریافت کنید.',
  'onboardingPage1Eyebrow': 'جستجو و دریافت',
  'onboardingPage1Description':
      'یک عنوان را جستجو کنید، منابع زیرنویس انگلیسی را ببینید و ترجمه را خیلی سریع شروع کنید.',
  'onboardingPage1Highlight1': 'کاتالوگ آزمایشی پایدار برای توسعه مطمئن',
  'onboardingPage1Highlight2': 'برچسب کیفیت و فرمت برای منابع زیرنویس',
  'onboardingPage1Highlight3': 'آماده برای اتصال به بک‌اند واقعی در آینده',
  'onboardingPage2Title':
      'اگر فایل زیرنویس را دارید، فایل `.srt` یا `.vtt` را آپلود کنید.',
  'onboardingPage2Eyebrow': 'افزودن فایل شخصی',
  'onboardingPage2Description':
      'فایل زیرنویس را وارد کنید، فرمت را بررسی کنید و بدون خروج از برنامه همان روند ترجمه را ادامه دهید.',
  'onboardingPage2Highlight1':
      'بررسی فایل روی دستگاه همراه با مدیریت مناسب خطاها',
  'onboardingPage2Highlight2': 'تنظیمات یکپارچه برای آپلود و جستجو',
  'onboardingPage2Highlight3': 'پیش از گرفتن خروجی، پیش‌نمایش را ببینید',
  'onboardingPage3Title':
      'زبان مقصد را انتخاب کنید، پیش‌نمایش ببینید و بلافاصله خروجی بگیرید.',
  'onboardingPage3Eyebrow': 'ترجمه و خروجی',
  'onboardingPage3Description':
      'بین حالت اصلی، ترجمه و دوزبانه جابه‌جا شوید، تاریخچه را دوباره ببینید و وقتی نتیجه مناسب بود خروجی بگیرید.',
  'onboardingPage3Highlight1': 'پیش‌نمایش سریع همراه با متادیتا و جستجو',
  'onboardingPage3Highlight2':
      'تاریخچه، ترجمه‌های قبلی را فقط با یک لمس در دسترس نگه می‌دارد',
  'onboardingPage3Highlight3':
      'طراحی‌شده مانند یک ابزار حرفه‌ای، نه یک دمو ساده',
  'onboardingStart': 'شروع ترجمه',
  'onboardingNext': 'بعدی',
  'onboardingSkip': 'رد کردن',
  'onboardingContinue': 'ادامه',
  'onboardingEnterApp': 'ورود به SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'ترجمه زیرنویس با هوش مصنوعی',
  'splashPreparing': 'در حال آماده‌سازی استودیوی زیرنویس شما',
  'brandSubtitleCompact': 'هوش زیرنویس',
  'brandSubtitleFull': 'استودیوی ترجمه زیرنویس با هوش مصنوعی',
  'comingSoonTitle': 'به‌زودی',
  'comingSoonMessage': 'این صفحه هنوز آماده نشده است.',
};
