const Map<String, String> kStringsPt = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Pesquisar t?tulos',
  'searchMovieOrSeriesTitle': 'Pesquisar filme ou s?rie',
  'searchMovieOrSeriesSubtitle': 'Encontre um t?tulo, veja as fontes e inicie a tradu??o.',
  'searchHintText': 'Pesquisar Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Pesquisar no cat?logo demo',
  'searchMockMessage': 'Tente Inception, Dune, Breaking Bad, Severance.',
  'searchFailedTitle': 'Falha na pesquisa',
  'noTitlesMatchedTitle': 'Nenhum t?tulo encontrado',
  'noTitlesMatchedMessage': 'N?o encontramos no cat?logo demo. Tente outra busca.',
  'retry': 'Tentar novamente',
  'retryTranslation': 'Repetir tradu??o',
  'uploadSubtitleTitle': 'Enviar legenda',
  'uploadIntroTitle': 'Use seu arquivo de legenda',
  'uploadIntroSubtitle': 'Importe um arquivo `.srt` ou `.vtt` em ingl?s.',
  'uploadChooseFile': 'Escolher arquivo',
  'uploadSupportedFormatsTitle': 'Formatos suportados',
  'uploadSupportedFormatsSubtitle': 'Arquivos `.srt` e `.vtt` em ingl?s',
  'uploadOpeningPicker': 'Abrindo seletor...',
  'uploadChooseFileShort': 'Escolher',
  'uploadPickSubtitle': 'Selecionar arquivo de legenda',
  'uploadPickedFile': 'Arquivo selecionado',
  'uploadUseDemoFile': 'Usar arquivo demo',
  'uploadFailedTitle': 'Falha ao importar',
  'uploadFailedMessage': 'N?o foi poss?vel ler o arquivo. Tente outro.',
  'uploadFailedFallback': 'Tente outro arquivo.',
  'tryAgain': 'Tente novamente',
  'uploadMetadataTitle': 'Detalhes da legenda',
  'uploadReadyTitle': 'Pronto para traduzir',
  'uploadLineCount': '{lineCount} linhas',
  'uploadEnglishSource': 'Fonte em ingl?s',
  'uploadContinueSetup': 'Continuar configura??o',
  'translateSetupTitle': 'Configura??o de tradu??o',
  'translateSetupSubtitle': 'Escolha o idioma e inicie a tradu??o.',
  'subtitleSourceFormatLabel': 'Fonte {format}',
  'targetLanguage': 'Idioma alvo',
  'startTranslation': 'Iniciar tradu??o',
  'translationProgressTitle': 'Progresso',
  'translationProgressHeadline': 'Tradu??o com IA em andamento',
  'translationFailedTitle': 'Tradu??o falhou',
  'translationFailedMessage': 'Algo deu errado.',
  'translationStageQueued': 'Na fila',
  'translationStageIdle': 'Aguardando solicita??o',
  'translationStagePreparing': 'Preparando pacote',
  'translationStageAligning': 'Ajustando tempos',
  'translationStageGenerating': 'Gerando tradu??o',
  'translationStageReadability': 'Melhorando legibilidade',
  'translationStageReady': 'Tradu??o pronta',
  'translationPreviewTitle': 'Pr?-visualiza??o',
  'translationPreviewHeader': 'Revisar tradu??o',
  'translationPreviewSubtitle': 'Pesquise, altere o modo e exporte.',
  'translationPreviewSearchHint': 'Pesquisar legendas',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': 'Traduzido',
  'previewModeBilingual': 'Bil?ngue',
  'previewNotReadyTitle': 'Pr?via indispon?vel',
  'previewNotReadyMessage': 'A tradu??o acabou, mas a pr?via n?o chegou.',
  'previewNoMatchesTitle': 'Nenhuma linha encontrada',
  'previewNoMatchesMessage': 'Tente outro termo ou limpe o filtro.',
  'previewFailedTitle': 'Falha ao carregar pr?via',
  'exportingLabel': 'Exportando...',
  'exportSubtitleLabel': 'Exportar legenda traduzida',
  'exportedSnack': '{fileName} exportado para {path}',
  'exportFailedSnack': 'Falha na exporta??o: {error}',
  'metadataFormat': 'Formato',
  'metadataLines': 'Linhas',
  'metadataLanguages': 'Idiomas',
  'metadataEstimatedDuration': 'Dura??o estimada',
  'subtitleSourcesTitle': 'Fontes de legenda em ingl?s',
  'subtitleSourcesSubtitle': 'Escolha uma fonte para {title}{target}.',
  'subtitleSourcesFailedTitle': 'Falha ao carregar fontes',
  'seriesSeasonsTitle': 'Escolher temporada',
  'seriesSeasonsSubtitle': 'Escolha a temporada de {title}.',
  'seriesSeasonLabel': 'Temporada {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} epis?dios{year}',
  'seriesEpisodesTitle': 'Temporada {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} epis?dios{year}',
  'seriesEpisodeLabel': 'Epis?dio {episodeNumber}',
  'seriesEpisodeMeta': 'Aprox. {runtime} min',
  'historyTitle': 'Hist?rico',
  'historySubtitle': 'Reabra trabalhos anteriores.',
  'historyEmptyTitle': 'Hist?rico vazio',
  'historyEmptyMessage': 'Os trabalhos aparecer?o aqui ap?s completar.',
  'historyFailedTitle': 'Falha ao carregar hist?rico',
  'homeRecentJobsTitle': 'Trabalhos recentes',
  'homeRecentJobsSubtitle': 'Reabra sess?es recentes rapidamente.',
  'homeNoRecentTitle': 'Sem trabalhos recentes',
  'homeNoRecentMessage': 'Comece pela busca ou upload.',
  'homeFailedRecentTitle': 'Falha ao carregar trabalhos recentes',
  'homeTrustTitle': 'Por que confiar',
  'homeTrustSubtitle': 'Hoje mock, pronto para produ??o.',
  'homeFutureTitle': 'Reposit?rios prontos para o futuro',
  'homeFutureSubtitle': 'UI isolada do backend.',
  'homePreviewTitle': 'Fluxo com pr?via',
  'homePreviewSubtitle': 'Revise antes de exportar.',
  'homeStatesTitle': 'Estados completos',
  'homeStatesSubtitle': 'Loading, vazio e retry inclu?dos.',
  'navHome': 'In?cio',
  'navHistory': 'Hist?rico',
  'navSettings': 'Configura??es',
  'heroTitle': 'Traduza legendas mais r?pido',
  'heroSubtitle': 'Pesquise, escolha e exporte em minutos.',
  'heroBadge': 'Fluxo premium',
  'heroHeadline': 'Tradu??o n?vel est?dio',
  'heroBody': 'Escolha busca ou upload e exporte.',
  'heroSearchCta': 'Buscar filme / s?rie',
  'heroUploadCta': 'Enviar legenda',
  'heroStatPathsTitle': '2 caminhos',
  'heroStatPathsValue': 'Busca ou upload',
  'heroStatLanguagesTitle': '10 idiomas',
  'heroStatLanguagesValue': 'Pronto para pr?via',
  'heroStatMockTitle': 'APIs mock',
  'heroStatMockValue': 'Backend pronto',
  'settingsTitle': 'Configura??es',
  'settingsSubtitle': 'Gerencie idioma, visual e informa??es.',
  'settingsLanguageLabel': 'Idioma alvo preferido',
  'settingsThemeLabel': 'Apar?ncia',
  'themeSystem': 'Sistema',
  'themeDark': 'Escuro',
  'themeLight': 'Claro',
  'settingsPremiumTitle': 'Premium (placeholder)',
  'settingsPremiumSubtitle': 'Assinatura ser? conectada depois.',
  'settingsSupportTitle': 'Suporte (placeholder)',
  'settingsSupportSubtitle': 'P?gina de suporte demo',
  'settingsPrivacyTitle': 'Pol?tica de privacidade',
  'settingsPrivacySubtitle': 'Conte?do demo',
  'settingsTermsTitle': 'Termos de servi?o',
  'settingsTermsSubtitle': 'Conte?do demo',
  'settingsMaintenanceTitle': 'Manuten??o',
  'settingsMaintenanceSubtitle': 'Limpar hist?rico deste dispositivo.',
  'settingsHistoryClearedSnack': 'Hist?rico limpo',
  'settingsAboutTitle': 'Sobre o SubFlix',
  'settingsVersion': 'Vers?o {version}',
  'settingsClearCache': 'Limpar cache',
  'settingsCacheCleared': 'Cache limpo',
  'settingsFailedTitle': 'Falha ao carregar configura??es',
  'legalPlaceholderBody': 'Esta p?gina ? um placeholder.',
  'legalTitlePrivacy': 'Privacidade',
  'legalTitleTerms': 'Termos',
  'legalTitleSupport': 'Suporte',
  'legalTitleAbout': 'Sobre',
  'legalBodyPrivacy': 'Somente prefer?ncias mock s?o salvas.',
  'legalBodyTerms': 'Vers?o destinada a testes.',
  'legalBodySupport': 'Suporte ser? conectado depois.',
  'legalBodyAbout': 'Cliente Flutter para tradu??o de legendas.',
  'routeMissingSubtitleSourcesTitle': 'Fontes de legenda',
  'routeMissingSubtitleSourcesMessage': 'N?o foi poss?vel identificar o t?tulo.',
  'routeMissingSeriesSeasonsTitle': 'Temporadas',
  'routeMissingSeriesSeasonsMessage': 'N?o foi poss?vel identificar a s?rie.',
  'routeMissingSeasonEpisodesTitle': 'Epis?dios',
  'routeMissingSeasonEpisodesMessage': 'N?o foi poss?vel identificar a temporada.',
  'routeMissingTranslationSetupTitle': 'Configura??o',
  'routeMissingTranslationSetupMessage': 'Fonte necess?ria.',
  'routeMissingTranslationProgressTitle': 'Progresso',
  'routeMissingTranslationProgressMessage': 'Sem solicita??o de tradu??o.',
  'searchResultPopularity': 'Popularidade {score}',
  'subtitleSourceLines': '{lineCount} linhas',
  'subtitleSourceDownloads': '{downloads} downloads',
  'subtitleSourceRating': 'Nota {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Filme',
  'mediaTypeSeries': 'S?rie',
  'jobReuseTranslation': 'Reutilizar tradu??o',
  'jobReuseSubtitle': 'Reutilizar legenda',
  'jobConfidence': 'Confian?a: {level}',
  'jobOpenPreview': 'Abrir pr?via',
  'onboardingPage1Title': 'Encontre filmes ou s?ries.',
  'onboardingPage1Eyebrow': 'Buscar e encontrar',
  'onboardingPage1Description': 'Busque e revise as fontes.',
  'onboardingPage1Highlight1': 'Cat?logo mock confi?vel',
  'onboardingPage1Highlight2': 'Selos de qualidade',
  'onboardingPage1Highlight3': 'Pronto para backend real',
  'onboardingPage2Title': 'Envie `.srt` ou `.vtt`.',
  'onboardingPage2Eyebrow': 'Seu arquivo',
  'onboardingPage2Description': 'Importe e siga o fluxo.',
  'onboardingPage2Highlight1': 'Valida??o local',
  'onboardingPage2Highlight2': 'Setup consistente',
  'onboardingPage2Highlight3': 'Pr?via antes de exportar',
  'onboardingPage3Title': 'Escolha idioma e exporte.',
  'onboardingPage3Eyebrow': 'Traduzir e exportar',
  'onboardingPage3Description': 'Mude os modos e exporte.',
  'onboardingPage3Highlight1': 'Controles r?pidos de pr?via',
  'onboardingPage3Highlight2': 'Hist?rico sempre dispon?vel',
  'onboardingPage3Highlight3': 'Design premium',
  'onboardingStart': 'Come?ar',
  'onboardingNext': 'Pr?ximo',
  'onboardingSkip': 'Pular',
  'onboardingContinue': 'Continuar',
  'onboardingEnterApp': 'Entrar no SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'Tradu??o de legendas com IA',
  'splashPreparing': 'Preparando o est?dio',
  'brandSubtitleCompact': 'Intelig?ncia de legendas',
  'brandSubtitleFull': 'Est?dio de tradu??o com IA',
  'comingSoonTitle': 'Em breve',
  'comingSoonMessage': 'Esta tela est? sendo preparada.',
};
