const Map<String, String> kStringsDe = <String, String>{
  'appTitle': 'SubFlix',
  'searchTitles': 'Titel suchen',
  'searchMovieOrSeriesTitle': 'Film oder Serie suchen',
  'searchMovieOrSeriesSubtitle': 'Titel finden, Quellen pr?fen und ?bersetzung starten.',
  'searchHintText': 'Suche nach Dune, Breaking Bad, Severance...',
  'searchMockTitle': 'Im Demo-Katalog suchen',
  'searchMockMessage': 'Probiere Inception, Dune, Breaking Bad, Severance, The Last of Us.',
  'searchFailedTitle': 'Suche fehlgeschlagen',
  'noTitlesMatchedTitle': 'Keine Treffer',
  'noTitlesMatchedMessage': 'Titel nicht im Demo-Katalog gefunden. Suche erweitern.',
  'retry': 'Erneut versuchen',
  'retryTranslation': '?bersetzung erneut starten',
  'uploadSubtitleTitle': 'Untertitel hochladen',
  'uploadIntroTitle': 'Eigenen Untertitel hochladen',
  'uploadIntroSubtitle': 'Eine englische `.srt` oder `.vtt` Datei importieren.',
  'uploadChooseFile': 'Datei ausw?hlen',
  'uploadSupportedFormatsTitle': 'Unterst?tzte Formate',
  'uploadSupportedFormatsSubtitle': 'Englische `.srt` und `.vtt` Dateien',
  'uploadOpeningPicker': '?ffne Auswahl...',
  'uploadChooseFileShort': 'Ausw?hlen',
  'uploadPickSubtitle': 'Untertiteldatei w?hlen',
  'uploadPickedFile': 'Datei ausgew?hlt',
  'uploadUseDemoFile': 'Demo-Datei nutzen',
  'uploadFailedTitle': 'Import fehlgeschlagen',
  'uploadFailedMessage': 'Datei konnte nicht gelesen werden. Andere Datei w?hlen.',
  'uploadFailedFallback': 'Bitte andere Datei versuchen.',
  'tryAgain': 'Erneut versuchen',
  'uploadMetadataTitle': 'Untertitel-Details',
  'uploadReadyTitle': 'Bereit zur ?bersetzung',
  'uploadLineCount': '{lineCount} Zeilen',
  'uploadEnglishSource': 'Englische Quelle',
  'uploadContinueSetup': 'Weiter zur Einrichtung',
  'translateSetupTitle': '?bersetzung einrichten',
  'translateSetupSubtitle': 'Zielsprache w?hlen und ?bersetzung starten.',
  'subtitleSourceFormatLabel': '{format}-Quelle',
  'targetLanguage': 'Zielsprache',
  'startTranslation': '?bersetzung starten',
  'translationProgressTitle': 'Fortschritt',
  'translationProgressHeadline': 'KI-?bersetzung l?uft',
  'translationFailedTitle': '?bersetzung fehlgeschlagen',
  'translationFailedMessage': 'Etwas ist schiefgelaufen.',
  'translationStageQueued': 'In Warteschlange',
  'translationStageIdle': 'Warten auf Anfrage',
  'translationStagePreparing': 'Paket wird vorbereitet',
  'translationStageAligning': 'Zeitstempel werden angepasst',
  'translationStageGenerating': '?bersetzung wird erstellt',
  'translationStageReadability': 'Lesbarkeit verbessern',
  'translationStageReady': '?bersetzung bereit',
  'translationPreviewTitle': 'Vorschau',
  'translationPreviewHeader': '?bersetzte Untertitel pr?fen',
  'translationPreviewSubtitle': 'Im Text suchen, Modus wechseln, dann exportieren.',
  'translationPreviewSearchHint': 'Untertitel durchsuchen',
  'previewModeOriginal': 'Original',
  'previewModeTranslated': '?bersetzt',
  'previewModeBilingual': 'Zweisprachig',
  'previewNotReadyTitle': 'Vorschau noch nicht verf?gbar',
  'previewNotReadyMessage': '?bersetzung fertig, aber Vorschau fehlt noch.',
  'previewNoMatchesTitle': 'Keine passenden Zeilen',
  'previewNoMatchesMessage': 'Anderen Begriff versuchen oder Filter l?schen.',
  'previewFailedTitle': 'Vorschau konnte nicht geladen werden',
  'exportingLabel': 'Exportiere...',
  'exportSubtitleLabel': '?bersetzung exportieren',
  'exportedSnack': '{fileName} exportiert nach {path}',
  'exportFailedSnack': 'Export fehlgeschlagen: {error}',
  'metadataFormat': 'Format',
  'metadataLines': 'Zeilen',
  'metadataLanguages': 'Sprachen',
  'metadataEstimatedDuration': 'Gesch?tzte Dauer',
  'subtitleSourcesTitle': 'Englische Untertitelquellen',
  'subtitleSourcesSubtitle': 'Quelle f?r {title}{target} w?hlen.',
  'subtitleSourcesFailedTitle': 'Quellen konnten nicht geladen werden',
  'seriesSeasonsTitle': 'Staffel w?hlen',
  'seriesSeasonsSubtitle': 'Staffel von {title} w?hlen, um Episoden zu sehen.',
  'seriesSeasonLabel': 'Staffel {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} Episoden{year}',
  'seriesEpisodesTitle': 'Staffel {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} Episoden{year}',
  'seriesEpisodeLabel': 'Episode {episodeNumber}',
  'seriesEpisodeMeta': 'Ca. {runtime} Min',
  'historyTitle': '?bersetzungsverlauf',
  'historySubtitle': 'Vergangene Jobs erneut ?ffnen.',
  'historyEmptyTitle': 'Verlauf leer',
  'historyEmptyMessage': 'Jobs erscheinen hier nach Abschluss eines Flows.',
  'historyFailedTitle': 'Verlauf konnte nicht geladen werden',
  'homeRecentJobsTitle': 'Neueste Jobs',
  'homeRecentJobsSubtitle': 'Letzte Sitzungen schnell ?ffnen.',
  'homeNoRecentTitle': 'Keine neuen Jobs',
  'homeNoRecentMessage': 'Starte mit Suche oder Upload.',
  'homeFailedRecentTitle': 'Neueste Jobs konnten nicht geladen werden',
  'homeTrustTitle': 'Warum Teams es vertrauen',
  'homeTrustSubtitle': 'Heute Mock, morgen Produkt.',
  'homeFutureTitle': 'Zukunftssichere Repos',
  'homeFutureSubtitle': 'UI unabh?ngig vom Backend.',
  'homePreviewTitle': 'Vorschau zuerst',
  'homePreviewSubtitle': 'Ergebnisse vor Export pr?fen.',
  'homeStatesTitle': 'Zust?nde inklusive',
  'homeStatesSubtitle': 'Loading, Empty, Retry sind integriert.',
  'navHome': 'Start',
  'navHistory': 'Verlauf',
  'navSettings': 'Einstellungen',
  'heroTitle': 'Untertitel schneller ?bersetzen',
  'heroSubtitle': 'Suchen, w?hlen, exportieren ? in Minuten.',
  'heroBadge': 'Premium-Workflow',
  'heroHeadline': 'Studio-Grade ?bersetzung',
  'heroBody': 'Suche oder Upload w?hlen, dann exportieren.',
  'heroSearchCta': 'Film / Serie suchen',
  'heroUploadCta': 'Untertitel hochladen',
  'heroStatPathsTitle': '2 Wege',
  'heroStatPathsValue': 'Suche oder Upload',
  'heroStatLanguagesTitle': '10 Sprachen',
  'heroStatLanguagesValue': 'F?r Vorschau bereit',
  'heroStatMockTitle': 'Mock APIs',
  'heroStatMockValue': 'Backend-ready',
  'settingsTitle': 'Einstellungen',
  'settingsSubtitle': 'Standards, Look & Infos verwalten.',
  'settingsLanguageLabel': 'Bevorzugte Zielsprache',
  'settingsThemeLabel': 'Darstellung',
  'themeSystem': 'System',
  'themeDark': 'Dunkel',
  'themeLight': 'Hell',
  'settingsPremiumTitle': 'Premium (Platzhalter)',
  'settingsPremiumSubtitle': 'Abo-Flow sp?ter.',
  'settingsSupportTitle': 'Support (Platzhalter)',
  'settingsSupportSubtitle': 'Mock-Supportseite',
  'settingsPrivacyTitle': 'Datenschutz',
  'settingsPrivacySubtitle': 'Mock-Inhalte',
  'settingsTermsTitle': 'Nutzungsbedingungen',
  'settingsTermsSubtitle': 'Mock-Inhalte',
  'settingsMaintenanceTitle': 'Wartung',
  'settingsMaintenanceSubtitle': 'Verlauf dieses Ger?ts l?schen.',
  'settingsHistoryClearedSnack': 'Verlauf gel?scht',
  'settingsAboutTitle': '?ber SubFlix',
  'settingsVersion': 'Version {version}',
  'settingsClearCache': 'Cache leeren',
  'settingsCacheCleared': 'Cache gel?scht',
  'settingsFailedTitle': 'Einstellungen konnten nicht geladen werden',
  'legalPlaceholderBody': 'Diese Seite ist ein Platzhalter.',
  'legalTitlePrivacy': 'Datenschutz',
  'legalTitleTerms': 'Nutzungsbedingungen',
  'legalTitleSupport': 'Support',
  'legalTitleAbout': '?ber SubFlix',
  'legalBodyPrivacy': 'Nur Mock-Daten werden gespeichert.',
  'legalBodyTerms': 'Diese Version dient dem UI-Test.',
  'legalBodySupport': 'Support ist aktuell Platzhalter.',
  'legalBodyAbout': 'Premium Flutter-Client f?r Untertitel?bersetzung.',
  'routeMissingSubtitleSourcesTitle': 'Untertitelquellen',
  'routeMissingSubtitleSourcesMessage': 'Titel fehlt. Bitte erneut suchen.',
  'routeMissingSeriesSeasonsTitle': 'Staffeln',
  'routeMissingSeriesSeasonsMessage': 'Serie fehlt. Bitte erneut suchen.',
  'routeMissingSeasonEpisodesTitle': 'Episoden',
  'routeMissingSeasonEpisodesMessage': 'Staffel fehlt. Bitte erneut suchen.',
  'routeMissingTranslationSetupTitle': 'Setup',
  'routeMissingTranslationSetupMessage': 'Quelle erforderlich.',
  'routeMissingTranslationProgressTitle': 'Fortschritt',
  'routeMissingTranslationProgressMessage': 'Keine Anfrage vorhanden.',
  'searchResultPopularity': 'Beliebtheit {score}',
  'subtitleSourceLines': '{lineCount} Zeilen',
  'subtitleSourceDownloads': '{downloads} Downloads',
  'subtitleSourceRating': 'Bewertung {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'Film',
  'mediaTypeSeries': 'Serie',
  'jobReuseTranslation': '?bersetzung wiederverwenden',
  'jobReuseSubtitle': 'Untertitel wiederverwenden',
  'jobConfidence': 'Vertrauen: {level}',
  'jobOpenPreview': 'Vorschau ?ffnen',
  'onboardingPage1Title': 'Film oder Serie finden.',
  'onboardingPage1Eyebrow': 'Suchen & holen',
  'onboardingPage1Description': 'Titel suchen und Quelle pr?fen.',
  'onboardingPage1Highlight1': 'Zuverl?ssiger Mock-Katalog',
  'onboardingPage1Highlight2': 'Qualit?tslabels & Badges',
  'onboardingPage1Highlight3': 'Bereit f?r echtes Backend',
  'onboardingPage2Title': '`.srt` oder `.vtt` hochladen.',
  'onboardingPage2Eyebrow': 'Eigene Datei',
  'onboardingPage2Description': 'Datei importieren und fortfahren.',
  'onboardingPage2Highlight1': 'Lokale Validierung',
  'onboardingPage2Highlight2': 'Einheitliches Setup',
  'onboardingPage2Highlight3': 'Vorschau vor Export',
  'onboardingPage3Title': 'Zielsprache w?hlen und exportieren.',
  'onboardingPage3Eyebrow': '?bersetzen & exportieren',
  'onboardingPage3Description': 'Modus wechseln und exportieren.',
  'onboardingPage3Highlight1': 'Schnelle Vorschau',
  'onboardingPage3Highlight2': 'Verlauf bleibt verf?gbar',
  'onboardingPage3Highlight3': 'Premium-Design',
  'onboardingStart': 'Starten',
  'onboardingNext': 'Weiter',
  'onboardingSkip': '?berspringen',
  'onboardingContinue': 'Fortfahren',
  'onboardingEnterApp': 'SubFlix ?ffnen',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'KI-Untertitel?bersetzung',
  'splashPreparing': 'Studio wird vorbereitet',
  'brandSubtitleCompact': 'Untertitel-Intelligenz',
  'brandSubtitleFull': 'KI-Untertitelstudio',
  'comingSoonTitle': 'Bald verf?gbar',
  'comingSoonMessage': 'Diese Seite wird vorbereitet.',
};
