const Map<String, String> kStringsAr = <String, String>{
  'appTitle': 'ساب فليكس',
  'searchTitles': 'البحث عن العناوين',
  'searchMovieOrSeriesTitle': 'ابحث عن فيلم أو مسلسل',
  'searchMovieOrSeriesSubtitle':
      'اعثر على عنوان، واستعرض مصادر الترجمة، وابدأ مهمة الترجمة ببضع نقرات.',
  'searchHintText': 'ابحث عن Dune أو Breaking Bad أو Severance...',
  'searchMockTitle': 'ابحث عن أي شيء في الكتالوج التجريبي',
  'searchMockMessage':
      'جرّب عناوين مثل Inception أو Dune أو Breaking Bad أو Severance أو The Last of Us لاستكشاف تدفق مصادر الترجمة.',
  'searchFailedTitle': 'فشل البحث',
  'noTitlesMatchedTitle': 'لم يتم العثور على نتائج',
  'noTitlesMatchedMessage':
      'لم نتمكن من العثور على هذا العنوان في الكتالوج التجريبي. جرّب بحثًا أوسع أو أحد العناوين المقترحة.',
  'retry': 'إعادة المحاولة',
  'retryTranslation': 'إعادة محاولة الترجمة',
  'uploadSubtitleTitle': 'رفع الترجمة',
  'uploadIntroTitle': 'أضف ملف الترجمة الخاص بك',
  'uploadIntroSubtitle':
      'استورد ملف `.srt` أو `.vtt` باللغة الإنجليزية، ودَع الخادم يتحقق منه ويحلله، ثم انتقل إلى إعداد الترجمة.',
  'uploadChooseFile': 'اختر ملف الترجمة',
  'uploadSupportedFormatsTitle': 'الصيغ المدعومة',
  'uploadSupportedFormatsSubtitle': 'ملفات الترجمة الإنجليزية `.srt` و `.vtt`',
  'uploadOpeningPicker': 'جارٍ فتح أداة الاختيار...',
  'uploadChooseFileShort': 'اختر ملفًا',
  'uploadPickSubtitle': 'اختر ملف ترجمة',
  'uploadPickedFile': 'تم اختيار ملف الترجمة',
  'uploadUseDemoFile': 'استخدم ملفًا تجريبيًا',
  'uploadFailedTitle': 'فشل استيراد الملف',
  'uploadFailedMessage':
      'تعذر علينا قراءة ملف الترجمة هذا. جرّب ملفًا آخر أو اختر ملفًا أصغر.',
  'uploadFailedFallback': 'يرجى تجربة ملف ترجمة آخر.',
  'tryAgain': 'حاول مرة أخرى',
  'uploadMetadataTitle': 'تفاصيل الترجمة',
  'uploadReadyTitle': 'جاهز للترجمة',
  'uploadLineCount': '{lineCount} سطر',
  'uploadEnglishSource': 'المصدر الإنجليزي',
  'uploadContinueSetup': 'المتابعة إلى إعداد الترجمة',
  'translateSetupTitle': 'إعداد الترجمة',
  'translateSetupSubtitle':
      'اختر اللغة الهدف، وراجع مصدر الترجمة، ثم ابدأ مهمة الترجمة عبر الخادم.',
  'subtitleSourceFormatLabel': 'مصدر ترجمة {format}',
  'targetLanguage': 'اللغة الهدف',
  'startTranslation': 'بدء الترجمة',
  'translationProgressTitle': 'تقدم الترجمة',
  'translationProgressHeadline': 'جارٍ ترجمة الترجمة بالذكاء الاصطناعي',
  'translationFailedTitle': 'تعذر إكمال الترجمة',
  'translationFailedMessage': 'حدث خطأ ما.',
  'translationStageQueued': 'في قائمة الانتظار',
  'translationStageIdle': 'بانتظار طلب الترجمة',
  'translationStagePreparing': 'جارٍ تجهيز حزمة الترجمة',
  'translationStageAligning': 'جارٍ مزامنة التوقيت وسياق المشهد',
  'translationStageGenerating': 'جارٍ إنشاء الترجمة',
  'translationStageReadability': 'جارٍ تحسين قابلية القراءة',
  'translationStageReady': 'الترجمة جاهزة',
  'translationPreviewTitle': 'معاينة الترجمة',
  'translationPreviewHeader': 'راجع الترجمة المترجمة',
  'translationPreviewSubtitle':
      'ابحث داخل الأسطر، وبدّل أوضاع المعاينة، ثم صدّر الملف عندما تصبح الترجمة جاهزة.',
  'translationPreviewSearchHint': 'ابحث في أسطر الترجمة',
  'previewModeOriginal': 'الأصل',
  'previewModeTranslated': 'المترجم',
  'previewModeBilingual': 'ثنائي اللغة',
  'previewNotReadyTitle': 'أسطر المعاينة غير متاحة بعد',
  'previewNotReadyMessage':
      'اكتملت الترجمة، لكن الخادم لم يُرجع أسطر المعاينة بعد. حاول إعادة تحميل هذه الشاشة بعد لحظة.',
  'previewNoMatchesTitle': 'لم يتم العثور على أسطر ترجمة مطابقة',
  'previewNoMatchesMessage':
      'جرّب كلمة بحث مختلفة أو امسح الفلتر لعرض الترجمة كاملة.',
  'previewFailedTitle': 'فشل تحميل المعاينة',
  'exportingLabel': 'جارٍ التصدير...',
  'exportSubtitleLabel': 'تصدير الترجمة المترجمة',
  'exportedSnack': 'تم تصدير {fileName} إلى {path}',
  'exportFailedSnack': 'فشل التصدير: {error}',
  'metadataFormat': 'الصيغة',
  'metadataLines': 'الأسطر',
  'metadataLanguages': 'اللغات',
  'metadataEstimatedDuration': 'المدة التقديرية',
  'subtitleSourcesTitle': 'مصادر الترجمة الإنجليزية',
  'subtitleSourcesSubtitle':
      'اختر مصدر ترجمة لـ {title}{target}، ثم اختر اللغة الهدف في الخطوة التالية.',
  'subtitleSourcesFailedTitle': 'تعذر تحميل مصادر الترجمة',
  'seriesSeasonsTitle': 'اختر موسمًا',
  'seriesSeasonsSubtitle': 'اختر موسمًا من {title} لاستعراض الحلقات المتاحة.',
  'seriesSeasonLabel': 'الموسم {seasonNumber}',
  'seriesSeasonMeta': '{episodeCount} حلقات{year}',
  'seriesEpisodesTitle': 'الموسم {seasonNumber}',
  'seriesEpisodesSubtitle': '{episodeCount} حلقات{year}',
  'seriesEpisodeLabel': 'الحلقة {episodeNumber}',
  'seriesEpisodeMeta': 'حوالي {runtime} دقيقة',
  'historyTitle': 'سجل الترجمة',
  'historySubtitle':
      'أعد فتح مهام الترجمة السابقة، وراجع المعاينة مرة أخرى، أو صدّرها لاحقًا.',
  'historyEmptyTitle': 'السجل فارغ',
  'historyEmptyMessage':
      'ستظهر مهام الترجمة هنا بعد إكمال مسار البحث أو رفع الملف.',
  'historyFailedTitle': 'تعذر تحميل السجل',
  'homeRecentJobsTitle': 'المهام الأخيرة',
  'homeRecentJobsSubtitle': 'أعد فتح أحدث جلسات الترجمة دون البدء من جديد.',
  'homeNoRecentTitle': 'لا توجد مهام حديثة بعد',
  'homeNoRecentMessage':
      'ابدأ بالبحث عن فيلم أو ارفع ملف ترجمة، وستظهر ترجماتك الأخيرة هنا.',
  'homeFailedRecentTitle': 'تعذر تحميل المهام الأخيرة',
  'homeTrustTitle': 'لماذا تثق به الفرق',
  'homeTrustSubtitle':
      'هو تجريبي اليوم، لكنه منظم مثل منتج جاهز للإطلاق الحقيقي.',
  'homeFutureTitle': 'مستودعات جاهزة للمستقبل',
  'homeFutureSubtitle':
      'المستودعات التجريبية القابلة للاستبدال تُبقي كود الواجهة معزولًا عن تغييرات الخادم.',
  'homePreviewTitle': 'تدفق ترجمة يبدأ بالمعاينة',
  'homePreviewSubtitle':
      'راجع النتائج قبل التصدير من خلال أوضاع العرض الأصلي أو المترجم أو ثنائي اللغة.',
  'homeStatesTitle': 'جميع الحالات مدعومة بسلاسة',
  'homeStatesSubtitle':
      'حالات التحميل والفراغ وإعادة المحاولة والتحقق وحتى سيناريوهات عدم الاتصال التجريبية جزء من التجربة منذ اليوم الأول.',
  'navHome': 'الرئيسية',
  'navHistory': 'السجل',
  'navSettings': 'الإعدادات',
  'heroTitle': 'ترجم الترجمات بسرعة أكبر',
  'heroSubtitle':
      'ابحث في كتالوجات الأفلام والمسلسلات، واختر المصادر، وصدّر ترجمات مصقولة خلال دقائق.',
  'heroBadge': 'تدفق ترجمة احترافي',
  'heroHeadline': 'ترجم ترجمات الأفلام والمسلسلات بتجربة احترافية.',
  'heroBody':
      'اختر بين كتالوج قابل للبحث أو رفع ملف مباشر، ثم عاين وصدّر ترجمات مصقولة خلال دقائق.',
  'heroSearchCta': 'ابحث عن فيلم / مسلسل',
  'heroUploadCta': 'رفع ترجمة',
  'heroStatPathsTitle': 'مساران',
  'heroStatPathsValue': 'بحث أو رفع',
  'heroStatLanguagesTitle': '10 لغات',
  'heroStatLanguagesValue': 'جاهزة للمعاينة',
  'heroStatMockTitle': 'واجهات وهمية',
  'heroStatMockValue': 'واجهة جاهزة للخادم',
  'settingsTitle': 'الإعدادات',
  'settingsSubtitle':
      'أدر الإعدادات الافتراضية للترجمة والمظهر ومعلومات التطبيق وعناصر بريميوم التجريبية.',
  'settingsLanguageLabel': 'لغة الهدف المفضلة',
  'settingsThemeLabel': 'المظهر',
  'themeSystem': 'النظام',
  'themeDark': 'داكن',
  'themeLight': 'فاتح',
  'settingsPremiumTitle': 'عنصر بريميوم تجريبي',
  'settingsPremiumSubtitle':
      'لاحقًا يمكننا ربط الاشتراكات والفوترة ومزامنة المشاريع السحابية هنا.',
  'settingsSupportTitle': 'عنصر دعم تجريبي',
  'settingsSupportSubtitle': 'صفحة مساعدة واتصال تجريبية',
  'settingsPrivacyTitle': 'سياسة الخصوصية',
  'settingsPrivacySubtitle': 'محتوى خصوصية تجريبي',
  'settingsTermsTitle': 'شروط الخدمة',
  'settingsTermsSubtitle': 'محتوى شروط تجريبي',
  'settingsMaintenanceTitle': 'الصيانة',
  'settingsMaintenanceSubtitle':
      'امسح مهام الترجمة الخاصة بهذا الجهاز وابدأ بسجل فارغ.',
  'settingsHistoryClearedSnack': 'تم مسح سجل الترجمة لهذا الجهاز',
  'settingsAboutTitle': 'حول SubFlix',
  'settingsVersion': 'الإصدار {version}',
  'settingsClearCache': 'مسح ذاكرة التخزين المؤقت',
  'settingsCacheCleared': 'تم مسح ذاكرة التخزين المؤقت',
  'settingsFailedTitle': 'فشل تحميل الإعدادات',
  'legalPlaceholderBody':
      'هذه الصفحة مجرد عنصر نائب في التطبيق التجريبي. اربطها بمحتواك القانوني الفعلي في الإصدار الإنتاجي.',
  'legalTitlePrivacy': 'سياسة الخصوصية',
  'legalTitleTerms': 'شروط الخدمة',
  'legalTitleSupport': 'الدعم',
  'legalTitleAbout': 'حول SubFlix',
  'legalBodyPrivacy':
      'يخزن SubFlix حاليًا فقط التفضيلات التجريبية وسجل الترجمة على الجهاز عبر التخزين المحلي. ويمكن أن يستبدل التكامل المستقبلي مع الخادم ذلك بتخزين موثّق، وسجلات تدقيق، وسياسات احتفاظ تُدار من الخادم.',
  'legalBodyTerms':
      'تم إنشاء هذا الإصدار التجريبي لاختبار تدفقات المنتج وحالات الواجهة وحدود المعمارية. وعند توصيل خادم NestJS وقاعدة بيانات Postgres لاحقًا، يمكن توسيع هذا القسم ببنود خدمة حقيقية وصياغات خاصة بمعالجة البيانات.',
  'legalBodySupport':
      'الدعم مجرد عنصر نائب حاليًا. وفي إصدار الإنتاج يمكن لهذا القسم أن يتصل بالبريد الإلكتروني، والإبلاغ عن المشكلات، ومساعدة الحسابات المميزة، مع بقاء هيكل التطبيق كما هو.',
  'legalBodyAbout':
      'SubFlix هو عميل Flutter بطابع احترافي لترجمة الترجمات بالذكاء الاصطناعي. يستخدم هذا الإصدار مستودعات تجريبية وتأخيرًا اصطناعيًا وتخزينًا محليًا حتى تتمكن الواجهة والمعمارية من التطور قبل توصيل خادم حقيقي.',
  'routeMissingSubtitleSourcesTitle': 'مصادر الترجمة',
  'routeMissingSubtitleSourcesMessage':
      'تعذر تحديد العنوان الذي يجب تحميل مصادر الترجمة له. ابدأ من البحث مرة أخرى.',
  'routeMissingSeriesSeasonsTitle': 'مواسم المسلسل',
  'routeMissingSeriesSeasonsMessage':
      'تعذر تحديد المسلسل الذي يجب تحميله. ابدأ من البحث مرة أخرى.',
  'routeMissingSeasonEpisodesTitle': 'حلقات الموسم',
  'routeMissingSeasonEpisodesMessage':
      'تعذر تحديد الموسم الذي يجب تحميله. ابدأ من البحث مرة أخرى.',
  'routeMissingTranslationSetupTitle': 'إعداد الترجمة',
  'routeMissingTranslationSetupMessage':
      'مطلوب مصدر ترجمة قبل أن يمكن فتح شاشة إعداد الترجمة.',
  'routeMissingTranslationProgressTitle': 'تقدم الترجمة',
  'routeMissingTranslationProgressMessage':
      'لم يتم تقديم طلب ترجمة. ابدأ ترجمة جديدة من البحث أو الرفع.',
  'searchResultPopularity': 'الشعبية {score}',
  'subtitleSourceLines': '{lineCount} سطر',
  'subtitleSourceDownloads': '{downloads} تنزيل',
  'subtitleSourceRating': 'التقييم {rating}',
  'subtitleSourceHiLabel': 'HI / SDH',
  'mediaTypeMovie': 'فيلم',
  'mediaTypeSeries': 'مسلسل',
  'jobReuseTranslation': 'إعادة استخدام الترجمة',
  'jobReuseSubtitle': 'إعادة استخدام ملف الترجمة',
  'jobConfidence': 'مستوى الثقة: {level}',
  'jobOpenPreview': 'فتح المعاينة',
  'onboardingPage1Title':
      'اعثر على الأفلام أو المسلسلات واسحب ترجمات جاهزة للترجمة.',
  'onboardingPage1Eyebrow': 'ابحث واستورد',
  'onboardingPage1Description':
      'ابحث عن عنوان، وراجع مصادر الترجمة الإنجليزية المتاحة، وابدأ تدفق ترجمة يبدو فوريًا.',
  'onboardingPage1Highlight1': 'كتالوج تجريبي حتمي لتطوير موثوق',
  'onboardingPage1Highlight2': 'ملصقات جودة المصدر وشارات الصيغة',
  'onboardingPage1Highlight3': 'مصمم ليُستبدل بخادم حقيقي لاحقًا',
  'onboardingPage2Title':
      'ارفع ملفات `.srt` أو `.vtt` عندما يكون لديك النص بالفعل.',
  'onboardingPage2Eyebrow': 'أحضر ملفك الخاص',
  'onboardingPage2Description':
      'استورد ملف الترجمة، وتحقق من الصيغة، وشغّل نفس مسار الترجمة المصقول دون مغادرة التطبيق.',
  'onboardingPage2Highlight1': 'تحقق محلي من الملف مع حالات إعادة محاولة سلسة',
  'onboardingPage2Highlight2': 'إعداد ترجمة موحّد للرفع والبحث',
  'onboardingPage2Highlight3': 'عاين قبل التصدير حتى لا يبدو شيء غامضًا',
  'onboardingPage3Title': 'اختر اللغات الهدف، وعاين الترجمة، وصدّر فورًا.',
  'onboardingPage3Eyebrow': 'ترجم وصدّر',
  'onboardingPage3Description':
      'بدّل بين العرض الأصلي والمترجم وثنائي اللغة، وارجع إلى السجل، وصدّر ملفات ترجمة نظيفة عندما تبدو النتيجة مناسبة.',
  'onboardingPage3Highlight1':
      'عناصر تحكم سريعة للمعاينة مع البيانات الوصفية والبحث',
  'onboardingPage3Highlight2':
      'يحافظ السجل على المهام السابقة على بُعد نقرة واحدة',
  'onboardingPage3Highlight3': 'مصمم كأداة وسائط احترافية، لا كعرض تجريبي',
  'onboardingStart': 'ابدأ الترجمة',
  'onboardingNext': 'التالي',
  'onboardingSkip': 'تخطي',
  'onboardingContinue': 'متابعة',
  'onboardingEnterApp': 'الدخول إلى SubFlix',
  'splashHeadline': 'SubFlix',
  'splashSubtitle': 'ترجمة الترجمات بالذكاء الاصطناعي',
  'splashPreparing': 'جارٍ تجهيز استوديو الترجمة الخاص بك',
  'brandSubtitleCompact': 'ذكاء الترجمة',
  'brandSubtitleFull': 'استوديو ترجمة الترجمات بالذكاء الاصطناعي',
  'comingSoonTitle': 'قريبًا',
  'comingSoonMessage': 'ما زلنا نجهّز هذه الشاشة.',
};
